## Solicitacao do professor Roberto Matos atraves do chamado IFSC#2019070410000533
#### VERSAO ANTIGA
# - name: Baixando e extraindo os softwares da microchip - Linux Debian
#   unarchive:
#     src: https://discovirtual.ifsc.edu.br/index.php/s/jFJXF4Sk7Ou4k31/download
#     dest: /opt/
#     creates: /opt/microchip/mplabx/v5.20/mplab_platform/bin/mplab_ide
#     remote_src: yes
#     owner: root
#     group: root
#   when: ansible_os_family == 'Debian'

- name: Verificando se eh versao nova do mplab - Linux Debian
  ansible.builtin.shell: ls /opt/microchip/mplabx
  register: result_mplab
  changed_when: False
  failed_when: False
  when: ansible_os_family == 'Debian'

- name: Apagando mplab - Linux
  file:
    state: absent
    path: /opt/microchip/
  when: (ansible_os_family == 'Debian' and result_mplab.stdout.find('5.5') == -1)

- name: Apagando links mplab - Linux
  file:
    state: absent
    path: /usr/bin/{{ old_mplab_link }}
  loop:
    - mplab_ide
    - mplab_ipe
    - mdb
  loop_control:
    loop_var: old_mplab_link
  when: (ansible_os_family == 'Debian' and result_mplab.stdout.find('5.5') == -1)

### Gambiarra para baixar arquivo do Google Drive, limite de 12 conexões simultâneas
- name: Baixar mplab - Linux Debian
  shell: wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1HrdzV-MYGFEMW4zvFgvaMugyhlCJ0wGo' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1HrdzV-MYGFEMW4zvFgvaMugyhlCJ0wGo" -O /tmp/mplab.bz && rm -rf /tmp/cookies.txt
  args:
    creates: /opt/microchip
  when: ansible_os_family == 'Debian'

- name: Extraindo mplab - Linux Debian
  unarchive:
    src: /tmp/mplab.bz
    dest: /opt/
    owner: root
    creates: /opt/microchip
    mode: 0755
    remote_src: yes
  when: ansible_os_family == 'Debian'

- name: Extraindo avr8 toolchain - Linux Debian
  unarchive:
    src: avr8-toolchain.bz
    dest: /opt/microchip
    creates: /opt/microchip/avr8-gnu-toolchain
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: Copiando arquivos .rules - Linux Debian
  copy:
    src: "{{ rules_mplab }}"
    dest: /etc/udev/rules.d
    owner: root
    group: root
    mode: 0664
  loop:
    - 99-jlink.rules
    - z010_mchp_tools.rules
    - z011_mchp_jlink.rules
    - z012_mchp_efr.rules
  loop_control:
    loop_var: rules_mplab
  when: ansible_os_family == 'Debian'

# - name: Adicionar PATH  - Linux Debian
#   lineinfile:
#     regexp: "^export OLDPATH="
#     state: present
#     path: /etc/bash.bashrc
#     line: 'export OLDPATH=/home/aluno'
#   when: ansible_os_family == 'Debian'

- name: Copiando os atalhos MPLAB - Linux Debian
  copy:
    src: "{{ mplab_desktop }}"
    dest: /usr/share/applications/
    owner: root
    group: root
    mode: 0644
  loop:
    - mplab.desktop
    - mplab_ipe.desktop
  loop_control:
    loop_var: mplab_desktop
  when: ansible_os_family == 'Debian'

- name: Copiando figuras - Linux Debian
  copy:
    src: "{{ mplab_figs }}"
    dest: /usr/share/icons/
    owner: root
    group: root
    mode: 0755
  loop:
    - mplab_ide.png
    - mplab_ipe.png
  loop_control:
    loop_var: mplab_figs
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo m328pdef.inc - Linux Debian
  copy:
    src: m328pdef.inc
    dest: /opt/microchip/xc8/v2.05/dfp/avrasm/inc/
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Criando links simbolicos - Linux Debian
  file:
    src: /opt/microchip/mplabx/v5.50/mplab_platform/bin/{{ mplab_link }}
    dest: /usr/bin/{{ mplab_link }}
    state: link
  loop:
    - mplab_ide
    - mplab_ipe
  loop_control:
    loop_var: mplab_link
  when: ansible_os_family == 'Debian'

- name: Criando link simbolico com nome diferente - Linux Debian
  file:
    src: /opt/microchip/mplabx/v5.50/mplab_platform/bin/mdb.sh
    dest: /usr/bin/mdb
    state: link
  when: ansible_os_family == 'Debian'

# Antes de executar os comandos abaixo, precisa reiniciar as
# máquinas para confirmar que o /home/aluno estão limpos.

- name: Copiando arquivos de configuracao de usuario
  copy:
    src: "{{ mplab_config }}"
    dest: /home/aluno/
    owner: aluno
    group: root
    mode: 0755
  loop:
    - .mchp_packs
    - .mplabcomm
    - .mplab_ide
  loop_control:
    loop_var: mplab_config
  when: (ansible_os_family == 'Debian' and  play == 1)

- name: Faz backup do último aluno.tgz e cria um novo com as novas configuracoes
  shell: /bin/mv /home/backup/aluno.tgz /home/backup/aluno-$(date +'%d-%m-%Y').tgz ; /bin/tar -zcvf /home/backup/aluno.tgz /home/aluno
  when: (ansible_os_family == 'Debian' and  play == 1)
