## Instala Eclipse com suporte a C/C++ e Java - Alternativa ao Eclipse modificado que o Arliones tinha sugerido.

- name: Instala Eclipse com suporte a C/C++ e Java - Linux
  ansible.builtin.apt:
    state: latest
    pkg:
    - eclipse-cdt
    - eclipse
    - eclipse-cdt-autotools
    - eclipse-cdt-jni
    - eclipse-egit
    - eclipse-gef
    - eclipse-emf
    - eclipse-jdt
    - eclipse-pde
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

- name: Copia plugins do avr - Linux
  ansible.builtin.copy:
    src: "{{ plugin_avr }}"
    dest: /usr/lib/eclipse/plugins
    owner: root
    group: root
    mode: 0554
  loop:
    - de.innot.avreclipse.core_2.4.1.jar
    - de.innot.avreclipse.core.managedbuildsystem_2.4.1.jar
    - de.innot.avreclipse.doc_2.4.1.jar
    - de.innot.avreclipse.root_2.4.1.jar
    - de.innot.avreclipse.ui_2.4.1.jar
  loop_control:
    loop_var: plugin_avr
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

- name: Baixa e extrai eclipse 8.8 - Debian 11
  ansible.builtin.unarchive:
    src: http://ansiblefiles.sj.ifsc.edu.br/eclipse-cpp-mars-2-linux-gtk-x86_64.tar.gz
    dest: /opt/intelFPGA/18.1/nios2eds/bin/
    creates: /opt/intelFPGA/18.1/nios2eds/bin/eclipse_nios2/plugin_customization.ini
    remote_src: true
    owner: root
    group: root
    mode: 0755
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Extrai plugins eclipse - Debian 11
  ansible.builtin.unarchive:
    src: /opt/intelFPGA/18.1/nios2eds/bin/eclipse_nios2_plugins.tar.gz
    dest: /opt/intelFPGA/18.1/nios2eds/bin
    creates: /opt/intelFPGA/18.1/nios2eds/bin/eclipse_nios2/plugin_customization.ini
    owner: root
    group: root
    mode: 0755
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')


- name: Inserir linha para arrumar eclipse
  blockinfile:
    path: /opt/intelFPGA/20.1/nios2eds/bin/eclipse_nios2/eclipse.ini
    insertbefore: --launcher.appendVmargs
    block: |
      --launcher.GTK_version
      2
    state: present
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')
