---
- name: Instala snapd - Linux
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - snapd
  when: ansible_os_family == 'Debian'

- name: Instala shotcut via SNAP
  command: /usr/bin/snap install shotcut --classic
  args:
    creates: /snap/shotcut
  when: ansible_os_family == 'Debian'

- name: Instalar pacotes pra aceleração de hardware - Linux
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - qemu-kvm
    - bridge-utils
    - libvirt-daemon
  when: ansible_os_family == 'Debian'

- name: Cria atalho para o shotcut
  copy:
    content: |
      [Desktop Entry]
      Version=1.0
      Name=Shotcut
      Comment=cross-platform video editor
      Exec=/snap/bin/shotcut
      Icon=/snap/shotcut/282/meta/gui/shotcut-logo-64.png
      Terminal=false 
      Type=Application
      Categories=AudioVideo;Recorder;
    dest: /usr/share/applications/shotcut.desktop
  when: ansible_os_family == 'Debian'