#Windows

- name: Baixar e instalar o Pack Calculation PRO - Windows
  ansible.windows.win_package:
    path: https://www.ipu.dk/wp-content/uploads/2025/03/packcalculationpro-5630.exe
    arguments:
      - /VERYSILENT
      - /SUPRESSMSGBOXES
      - /NORESTART
      - /SP-
    product_id: 'Pack Calculation Pro_is1'
    state: present
  when: ansible_os_family == 'Windows'

- name: Baixar e instalar o CoolPack - Windows
  ansible.windows.win_package:
    path: https://www.ipu.dk/wp-content/uploads/2018/10/coolpack-v150.exe
    arguments:
      - /VERYSILENT
      - /SUPRESSMSGBOXES
      - /NORESTART
      - /SP-
    product_id: 'CoolPack_is1'
    state: present
  when: ansible_os_family == 'Windows'

- name: Baixar e instalar o SecCool - Windows
  ansible.windows.win_package:
    path: https://www.ipu.dk/wp-content/uploads/2024/06/seccool-x64-2020.exe
    arguments:
      - /VERYSILENT
      - /SUPRESSMSGBOXES
      - /NORESTART
      - /SP-
    product_id: 'SecCool_is1'
    state: present
  when: ansible_os_family == 'Windows'

- name: Baixar e instalar o Simple one-stage CO2  (Transcritical CO2 cycles)- Windows
  ansible.windows.win_package:
    path: https://www.ipu.dk/wp-content/uploads/2024/09/simpleonestage-302.exe
    arguments:
      - /VERYSILENT
      - /SUPRESSMSGBOXES
      - /NORESTART
      - /SP-
    product_id: 'Simple One Stage CO2 Cycle_is1'
    state: present
  when: ansible_os_family == 'Windows'

### Comando em powershell para mostrar product_id
### get-wmiobject Win32_Product | Format-Table IdentifyingNumber, Name, LocalPackage -AutoSize
### Localizacao do productid 32 bits: HKLM:Software\Microsoft\Windows\CurrentVersion\Uninstall
### Localizacao do productid 64 bits: HKLM:Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall
