# Linux Debian 11
- name: Arquivo do source list - Debian bullseye
  ansible.builtin.copy:
    src: sources.bullseye.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution_release == 'bullseye'

# Linux Debian 12
- name: Arquivo do source list - Debian bookworm
  ansible.builtin.copy:
    src: sources.bookworm.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution_release == 'bookworm'

# Linux Debian 13
- name: Arquivo do source list - Debian trixie
  ansible.builtin.copy:
    src: sources.trixie.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution_release == 'trixie'

- name: Atualiza cache do apt
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == 'Debian'
