- name: Instala MySQL Workbench
  community.general.snap:
    name:
      - core
      - mysql-workbench-community
  when: ansible_os_family == 'Debian'

- name: Cria atalho mysql-workbench-community
  ansible.builtin.file:
    src: /var/lib/snapd/desktop/applications/mysql-workbench-community_mysql-workbench-community.desktop
    dest: /usr/share/applications/mysql-workbench-community_mysql-workbench-community.desktop
    owner: root
    group: root
    state: link
  when: ansible_os_family == 'Debian'
