# Linux
- name: Instalando o pacote necessario
  ansible.builtin.apt:
    name: x11vnc
  when: ansible_os_family == 'Debian'

- name: Copiando o arquivo .desktop Acesso remoto - Linux
  ansible.builtin.copy:
    src: suporte_remoto.desktop
    dest: /usr/share/applications/suporte_remoto.desktop
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

# Copiado os icones

- name: Copiando o icone Acesso remoto - Linux
  ansible.builtin.copy:
    src: suporte_remoto.png
    dest: /var/
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

# Windows
- name: Criar a pasta do UltraVNC - Windows
  ansible.windows.win_file:
    path: C:\Program Files\uvnc bvba\UltraVnc
    state: directory
  when: ansible_os_family == 'Windows'

- name: Copia o arquivo de configuracao do UltraVNC - Windows
  ansible.windows.win_copy:
    src: UltraVNC.ini
    dest: C:\Program Files\uvnc bvba\UltraVnc\UltraVNC.ini
  when: ansible_os_family == 'Windows'

- name: Libera porta 5900 UltraVNC Firewall - Windows
  community.windows.win_firewall_rule:
    name: OpenVNC
    localport: 5900
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
  when: ansible_os_family == 'Windows'
