### Comando em powershell para mostrar product_id
### get-wmiobject Win32_Product | Format-Table IdentifyingNumber, Name, LocalPackage -AutoSize
### Localizacao do productid 32 bits: HKLM:Software\Microsoft\Windows\CurrentVersion\Uninstall
### Localizacao do productid 64 bits: HKLM:Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall

- name: Cria pasta para instaladores
  ansible.windows.win_file:
    path: C:\instaladores
    state: directory
  when: ansible_os_family == 'Windows'

- name: Instala o Microsoft Visual C++ Redistributable for Visual Studio 2015-2026 14.51.36247
  chocolatey.chocolatey.win_chocolatey:
    name:
      - vcredist140
  when: ansible_os_family == 'Windows'

- name: Baixa o Sketchup 2017 e plugin Euclid
  ansible.windows.win_get_url:
    url: "{{ item.url }}"
    dest: C:\instaladores
    checksum: "{{ item.checksum }}"
  loop:
    - url: http://ansiblefiles.sj.ifsc.edu.br/euclid-0.9.4.4.rbz
      checksum: 414ab860d8ca194d48a388ab38744d031edc0219
    - url: http://ansiblefiles.sj.ifsc.edu.br/SketchUp2017-x64.msi
      checksum: d2e022879ea84cd67690e1435b92ddee1551725e
  tags:
    - download
  when: ansible_os_family == 'Windows'

- name: Instalar o Sketchup 2017 silenciosamente - Windows
  ansible.windows.win_package:
    path: C:\instaladores\SketchUp2017-x64.msi
    arguments:
      - /quiet
    product_id: {5BF32B95-4930-40AC-A756-C2837997EAA2}
  tags:
    - install_sketchup
  when: ansible_os_family == 'Windows'
