#Windows

- name: Baixar o instalador do LINK Planner 5.6.4 - Windows
  win_get_url:
    url: 'https://discovirtual.ifsc.edu.br/index.php/s/zHptrJ0Ml6ZNb4m/download'
    dest: 'C:\instaladores\link-planner.exe'
    timeout: 120
  when: ansible_os_family == 'Windows'

- name: Instalar o LINK Planner 5.6.4 - Windows
  win_package:
    path: 'C:\instaladores\link-planner.exe'
    arguments: '/VERYSILENT /SUPRESSMSGBOXES /NORESTART /SP-'
    product_id: 'Cambium PTP Link Planner_is1'
    state: present
  when: ansible_os_family == 'Windows'

### Comando em powershell para mostrar product_id
### get-wmiobject Win32_Product | Format-Table IdentifyingNumber, Name, LocalPackage -AutoSize
### Localizacao do productid 32 bits: HKLM:Software\Microsoft\Windows\CurrentVersion\Uninstall
### Localizacao do productid 64 bits: HKLM:Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall
