######################## OBSERVAÇÕES IMPORTANTES ######################
#######################################################################
#######################################################################
# Há roles que precisam ser atualizados de tempos em tempos.
# Deve-se adicionar aqui os roles que perceberem que necessitam atualizações
# - Atualizar os patrimonio do role configura_monitores
#######################################################################

# - name: Servidor controlador
#   hosts: controlador
#   tasks:
#     # USAR O CPF COMO USUÁRIO E A SENHA DEVE TER NO MÍNIMO 8 dígitos
#     - name: Cria usuários para o IFSC-Terceirizados
#       ansible.builtin.shell: "samba-tool user create {{ item.user }} {{ item.password }} --userou=OU=terceirizados && samba-tool user setexpiry --days=365 {{ item.user }}"
#       loop:
#         - { user: 12345678910, password: 87654321 }

######### Correção das máquinas virtuais ############
# - hosts: laboratorios_lin
#   1 - Executar primeiro
#   tasks:
#     - name: Remove arquivos da pasta Virtualbox
#       raw: rm -rf /opt/vms/'VirtualBox VMs'/*
#     - name: Remove configurações das máquinas virtuais
#       raw: rm -rf /opt/vms/.config/VirtualBox/*
#   roles:
#     - aluno #### 2 - Depois executar apenas isso
# 3 - Depois executar apenas isso
#   tasks:
#     - name: Reinicia o computador
#       raw: reboot
#   roles:
#     - criar_vm #### 4 - Por último executar isso

# - name: Manage local user aluno on a Windows remote host # ( ESTÁ funcionando )
#   hosts: sje-ctic-866467.maquinas.sj.ifsc.edu.br
#   gather_facts: no
#   vars:
#     ansible_winrm_transport: basic
#     ansible_winrm_server_cert_validation: ignore

#   tasks:
#     - name: Add user "aluno" to local group "Usuários"
#       win_group_membership:
#         name: Usuários
#         members:
#           - aluno
#         state: present
#
# ## Remover do LDAP ##############

# - hosts: laboratorios_lin
#   roles:
#     - mplab
#
# ## Instala Impressoras CUPS ##############

# - name: Desligar todos os computadores de um  grupo
#   hosts: programacao_lin
#   tasks:
#     - name: Enviar comando de desligamento
#       ansible.builtin.command:
#         cmd: /sbin/shutdown -h now
#       ignore_errors: true
#       register: shutdown_result
#     - name: Mostrar status do desligamento
#       ansible.builtin.debug:
#         var: shutdown_result

######### Executar o Windows Update em Hosts windows remotos

# - name: Executar o Windows Update em Hosts windows remotos
#   hosts: sj-labter-614120.maquinas.sj.ifsc.edu.br
#   tasks:
#     - name: Run Windows Update
#       win_updates:
#         category_names:
#           - CriticalUpdates
#           - SecurityUpdates
#           - UpdateRollups
#           - FeaturePacks
#           - ServicePacks
#         state: installed
#         reboot: yes

# - hosts: laboratorios_lin
#   tasks:
#     - name: Copia um arquivo para as maquinas - Linux
#       ansible.builtin.copy:
#         src: /dados/backup/{{ item }}
#         dest: /usr/share/applications/
#         owner: root
#         group: root
#         mode: 0644
#       loop:
#         - google-chrome.desktop
#         - firefox-esr.desktop

# - name: Executa alguma coisa
#   hosts: laboratorios_win
#   tasks:
#     - name: Desativa o início rápido para o WOL funcionar
#       ansible.windows.win_regedit:
#         path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Power
#         name: HiberbootEnabled
#         data: 0
#         type: dword

## Executar no final do semestre
# - hosts: laboratorios_lin
#   roles:
    # - chaves_ssh
    # - firewall_labs
    # - final_semestre
    #  - gradle

# - hosts: all
#   tasks:
#     - name: enable TLSv1.2 support
#       win_regedit:
#         path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\{{ item.type }}
#         name: '{{ item.property }}'
#         data: '{{ item.value }}'
#         type: dword
#         state: present
#       register: enable_tls12
#       loop:
#       - type: Server
#         property: Enabled
#         value: 1
#       - type: Server
#         property: DisabledByDefault
#         value: 0
#       - type: Client
#         property: Enabled
#         value: 1
#       - type: Client
#         property: DisabledByDefault
#         value: 0
#         when: (ansible_os_family == 'Windows' and ansible_os_name == 'Microsoft Windows 7 Professional')

#     - name: reboot if TLS config was applied
#       win_reboot:
#       when: enable_tls12 is changed

# - hosts: laboratorios_win
#   tasks:
#     - name: Corrigir problema com senha expirada
#       ansible.windows.win_user:
#         name: aluno
#         password_expired: false
#         password_never_expires: true
#         user_cannot_change_password: true
#       when: ansible_os_family == 'Windows'

# # LIMPA TEMP WINDOWS
# - hosts: laboratorios_win
#   roles:
#     - role: limpa_temp_windows
#       play: 0
#       # play: 0 desativa
#       # play: 1 ativa

# # ATUALIZA MAC
# # SEMPRE VERIFICAR O HOST QUE QUER ATINGIR
# - hosts: laboratorios_lin
#   roles:
#     - role: atualiza_mac
#       play: 0
#       # play: 0 desativa
#       # play: 1 ativa

## DESCOMENTAR PARA CORRIGIR O EPOPTES, PEGAR AS CHAVES DO SERVER. COMENTAR NOVAMENTE DEPOIS.
## LEMBRAR DE RODAR COM A OPÇÃO -l GRUPO_DO_LAB
# - hosts: laboratorios_lin
#   tasks:
#     - name: Pegar as chaves do epoptes server no cliente - Linux
#       shell: /usr/sbin/epoptes-client -c
#       when: ansible_os_family == 'Debian'

##RESOLVENDO PROBLEMA DAS INTERFACES DE REDE DO OPENVSWITCH NOS LABS
# - hosts: laboratorios_lin
#   tasks:
#     - name: Apagar as interfaces virtuais de rede
#       shell: for x in $(ovs-vsctl list-br); do ovs-vsctl del-br ${x}; done
#       when: ansible_os_family == 'Debian'

# - hosts: sidi_win
#   tasks:
#     - name: Turn off computers Windows
#       raw: shutdown /s /hybrid /t 15 /c "We are turning computers off after maintenance"

# - hosts: programacao_lin
#   tasks:
#     - name: Reboot computer para Windows
#       raw: grub-reboot 2
#     - name: Turn off computers
#       raw: reboot

# - hosts: laboratorios_lin
#   roles:
#     - role: restaura_vms
#       nome_vms:
#         - 1-Servidor
#         - 2-Servidor
#         - 3-Servidor
#         - 4-Servidor
#         - 5-Servidor
#         - 6-Servidor
#         - 7-Servidor

# - hosts: laboratorios_lin
#   roles:
#     - role: restaura_vms_grafico
#       nome_vms:
#         - 1-Grafico
#         - 2-Grafico
#         - 3-Grafico
#         - 4-Grafico

# - hosts: all
#   tasks:
#     - name: Get the MAC address
#       debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
#     - name: Salvar na maquina que esta executando o ansible os enderecos macs
#       local_action: shell echo "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}" >> /tmp/output

# - win_shell: netsh interface ip add wins name=LAN addr=172.18.109.10 index=0

################### Limpar home do aluno no windows ###################
# - name: Remove conta do aluno
#   win_user:
#     name: aluno
#     state: absent
#   when: ansible_os_family == 'Windows'

# - name: Remove profile do aluno
#   win_user_profile:
#     name: aluno
#     state: absent
#     remove_multiple: yes
#   when: ansible_os_family == 'Windows'

# - name: Remove a pasta do aluno
#   win_file:
#     path: C:\Users\aluno
#     state: absent
#   when: ansible_os_family == 'Windows'

# - name: cria usuário aluno
#   win_user:
#     name: aluno
#     password_expired: no
#     state: present
#     user_cannot_change_password: yes
#     groups:
#       - "Usuários"
#   when: ansible_os_family == 'Windows'
#
#
#
# - name: Forçar logoff em todas as máquinas do grupo programacao_win
#   hosts: programacao_win
#   gather_facts: no
#   tasks:
#     - name: Forçar logoff da sessão ativa
#       ansible.windows.win_shell: |
#         query session | findstr "Active" | for /F "tokens=3" %i in ('more') do logoff %i
#       register: logoff_result
#       ignore_errors: yes

#     - name: Exibir saída do logoff
#       debug:
#         var: logoff_result.stdout_lines

# - name: Executar Windows Update (baixar e instalar todas as atualizações)
#   win_updates:
#     category_names:
#       - SecurityUpdates
#       - CriticalUpdates
#       - UpdateRollups
#       - DefinitionUpdates
#       - Updates
#     reboot: yes
#
#
# - name: Modificar /etc/default/grub para ativar OS Prober ( Dual bot grub / Windows Boot Manager )
#   hosts: programacao_lin
#   become: yes
#   tasks:
#     - name: Garantir que GRUB_DISABLE_OS_PROBER=false está descomentado
#       lineinfile:
#         path: /etc/default/grub
#         regexp: '^#?GRUB_DISABLE_OS_PROBER='
#         line: 'GRUB_DISABLE_OS_PROBER=false'
#         backrefs: yes

#     - name: Atualizar GRUB
#       command: update-grub

#######################################################################
