---
- hosts:  sj-labter-614120.maquinas.sj.ifsc.edu.br 
  roles:
    - create_user_aluno
#
# - name: Criar conta de usuário aluno no host local
#   hosts: sje-lin-note-3849460.maquinas.sj.ifsc.edu.br 
#   tasks:
#     - name: Criar diretório home
#       file:
#         path: /home/aluno
#         state: directory
#         owner: aluno
#         group: aluno
#         mode: '0755'
#     - name: Criar conta de usuário
#       user:
#         name: aluno
#         password: "{{ 'aluno' | password_hash('sha512') }}"
#         shell: /bin/bash
#         home: /home/aluno
#         createhome: no


# - name: Servidor controlador
#   hosts: controlador
#   tasks:
#     # USAR O CPF COMO USUÁRIO E A SENHA DEVE TER NO MÍNIMO 8 dígitos
#     - name: Cria usuários para o IFSC-Terceirizados
#       ansible.builtin.shell: "samba-tool user create {{ item.user }} {{ item.password }} --userou=OU=terceirizados && samba-tool user setexpiry --days=365 {{ item.user }}"
#       loop:
#         - { user: 12345678910, password: 87654321 }

# - hosts: csfio_lin
#   tasks:
#     - name: Mantem o estado do arquivo /etc/network/interfaces - Linux
#       ansible.builtin.copy:
#         content: |
#           search sj.ifsc.edu.br
#           nameserver 191.36.8.66
#           nameserver 191.36.8.90
#           nameserver 191.36.15.200
#         dest: /etc/resolv.conf
#         owner: root
#         group: root
#         mode: 0644

# - hosts: laboratorios_lin
#   tasks:
#     - name: Copia um arquivo para as maquinas - Linux
#       ansible.builtin.copy:
#         src: /dados/backup/{{ item }}
#         dest: /usr/share/applications/
#         owner: root
#         group: root
#         mode: 0644
#       with_items:
#         - google-chrome.desktop
#         - firefox-esr.desktop

# - name: Executa alguma coisa
#   hosts: sj-ctic-1bw10.maquinas.sj.ifsc.edu.br
#   tasks:
#     - name: Desativa o início rápido para o WOL funcionar
#       ansible.windows.win_regedit:
#         path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Power
#         name: HiberbootEnabled
#         data: 0
#         type: dword

## Executar no final do semestre
# - hosts: programacao_lin
#   roles:
    # - chaves_ssh
    # - firewall_labs
    # - final_semestre
    #  - gradle
  # roles:
  #   - role: atualiza_mac
  #     play: 1
      # play: 0 desativa
      # play: 1 ativa

# - hosts: sj-lin-dire-38132.maquinas.sj.ifsc.edu.br

#   tasks:
#     - name: Configura printers.conf
#       ansible.builtin.copy:
#         content: |
#           ServerName 191.36.8.74
#         dest: /etc/cups/client.conf
#         owner: 'root'
#         group: 'root'
#         mode: '0644'

# - hosts:  sje-lin-suped-920798.maquinas.sj.ifsc.edu.br
#   roles:
#     - remove_ldap

# - hosts: all
#   tasks:
#     - name: enable TLSv1.2 support
#       win_regedit:
#         path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\{{ item.type }}
#         name: '{{ item.property }}'
#         data: '{{ item.value }}'
#         type: dword
#         state: present
#       register: enable_tls12
#       loop:
#       - type: Server
#         property: Enabled
#         value: 1
#       - type: Server
#         property: DisabledByDefault
#         value: 0
#       - type: Client
#         property: Enabled
#         value: 1
#       - type: Client
#         property: DisabledByDefault
#         value: 0
#         when: (ansible_os_family == 'Windows' and ansible_os_name == 'Microsoft Windows 7 Professional')

#     - name: reboot if TLS config was applied
#       win_reboot:
#       when: enable_tls12 is changed

# - hosts: laboratorios_win
#   tasks:
#     - name: Corrigir problema com senha expirada
#       ansible.windows.win_user:
#         name: aluno
#         password_expired: false
#         password_never_expires: true
#         user_cannot_change_password: true
#       when: ansible_os_family == 'Windows'

# # LIMPA TEMP WINDOWS
# - hosts: laboratorios_win
#   roles:
#     - role: limpa_temp_windows
#       play: 0
#       # play: 0 desativa
#       # play: 1 ativa

# # ATUALIZA MAC
# # SEMPRE VERIFICAR O HOST QUE QUER ATINGIR
# - hosts: laboratorios_lin
#   roles:
#     - role: atualiza_mac
#       play: 0
#       # play: 0 desativa
#       # play: 1 ativa

## DESCOMENTAR PARA CORRIGIR O EPOPTES, PEGAR AS CHAVES DO SERVER. COMENTAR NOVAMENTE DEPOIS.
## LEMBRAR DE RODAR COM A OPÇÃO -l GRUPO_DO_LAB
# - hosts: laboratorios_lin
#   tasks:
#     - name: Pegar as chaves do epoptes server no cliente - Linux
#       shell: /usr/sbin/epoptes-client -c
#       when: ansible_os_family == 'Debian'

##RESOLVENDO PROBLEMA DAS INTERFACES DE REDE DO OPENVSWITCH NOS LABS
# - hosts: laboratorios_lin
#   tasks:
#     - name: Apagar as interfaces virtuais de rede
#       shell: for x in $(ovs-vsctl list-br); do ovs-vsctl del-br ${x}; done
#       when: ansible_os_family == 'Debian'

# - hosts: sidi_win
#   tasks:
#     - name: Turn off computers Windows
#       raw: shutdown /s /hybrid /t 15 /c "We are turning computers off after maintenance"

# - hosts: programacao_lin
#   tasks:
#     - name: Reboot computer para Windows
#       raw: grub-reboot 2
#     - name: Turn off computers
#       raw: reboot

# - hosts: laboratorios_lin
#   roles:
#     - role: restaura_vms
#       nome_vms:
#         - 1-Servidor
#         - 2-Servidor
#         - 3-Servidor
#         - 4-Servidor
#         - 5-Servidor
#         - 6-Servidor
#         - 7-Servidor

# - hosts: laboratorios_lin
#   roles:
#     - role: restaura_vms_grafico
#       nome_vms:
#         - 1-Grafico
#         - 2-Grafico
#         - 3-Grafico
#         - 4-Grafico

# #
# ## Utilizado para fazer o hold do linux-image e linux-headers e reinstalar o virtualbox-dkms
# #
# - hosts: laboratorios_lin
#   tasks:

#     - name: apaga /etc/apt/sources.list.d/ftp_debian_org_debian.list
#       file:
#         path: /etc/apt/sources.list.d/ftp_debian_org_debian.list
#         state: absent
#       when: ansible_os_family == 'Debian'

#     - name: Run the equivalent of "apt-get update" as a separate step
#       apt:
#         update_cache: yes
#       when: ansible_os_family == 'Debian'

#     - name: Upgrade all packages to the latest version
#       apt:
#         name: "*"
#         state: latest
#       when: ansible_os_family == 'Debian'

#     - name: seleciona a entrada grub 0 para o próximo boot
#       shell: grub-reboot 0
#       when: ansible_os_family == 'Debian'

#     - name: Unconditionally reboot the machine with all defaults
#       reboot:
#       when: ansible_os_family == 'Debian'

#     - name: instala kernel headers atual
#       apt:
#         name: "linux-headers-{{ ansible_kernel }}"
#       when: ansible_os_family == 'Debian'

#     # Quando quiser atualizar precisar alterar o selection para "install"
#     - name: Faz hold no linux-image
#       dpkg_selections:
#         name: "linux-image-{{ ansible_kernel }}"
#         selection: hold
#       when: ansible_os_family == 'Debian'

#     # Quando quiser atualizar precisar alterar o selection para "install"
#     - name: Faz hold no linux-image
#       dpkg_selections:
#         name: "linux-headers-{{ ansible_kernel }}"
#         selection: hold
#       when: ansible_os_family == 'Debian'

#     - name: reinstala virtualbox-dkms
#       shell:  aptitude reinstall virtualbox-dkms
#       when: ansible_os_family == 'Debian'

# - hosts: all
#   tasks:
#     - name: Get the MAC address
#       debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
#     - name: Salvar na maquina que esta executando o ansible os enderecos macs
#       local_action: shell echo "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}" >> /tmp/output

# - win_shell: netsh interface ip add wins name=LAN addr=172.18.109.10 index=0

# - name: Install HPLIP on Debian
#   hosts: sj-lin-biblio-36076.maquinas.sj.ifsc.edu.br
#   become: yes

#   tasks:
#     - name: Update apt cache
#       apt:
#         update_cache: yes

#     - name: Install required packages
#       apt:
#         name: "{{ item }}"
#         state: present
#       with_items:
#         - hplip
#         - hplip-gui

#     - name: Ensure the cups service is running
#       service:
#         name: cups
#         state: started
#         enabled: yes
#
######################### Instala Gnome Online Accounts no debian ##############
#
#     - name: Install gnome-online-accounts
#       apt:
#        name: gnome-online-accounts
#        state: present

################### Limpar home do aluno no windows ###################
# - name: Remove conta do aluno
#   win_user:
#     name: aluno
#     state: absent
#   when: ansible_os_family == 'Windows'

# - name: Remove profile do aluno
#   win_user_profile:
#     name: aluno
#     state: absent
#     remove_multiple: yes
#   when: ansible_os_family == 'Windows'

# - name: Remove a pasta do aluno
#   win_file:
#     path: C:\Users\aluno
#     state: absent
#   when: ansible_os_family == 'Windows'

# - name: cria usuário aluno
#   win_user:
#     name: aluno
#     password_expired: no
#     state: present
#     user_cannot_change_password: yes
#     groups:
#       - "Usuários"
#   when: ansible_os_family == 'Windows'
#######################################################################


######################## OBSERVAÇÕES IMPORTANTES ######################
#######################################################################
#######################################################################
# Há roles que precisam ser atualizados de tempos em tempos.
# Deve-se adicionar aqui os roles que perceberem que necessitam atualizações
# - Atualizar os patrimonio do role firewall_labs.
# - Uma vez por ano tem que atualizar o role do irpf, porém não estamos mais autorizados
# a instalar ele.
