- hosts: biblio:!sj-lin-biblio-g36hqn1.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - ingressa_ldap_sem_cups_client
    - role: instala_impressora_cups
      install: 0
      compras: 1
      cgp: 1
      biblioteca: 1
      financeiro: 1
      secretaria: 1
      reprografia_principal: 1
      pdf: 1
    - role: softwares_remotos
      apps:
        - sophiaslade

- hosts: sj-lin-biblio-g36hqn1.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - ingressa_ldap_sem_cups_client
    - role: instala_impressora_cups
      install: 0
      compras: 1
      cgp: 1
      biblioteca_usb: 1
      financeiro: 1
      secretaria: 1
    - role: softwares_remotos
      apps:
        - sophiaslade

- hosts: sj-lin-biblio-36076.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - ingressa_ldap_sem_cups_client
    - role: instala_impressora_cups
      install: 0
      zebra: 1

- hosts: sj-lin-biblio-cnpq.maquinas.sj.ifsc.edu.br #para o notebook
  roles:
    - configura_wifi

- hosts: sj-lin-pesq-biblio-710805.maquinas.sj.ifsc.edu.br #para o computador da pesquisa
  roles:
    - remove_ldap
    - configura_wifi
    - zerar_home_aluno
  tasks:
    - name: Adiciona linha do usuario aluno no passwd
      blockinfile:
        path: /etc/passwd
        backup: yes
        block: |
          aluno:x:1001:1001::/home/aluno:
      when: ansible_os_family == 'Debian'

    - name: Adiciona linha do usuario aluno no group
      blockinfile:
        path: /etc/group
        backup: yes
        block: |
          aluno:x:1001:
      when: ansible_os_family == 'Debian'

    - name: Cria usuário aluno com a senha aluno
      ansible.builtin.user:
        name: aluno
        shell: /bin/bash
        password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
        groups: aluno
        append: yes
      when: ansible_os_family == 'Debian'


####################### Computador do balcao
- hosts: sje-lin-biblio-28857.maquinas.sj.ifsc.edu.br
  tasks:
    - name: Adiciona linha do usuario biblioteca no passwd
      blockinfile:
        path: /etc/passwd
        backup: yes
        block: |
          biblioteca:x:1001:1001:,,,:/home/biblioteca:/bin/bash
      when: ansible_os_family == 'Debian'

    - name: Adiciona linha do usuario biblioteca no group
      blockinfile:
        path: /etc/group
        backup: yes
        block: |
          biblioteca:x:1001:
      when: ansible_os_family == 'Debian'

    - name: Cria usuário biblioteca com a senha sebib1234
      ansible.builtin.user:
        name: biblioteca
        shell: /bin/bash
        password: $6$LCZb7LjvRCkVnHRI$R8VIp.EhrflQoTTwrtSCfQvtMjo2ONFMDtS6RDmwxTCsBegqerBcyxDoiOmzPhwRpU50hC20FmLGRgUvA1L3z.
        groups: biblioteca
        append: yes
      when: ansible_os_family == 'Debian'
