- hosts: cepe
  #any_errors_fatal: true
  tasks:
  - name: Pacotes especiais
    apt:
      state: latest
      pkg:
      - nautilus-dropbox

- hosts: sj-lin-cepe-38145.maquinas.sj.ifsc.edu.br #silvia
  roles:
    - kernel_backports