---
- hosts: cgp
  #any_errors_fatal: true
  roles:
    - role: softwares_remotos
      apps:
        - pontosecullum
        - ibsispes

- hosts: sj-lin-cgp-613018.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - savpdf
    - token_gd_starsign

- hosts: sj-lin-cgp-35968.maquinas.sj.ifsc.edu.br # Judite
  #any_errors_fatal: true
  roles:
    - token_gd_starsign
    - savpdf
