---
- hosts: cgp
  #any_errors_fatal: true
  roles:
    - role: softwares_remotos
      apps:
        - pontosecullum
        - ibsispes

- hosts: sj-lin-cgp-613018.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - irpf
