---
- hosts: coger
  #any_errors_fatal: true
  roles:
    - qgis
    - role: softwares_remotos
      apps:
        - asctime

- hosts: sje-lin-coger-926469.maquinas.sj.ifsc.edu.br # Notebook acer
  roles:
    - remove_ldap
