- hosts: sj-lin-comaf-37250.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - ingressa_ldap_sem_cups_client
    - savpdf
    - role: instala_impressora_cups
      install: 0
      financeiro: 1
      cgp: 1
      pdf: 1

- hosts: sj-lin-comaf-744525.maquinas.sj.ifsc.edu.br # Michael
  #any_errors_fatal: true
  roles:
    - ingressa_ldap_sem_cups_client
    - savpdf
    - role: instala_impressora_cups
      install: 0
      financeiro: 1
      cgp: 1
      pdf: 1

- hosts: sj-lin-comaf-36867.maquinas.sj.ifsc.edu.br # Hanada
  #any_errors_fatal: true
  roles:
    - token_safenet

- hosts: sj-lin-comaf-744518.maquinas.sj.ifsc.edu.br # Michael
  #any_errors_fatal: true
  roles:
    - token_gd_starsign

- hosts: sj-lin-comaf-37250.maquinas.sj.ifsc.edu.br # Edson
  #any_errors_fatal: true
  roles:
    - token_gd_starsign
    - ingressa_ldap_sem_cups_client
    - savpdf
    - role: instala_impressora_cups
      install: 0
      financeiro: 1
      pdf: 1
