- hosts: sj-lin-comaf-037242.maquinas.sj.ifsc.edu.br # Vanessa
  roles:
    - savpdf
    - role: instala_impressora_cups
      install: 0
      financeiro: 1
      cgp: 1
      pdf: 1

- name: Computador da Elaine
  hosts: sj-lin-comaf-744525.maquinas.sj.ifsc.edu.br
  roles:
    - ingressa_ldap_sem_cups_client
    - java8-oracle
    - token_gd_starsign
    - savpdf
    - role: instala_impressora_cups
      install: 0
      financeiro: 1
      cgp: 1
      pdf: 1

- hosts: sj-lin-comaf-36867.maquinas.sj.ifsc.edu.br
  roles:
    - token_safenet

- hosts: sj-lin-comaf-744518.maquinas.sj.ifsc.edu.br # Hanada
  roles:
    - token_gd_starsign

- hosts: sj-lin-comaf-37250.maquinas.sj.ifsc.edu.br # Edson
  roles:
    - token_safenet
    - ingressa_ldap_sem_cups_client
    - savpdf
    - role: instala_impressora_cups
      install: 0
      financeiro: 1
      pdf: 1

- hosts: sje-lin-financeiro-38109.maquinas.sj.ifsc.edu.br # Joarcir
  roles:
    - token_safenet
    - ingressa_ldap_sem_cups_client
    - savpdf
    - role: instala_impressora_cups
      install: 0
      financeiro: 1
      pdf: 1
