---
  ## Inclusao de roles apenas para LINUX
- hosts: laboratorios_lin
  #any_errors_fatal: true
  roles:
    - sources_list
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones_lab
    - octave
    - cmaptools
    - clion
    - code
    - idea
    - pycharm
    - mplab
    - jetbrains-toolbox
    - java17-oracle
    - wireshark
    - arduino
    - flashplayer
    - kile
    - foxit
    - unattendedUpgrades_labs
    - imunes
    - glpi_agent

  ## Inclusao de roles apenas para WINDOWS
- hosts: laboratorios_win
  #any_errors_fatal: true
  roles:
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones_lab
    - windows_update
    # - bricscad
    # - mmanagal  #Verificar o problema
    # - scratch  #Verificar o problema
    - bipide
    - sr2015
    # - chemdraw_12
    - ltspice
    - tracker
    - foxit
    - arduino
    - flashplayer
    - qgis
    - rstudio
    - geogebra
    - glpi_agent
    # - virtualbox
    # - wireshark
    # - kile
    # - progsisp
