---
  ## Inclusao de roles apenas para LINUX
- hosts: laboratorios_lin
  #any_errors_fatal: true
  roles:
    - sources_list
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones_lab
    # - softwares_sdr #incompativel com debian 11
    - octave
    - cmaptools
    # - android-studio #incompativel com debian 11
    - clion
    - code
    - idea
    - pycharm
    # - eclipse #incompativel com debian 11
    - mplab
    - jetbrains-toolbox
    # - netbeans82 #incompativel com debian 11
    # - netkit2 #incompativel com debian 11
    # - packettracer #incompativel com debian 11
    # - virtualbox
    - wireshark
    - arduino
    - flashplayer
    # - qgis #incompativel com debian 11
    # - rstudio #incompativel com debian 11
    # - geogebra #incompativel com debian 11
    - kile
    - foxit
    - unattendedUpgrades_labs
    - imunes
    # - zoiper
    # - astah
    # - ingles_progs

  ## Inclusao de roles apenas para WINDOWS
- hosts: laboratorios_win
  #any_errors_fatal: true
  roles:
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones_lab
    - windows_update
    # - bricscad
    # - mmanagal  #Verificar o problema
    # - scratch  #Verificar o problema
    - bipide
    # - sr2015  #Verificar o problema
    - chemdraw_12
    - ltspice
    - tracker
    - foxit
    - arduino
    - flashplayer
    - qgis
    - rstudio
    - geogebra
    # - virtualbox
    # - wireshark
    # - kile
    # - progsisp
