---
  ## Inclusao de roles apenas para LINUX
- hosts: laboratorios_lin
  #any_errors_fatal: true
  roles:
    - sources_list
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones_lab
    - octave
    - cmaptools
    - clion
    - code
    - idea
    - pycharm
    - mplab
    - jetbrains-toolbox
    - java17-oracle
    - wireshark
    - arduino
    - flashplayer
    - kile
    - foxit
    - unattendedUpgrades_labs
    - imunes

- hosts: laboratorios_lin
  roles:
  - role: gantsign.visual-studio-code-extensions
    users:
      - username: aluno
        visual_studio_code_extensions:
          - vscjava.vscode-java-pack
          - richardwillis.vscode-gradle-extension-pack
          - vscjava.vscode-lombok
          - ms-azuretools.vscode-docker
          - ms-vscode-remote.remote-containers
          - VisualStudioExptTeam.vscodeintellicode
          - James-Yu.latex-workshop
          - yzhang.markdown-all-in-one
          - bierner.markdown-preview-github-styles
          - ms-python.python
          - ms-python.vscode-pylance
          - jeff-hykin.better-cpp-syntax
          - ms-vscode.cpptools-extension-pack
          - streetsidesoftware.code-spell-checker
          - streetsidesoftware.code-spell-checker-portuguese-brazilian
          - vscode-icons-team.vscode-icons

  ## Inclusao de roles apenas para WINDOWS
- hosts: laboratorios_win
  #any_errors_fatal: true
  roles:
    - programas_padroes_labs
    - config_padrao_labs
    - papel_de_parede_e_icones_lab
    - windows_update
    # - bricscad
    # - mmanagal  #Verificar o problema
    # - scratch  #Verificar o problema
    - bipide
    - sr2015
    # - chemdraw_12
    - ltspice
    - tracker
    - foxit
    - arduino
    - flashplayer
    - qgis
    - rstudio
    - geogebra
    - glpi_agent
    # - virtualbox
    # - wireshark
    # - kile
    # - progsisp
