---
- hosts: ctic
  vars:
    ansible_python_interpreter: /usr/bin/python3
  #any_errors_fatal: true
  gather_facts: true
  roles:
    - code
    - docker
    # - teamviewer
    # - virtualbox
    # - rambox
    # - ingressa_ldap
    # - rke
  tasks:
  # - name: Instalar os pacotes para o Ansible #do buster-backports - Linux Debian
  #   apt: name=ansible state=latest #default_release=buster-backports
  - name: Pacotes padroes da CTIC
    apt:
      state: latest
      pkg:
      - ipcalc
      - ansible
      - keepassx
      - git
      - gparted
      - vinagre
      - tcpdump
      - dnsutils
      - python3-pip
      # - python-pip # Ruim no bullseye
  - pip:
      name:
        - pywinrm
        - paramiko
        - cryptography # ==2.4.2 #Não eh mais necessario essa versao
      executable: pip3
  - name: Adiciona no grupo docker
    user:
      name: "{{item}}"
      groups: docker
      append: yes
    with_items:
      - rmartins
      - humbertos
      - gabriel.souza
      - marcelo.alejandro
      - etorresini
    when: ansible_os_family == 'Debian'

##################  Maquina do 1berto  ##################
- hosts: sj-lin-ctic-37247.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - ingressa_ldap_gdm

##################  Maquina do RICARDO  ##################
- hosts: sj-lin-ctic-744521.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - kubernetes
    - ingressa_ldap_gdm
    # - softwares_remotos # ruim no buster
    - role: geerlingguy.nfs
      nfs_exports: [ "/dados *(rw,sync,no_root_squash)" ]
    # - role: bertvv.samba
    #   samba_shares:
    #     - name: ctic
    #       comment: 'O local mais seguro de todos'
    #       path: /dados
    #       browseable: yes
    #       create_mode: '777'
    #       directory_mode: '777'
    #       valid_users: '%S'
    #       writable: yes
    #       read_only: no
    #       guest_ok: yes
    #   samba_users:
    #     - name: USERNAME
    #       password: PASSWORD
  tasks:
  - name: Pacotes do Ricardo
    apt:
      state: latest
      pkg:
      - k3b
      - keychain
      - dcfldd
      - lm-sensors
      # - nautilus-dropbox # ruim no buster
      - unzip
      - vlan
      - python3-tk
      - python3-setuptools
      - gir1.2-appindicator3-0.1
      # - python-appindicator # ruim no buster
      - vinagre
      - virtualenv
      - konsole
      - nfs-common
      - curl
      - ethtool
      - samba
      - usbutils
      - sshfs
      - net-tools
##########################################################
