- hosts: depe
  #any_errors_fatal: true
  roles:
    - foxit
    - role: softwares_remotos
      apps:
        - asctime
        - isaacdesktop
        - sisaca

- hosts: sj-lin-depe-BRG311F6PN.maquinas.sj.ifsc.edu.br
  roles:
    - role: grub
      tipo: grub_lin
