# - hosts: des2
#   #any_errors_fatal: true
#   roles:
#     - packettracer
#     - kile
#     - programas_padroes_labs

# - hosts: des2
#   #any_errors_fatal: true
#   roles:
#     - role: grub
#       tipo: grub_lin

- hosts: sj-lin-des2-744927.maquinas.sj.ifsc.edu.br,sj-lin-des2-744928.maquinas.sj.ifsc.edu.br #Diego e Deise
  #any_errors_fatal: true
  roles:
    - ingressa_ldap_gdm
  tasks:
  - name: Pacotes do Diego
    apt:
      state: latest
      pkg:
      - nautilus-dropbox
  # Comentado pois apos instalar ele cria um repositorio e mantem atualizado.
  # - name: Install a .deb Mendeley Desktop - Linux Debian
  #   apt:
  #     deb: https://www.mendeley.com/repositories/ubuntu/stable/amd64/mendeleydesktop-latest
    when: ansible_os_family == 'Debian'
