---
- hosts: sj-lin-dire-38850.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - token_safenet

- hosts: sj-lin-dire-38853.maquinas.sj.ifsc.edu.br
  tasks:
  - name: Pacotes para os pcs da direcao #Solicitado pelo chamado IFSC#2022041810000801
    apt:
      state: latest
      pkg:
      - python3-pip
      - texlive-xetex # equivalente para debian ao solicitado, xelatex
