# Windows

- name: Máquina do professor Romulo
  hosts: sj-gerac-725865.maquinas.sj.ifsc.edu.br
  roles:
    - ingressa_ldap
  tasks:
    - name: Instala o Home assistance
      chocolatey.chocolatey.win_chocolatey:
        name: homeassistant
    - name: Instala o Virtualbox
      chocolatey.chocolatey.win_chocolatey:
        name: virtualbox
