- name: Computadores do laboratório
  hosts: cad1_lin
  roles:
    - role: grub
      tipo: grub_win

- name: Computadores dos alunos
  hosts: cad1_lin:!sj-lin-cad1-916082.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_client

- name: Computador do professor Linux
  hosts: sj-lin-cad1-916082.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_server
    - ingressa_ldap
    - scrcpy

# Windows

- name: Máquina do professor Windows
  hosts: sj-cad1-916082.maquinas.sj.ifsc.edu.br
  roles:
    - ingressa_ldap
