- name: Computador do professor
  hosts: sje-lin-csfio-744536.maquinas.sj.ifsc.edu.br,sj-csfio-744536.maquinas.sj.ifsc.edu.br
  roles:
    - ingressa_ldap

- name: Notebooks dos alunos
  hosts: csfio_lin,!sje-lin-csfio-744536.maquinas.sj.ifsc.edu.br,!sj-csfio-744536.maquinas.sj.ifsc.edu.br
  roles:
    - role: grub
      tipo: grub_lin

  tasks:
    - name: Cria diretório
      ansible.builtin.file:
        state: directory
        path: /opt/backup
        owner: root
        group: root
        mode: '0755'
      when: ansible_os_family == 'Debian'

    - name: Cria link simbólico para aluno.tgz
      ansible.builtin.file:
        state: link
        src: /home/aluno.tar.gz
        dest: /opt/backup/aluno.tgz
        owner: root
        group: root
        mode: '0755'
      when: ansible_os_family == 'Debian'

    - name: Apaga aluno alternativo
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          #Restaurar o usuario aluno quando manda desligar a maquina ou reiniciar.
          rm -rf /var/spool/cron/crontabs/aluno
          rm -rf /home/aluno
          tar -zxvf /opt/backup/aluno.tgz -C /home/ --exclude=home/aluno/.ssh/known_hosts
        dest: /etc/init.d/apagaAluno.sh
        owner: root
        group: root
        mode: '0755'
      when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Computador com Windows
  hosts: csfio_win
  roles:
    - nec
    - linkplanner
