- name: Computadores do laboratório
  hosts: cad2_lin
  roles:
    - role: grub
      tipo: grub_win
  # tasks:
  #   - name: Monta /media/aluno/trabalhos fstab - Linux
  #     ansible.posix.mount:
  #       path: /media/aluno/trabalhos
  #       src: "UUID=872E-9221"
  #       fstype: vfat
  #       opts: uid=aluno,gid=aluno
  #       state: present
  #     when: ansible_os_family == 'Debian'

- name: Computadores dos alunos
  hosts: cad2_lin:!sje-lin-cad2-905476.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_client

- name: Computador professor Linux
  hosts: sje-lin-cad2-905476.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_server
    - ingressa_ldap
    - scrcpy

# Windows
- name: Computador professor Windows
  hosts: sj-cad2-905476.maquinas.sj.ifsc.edu.br
  roles:
    - ingressa_ldap
