- name: Computadores do laboratório
  hosts: cad3_lin
  roles:
    - role: grub
      tipo: grub_win
  # tasks:
  # - name: Monta /media/aluno/trabalhos fstab - Linux
  #   mount:
  #     path: /media/aluno/trabalhos
  #     src: "UUID=872E-9221"
  #     fstype: vfat
  #     opts: uid=aluno,gid=aluno
  #     state: present
  #   when: ansible_os_family == 'Debian'

- name: Computador dos alunos
  hosts: cad3_lin:!sje-lin-cad3-744517.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_client

- name: Computador professor Linux
  hosts: sje-lin-cad3-744517.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_server
    - ingressa_ldap
    - curso_lic_leone
    - scrcpy

# Windows
- name: Computador professor Windows
  hosts: sj-cad3-744517.maquinas.sj.ifsc.edu.br
  roles:
    - ingressa_ldap
