#Linux

- hosts: cad2_lin
  #any_errors_fatal: true
  roles:
    - kernel_backports
    - role: grub
      tipo: grub_win
  tasks:
  - name: Monta /dev/sda5 em /media/aluno/trabalhos fstab - Linux
    mount:
      path: /media/aluno/trabalhos
      src: /dev/sda5
      fstype: vfat
      opts: uid=aluno,gid=aluno
      state: present
    when: ansible_os_family == 'Debian'

- hosts: cad2_lin:!sj-lin-cad2-905476.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - epoptes_client

- hosts: sj-lin-cad2-905476.maquinas.sj.ifsc.edu.br #Maquina do professor
  #any_errors_fatal: true
  roles:
    - epoptes_server
    - ingressa_ldap
    # - owncloud_client

# Windows

- hosts: sj-cad2-905476.maquinas.sj.ifsc.edu.br #Maquina do professor
  #any_errors_fatal: true
  roles:
    - ingressa_ldap
