- hosts: info_lin
  any_errors_fatal: true
  roles:
    - sources_list
    - google_earth
    - tracker
    # - kernel_backports
    - scidavis
    - role: grub
      tipo: grub_soh_lin
  tasks:
  - name: Cria o arquivo tcp_rmem # chamado IFSC#2023050410000449
    ansible.builtin.copy:
      content: |
        10000 10000 10000
      dest: /proc/sys/net/ipv4/tcp_rmem
      owner: root
      group: root
      mode: 0644
      unsafe_writes: true
    when: ansible_os_family == 'Debian'

  - name: Instala tiled via SNAP
    community.general.snap:
      name:
        - tiled
    when: ansible_os_family == 'Debian'
    tags: tiled

- hosts: info_lin:!sje-lin-info-895203.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - epoptes_client

- hosts: sje-lin-info-895203.maquinas.sj.ifsc.edu.br #Maquina do professor
  #any_errors_fatal: true
  roles:
    - epoptes_server
    - ingressa_ldap
    - configura_monitores
    # - owncloud_client

# Windows

- hosts: sje-info-895203.maquinas.sj.ifsc.edu.br #Maquina do professor
  #any_errors_fatal: true
  roles:
    - ingressa_ldap
