- name: Computadores do laboratório de informática
  hosts: info_lin
  roles:
    - sources_list
    - google_earth
    - tracker
    - scidavis
    - role: grub
      tipo: grub_soh_lin
  tasks:
    - name: Cria o arquivo tcp_rmem chamado IFSC#2023050410000449
      ansible.builtin.copy:
        content: |
          10000 10000 10000
        dest: /proc/sys/net/ipv4/tcp_rmem
        owner: root
        group: root
        mode: '0644'
        unsafe_writes: true
      when: ansible_os_family == 'Debian'

    - name: Instala tiled via SNAP
      community.general.snap:
        name:
          - tiled
      when: ansible_os_family == 'Debian'
      tags: tiled

- name: Computadores dos alunos
  hosts: info_lin:!sje-lin-info-895203.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_client

- name: Configurações do computador do professor
  hosts: sje-lin-info-895203.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_server
    - ingressa_ldap
    - configura_monitores
    - scrcpy

# Windows

- name: Configuração máquina do professor no Windows.
  hosts: sje-info-895203.maquinas.sj.ifsc.edu.br
  roles:
    - ingressa_ldap
