# Linux

# Chamado da aluna Jeneffer Farias Bora IFSC#2019042510000446
- hosts: labic
  any_errors_fatal: true
  tasks:
  - name: Instala pacotes labic
    apt:
      state: latest
      pkg:
      - idle3
      - python-flask
      - python3-flask
    when: ansible_os_family == 'Debian'

  # Permissao para gravar na placa
  - name: Adiciona a jeneffer no grupo dialout
    user:
      name: "{{ user_labic }}"
      groups: dialout
      append: yes
    loop:
      - jeneffer
    loop_control:
      loop_var: user_labic
    when: ansible_os_family == 'Debian'
