- hosts: sj-lin-meios-744520.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - ingressa_ldap_sem_cups_client
    - configura_monitores
    - role: grub
      tipo: grub_soh_lin
    - role: instala_impressora_cups
      install: 0
      brother: 1

- hosts: meios_lin
  #any_errors_fatal: true
  roles:
    - role: grub
      tipo: grub_lin
