- hosts: labmeios
  #any_errors_fatal: true
  roles:
    - ingressa_ldap_sem_cups_client
    - configura_monitores
    - role: grub
      tipo: grub_soh_lin
    - role: instala_impressora_cups
      install: 0
      brother: 1
