- name: Computadores do laboratório
  hosts: programacao_lin
  roles:
    - role: grub
      tipo: grub_lin

- name: Computadores HP
  hosts: sj-lin-prog-866459.maquinas.sj.ifsc.edu.br, sje-lin-prog-866460.maquinas.sj.ifsc.edu.br, sje-lin-prog-866461.maquinas.sj.ifsc.edu.br, sj-lin-prog-866462.maquinas.sj.ifsc.edu.br, sj-lin-prog-866463.maquinas.sj.ifsc.edu.br, sj-lin-prog-866464.maquinas.sj.ifsc.edu.br, sj-lin-prog-866465.maquinas.sj.ifsc.edu.br, sj-lin-prog-866466.maquinas.sj.ifsc.edu.br
  tasks:
    - name: Modulo video AMD - Linux
      ansible.builtin.apt:
        pkg:
          - firmware-amd-graphics
          - firmware-linux-nonfree
          - linux-image-6.5.0-0.deb12.4-amd64
          - linux-headers-6.5.0-0.deb12.4-amd64
      tags: firmware-amd

- name: Computadores dos alunos
  hosts: programacao_lin:!sj-lin-prog-744523.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_client

- name: Computador do professor Linux
  hosts: sj-lin-prog-744523.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_server
    - ingressa_ldap
    - configura_monitores
    - scrcpy

# Windows
- name: Computador do professor Windows
  hosts: sj-prog-744523.maquinas.sj.ifsc.edu.br:imgwin10-lab.maquinas.sj.ifsc.edu.br
  roles:
    - ingressa_ldap
    - nec
    - linkplanner
