- name: Computadores do laboratório
  hosts: programacao_lin
  roles:
    - role: grub
      tipo: grub_lin

- name: Computadores dos alunos
  hosts: programacao_lin:!sj-lin-prog-744523.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_client

- name: Computador do professor Linux
  hosts: sj-lin-prog-744523.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_server
    - ingressa_ldap
    - configura_monitores
    - scrcpy

# Windows
- name: Computador do professor Windows
  hosts: sj-prog-744523.maquinas.sj.ifsc.edu.br:imgwin10-lab.maquinas.sj.ifsc.edu.br
  roles:
    - ingressa_ldap
    - nec
    - linkplanner
