- name: Computadores dos labratórios
  hosts: redes_lin
  roles:
    - role: grub
      tipo: grub_lin

- name: Computadores dos alunos
  hosts: redes_lin:!sje-lin-redes-906284.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_client

- name: Computador professor Linux
  hosts: sje-lin-redes-906284.maquinas.sj.ifsc.edu.br
  roles:
    - epoptes_server
    - ingressa_ldap
    - configura_monitores
    - scrcpy

# Windows

- name: Computador professor Windows
  hosts: sj-redes-906284.maquinas.sj.ifsc.edu.br
  roles:
    - ingressa_ldap
