# Linux
- hosts: sidi_lin
  #any_errors_fatal: true
  roles:
    - pinta
    - role: grub
      tipo: grub_lin
  tasks:
  - name: Monta /media/aluno/trabalhos fstab - Linux
    mount:
      path: /media/aluno/trabalhos
      src: "UUID=872E-9221"
      fstype: vfat
      state: present
    when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

  - name: Monta HD correto em /media/aluno/trabalhos fstab - Linux
    mount:
      path: /media/aluno/trabalhos
      src: UUID=872E-9221
      fstype: vfat
      state: present
    when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- hosts: sidi_lin:!sj-lin-sidi-25.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - epoptes_client

- hosts: sj-lin-sidi-25.maquinas.sj.ifsc.edu.br #Maquina do professor
  #any_errors_fatal: true
  roles:
    - epoptes_server
    - ingressa_ldap
    - configura_monitores
    # - owncloud_client
  tasks:
  - name: Pacotes do Lab SiDi
    apt:
      state: latest
      pkg:
      - arandr


# Windows

- hosts: sj-sidi-25.maquinas.sj.ifsc.edu.br #Maquina do professor
  #any_errors_fatal: true
  roles:
    - ingressa_ldap
