---
- name: Computadores do Laboratório de Ensino à distância. - #LINUX
  hosts: ledis
  roles:
    - ingressa_ldap
    - role: grub
      tipo: grub_win

- name: Computadores do Laboratório de Ensino à distância. #WINDOWS
  hosts: ledis_win
  roles:
    - ingressa_ldap
