- hosts: sj-lin-manut-866467.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - role: grub
      tipo: grub_win

- hosts: manut_win
  tasks:
  - name: Instalar o TS print - Windows # Pacote necessário para imprimir relatórios no Volare
    chocolatey.chocolatey.win_chocolatey:
      name: tsprintclient
      state: present
    when: ansible_os_family == 'Windows'
