- name: Administrativo Linux -salas
  hosts: administrativos_lin,!sala,!note
  roles:
    - ingressa_ldap
    - acesso_remoto
    - cadeia_certificados
    - token_gd_starsign
    - token_safenet
    - hodprint

- name: Administrativo Linux
  hosts: administrativos_lin,sje-lin-gremio-38857.maquinas.sj.ifsc.edu.br

#############################################################
##################### INCLUSÃO DE ROLES #####################
  roles:
    - sources_list
    - fonte_garamound
    - unattendedUpgrades_adm
    - glpi_agent
    - auto_desligamento
    - warsaw
    - foxit
    # - java8-oracle
    - flatpak
    - google_chrome
    - role: grub
      tipo: grub_soh_lin

  tasks:
    - name: Upgrade the packages (apt full-upgrade)
      ansible.builtin.apt:
        upgrade: full
      when: ansible_os_family == 'Debian'

    - name: Run the equivalent of "apt-get clean" as a separate step
      ansible.builtin.apt:
        clean: true
      when: ansible_os_family == 'Debian'

    - name: Instala pacotes básicos - Linux
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - apt-transport-https
          - aptitude
          - bash-completion
          - chrony
          - command-not-found
          - dia
          - dkms
          - firmware-linux-free
          - firmware-linux-nonfree
          - gnome-terminal
          - gscan2pdf
          - gtklp
          - kdenlive
          - kolourpaint
          - libcurl4
          - linux-image-amd64
          - linux-headers-amd64
          - lldpd
          - network-manager
          - network-manager-gnome
          - nfs-common
          - okular
          - pdfarranger
          - ssh
          - system-config-printer
          - unrar-free
          - vim
          - vlc
      when: ansible_os_family == 'Debian'

    - name: Instala qpdf tools - Compressão de PDF
      community.general.flatpak:
        name:
          - br.eng.silas.qpdftools
      when: ansible_os_family == 'Debian'
      tags: qpdf

    - name: Remover programas  - Linux
      ansible.builtin.apt:
        state: absent
        pkg:
          - transmission
          - transmission-common
          - linux-image-6.5.0-0.deb12.4-amd64
          - linux-headers-6.5.0-0.deb12.4-amd64
          - linux-headers-6.5.0-0.deb12.4-common
      when: ansible_os_family == 'Debian'
      tags: remove

#########################################################
##################### CONFIGURAÇÕES #####################

    - name: Adiciona conteúdo do /etc/bash.bashrc
      ansible.builtin.blockinfile:
        path: /etc/bash.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        content: |
          # enable bash completion in interactive shells
          if ! shopt -oq posix; then
            if [ -f /usr/share/bash-completion/bash_completion ]; then
              . /usr/share/bash-completion/bash_completion
            elif [ -f /etc/bash_completion ]; then
              . /etc/bash_completion
            fi
          fi
          export SHELL=/bin/bash
          export PATH=$PATH:/sbin
        backup: true
      when: ansible_os_family == 'Debian'
      tags: bashrc

##########################################################
################ CONFIGURAÇÕES INDIVIUAIS ################
- name: Configuração salas de aula, se der problema comentar o scrcpy # e depois descomentar de novo
  hosts: sala
  roles:
    - configura_monitores
    - remove_ldap
    - geogebra
    - aluno
    - scrcpy
    - wine
  tasks:
    - name: Pacotes especiais
      ansible.builtin.apt:
        pkg:
          - x2goclient
          - wxmaxima
          - python3-matplotlib
          - python3-numpy
          - python3-scipy
          - python3-pandas
          - python3-pip
          - snapd
      tags: pacotes

- name: Configuração dos notebooks da turno
  hosts: note
  roles:
    - aluno

- name: Computadores Financeiro
  hosts: financeiro
  roles:
    - savpdf
    - role: instala_impressora_cups
      install: 0
      financeiro: 1
      cgp: 1

- name: Computadores meios de RAC
  hosts: mrac_lin
  roles:
    - role: grub
      tipo: grub_win

- name: Notebook acer
  hosts: sje-lin-dae-926476.maquinas.sj.ifsc.edu.br
  roles:
    - remove_ldap

- name: Computadores da biblioteca
  hosts: biblio
  roles:
    - role: softwares_remotos
      apps:
        - sophiaslade

- name: Computadores da secretaria
  hosts: secret
  roles:
    - role: softwares_remotos
      apps:
        - isaacdesktop

- name: Adiciona software scanner Epson Almoxarifado - Everson
  hosts: sje-lin-almox-756044.maquinas.sj.ifsc.edu.br
  roles:
    - scanner

- name: Adiciona impressora local Almoxarifado - Eduardo
  hosts: sje-lin-almox-933436.maquinas.sj.ifsc.edu.br
  roles:
    - savpdf
    - role: instala_impressora_cups
      install: 0
      reprografia_reserva: 1
      reprografia_principal: 1
      almoxarifado_3920: 1
      pdf: 1

- name: Programas do Jorge Casagrande
  hosts: sje-lin-des2-703872.maquinas.sj.ifsc.edu.br
  roles:
    - code

- name: Programas para o Marcelo do contratos
  hosts: sje-lin-contra-38845.maquinas.sj.ifsc.edu.br
  roles:
    - zoom
