- name: Administrativo Linux -salas
  hosts: administrativos_lin,!sala,!note
  roles:
    - ingressa_ldap
    - acesso_remoto
    - cadeia_certificados
    - token_gd_starsign
    - token_safenet
    - hodprint

- name: Administrativo Linux
  hosts: administrativos_lin

#############################################################
##################### INCLUSÃO DE ROLES #####################
  roles:
    - upgrade_11to12
    - sources_list
    - openaudit
    - fonte_garamound
    - unattendedUpgrades_adm
    - glpi_agent
    - auto_desligamento
    - warsaw
    - foxit
    - java8-oracle
    # - role: grub
    #   tipo: grub_soh_lin

  tasks:
    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.apt_key:
        id: 4EB27DB2A3B88B8B
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        keyring: /etc/apt/trusted.gpg.d/google-chrome.gpg
      when: ansible_os_family == 'Debian'

    - name: Instala utilitários para o bash
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - aptitude
          - bash-completion
          - chrony
          - command-not-found
          - dia
          - dkms
          - firmware-linux-free
          - firmware-linux-nonfree
          - gnome-terminal
          - gscan2pdf
          - gtklp
          - icedtea-netx
          - kdenlive
          - kolourpaint4
          - libcurl4
          - linux-image-amd64
          - linux-headers-amd64
          - network-manager
          - network-manager-gnome
          - nfs-common
          - okular
          - pdfshuffler
          - ssh
          - system-config-printer
          - unrar
          - vim
          - vlc
      when: ansible_os_family == 'Debian'

    - name: Instala pacotes .deb
      ansible.builtin.apt:
        deb: "{{ deb_pkgs }}"
      loop:
        - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      loop_control:
        loop_var: deb_pkgs
      when: ansible_os_family == 'Debian'

    - name: Remover programas  - Linux
      ansible.builtin.apt:
        state: absent
        pkg:
          - transmission
          - transmission-common
          - linux-image-6.5.0-0.deb12.4-amd64
          - linux-headers-6.5.0-0.deb12.4-amd64
          - linux-headers-6.5.0-0.deb12.4-common
      when: ansible_os_family == 'Debian'
      tags: remove

#########################################################
##################### CONFIGURAÇÕES #####################
    - name: Inclui o role do NTP do Linux
      ansible.builtin.include_role:
        name: geerlingguy.ntp
      vars:
        ntp_timezone: America/Sao_Paulo
        ntp_manage_config: true
        ntp_servers:
          - "pool.ntp.br iburst"
          - "ntp.cais.rnp.br iburst"
          - "ntp.ufsc.br iburst"
      when: ansible_os_family == 'Debian'

    - name: Adiciona conteúdo do /etc/bash.bashrc
      ansible.builtin.blockinfile:
        path: /etc/bash.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        content: |
          # enable bash completion in interactive shells
          if ! shopt -oq posix; then
            if [ -f /usr/share/bash-completion/bash_completion ]; then
              . /usr/share/bash-completion/bash_completion
            elif [ -f /etc/bash_completion ]; then
              . /etc/bash_completion
            fi
          fi
          export SHELL=/bin/bash
          export PATH=$PATH:/sbin
        backup: true
      when: ansible_os_family == 'Debian'
      tags: bashrc

##########################################################
################ CONFIGURAÇÕES INDIVIUAIS ################
- name: Configuração salas de aula, se der problema comentar o scrcpy # e depois descomentar de novo
  hosts: sala
  roles:
    - configura_monitores
    - remove_ldap
    - flatpak
    - geogebra
    - aluno
    - scrcpy
  tasks:
    - name: Pacotes especiais
      ansible.builtin.apt:
        pkg:
          - x2goclient
          - wxmaxima
          - python3-matplotlib
          - python3-numpy
          - python3-scipy
          - python3-pandas
          - python3-pip
          - snapd
      tags: pacotes

- name: Configuração dos notebooks da turno
  hosts: note
  roles:
    - configura_wifi
    - aluno

- name: Computadores Financeiro
  hosts: financeiro
  roles:
    - savpdf
    - role: instala_impressora_cups
      install: 0
      financeiro: 1
      cgp: 1
