- name: Administrativo Linux
  hosts: administrativos_lin

#############################################################
##################### INCLUSÃO DE ROLES #####################
  roles:
    - upgrade_11to12
    - ingressa_ldap
    - sources_list
    - openaudit
    - acesso_remoto
    - fonte_garamound
    - unattendedUpgrades_adm
    - glpi_agent
    - auto_desligamento
    - warsaw
    - foxit
    - cadeia_certificados
    - java8-oracle
    - token_gd_starsign
    - token_safenet
    - role: grub
      tipo: grub_soh_lin

  tasks:
    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.apt_key:
        id: 4EB27DB2A3B88B8B
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        keyring: /etc/apt/trusted.gpg.d/google-chrome.gpg
      when: ansible_os_family == 'Debian'

    - name: Instala utilitários para o bash
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - aptitude
          - bash-completion
          - chrony
          - command-not-found
          - dia
          - dkms
          - firmware-linux-free
          - firmware-linux-nonfree
          - gnome-terminal
          - gscan2pdf
          - gtklp
          - icedtea-netx
          - kdenlive
          - kolourpaint4
          - libcurl4
          - network-manager
          - network-manager-gnome
          - nfs-common
          - okular
          - pdfshuffler
          - ssh
          - system-config-printer
          - unrar
          - vim
          - vlc
      when: ansible_os_family == 'Debian'

    - name: Instala pacotes .deb
      ansible.builtin.apt:
        deb: "{{ deb_pkgs }}"
      loop:
        - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      loop_control:
        loop_var: deb_pkgs
      when: ansible_os_family == 'Debian'

    - name: Remover programas  - Linux
      ansible.builtin.apt:
        state: absent
        pkg:
          - transmission
          - transmission-common
      when: ansible_os_family == 'Debian'

#########################################################
##################### CONFIGURAÇÕES #####################
    - name: Inclui o role do NTP do Linux
      ansible.builtin.include_role:
        name: geerlingguy.ntp
      vars:
        ntp_timezone: America/Sao_Paulo
        ntp_manage_config: true
        ntp_servers:
          - "pool.ntp.br iburst"
          - "ntp.cais.rnp.br iburst"
          - "ntp.ufsc.br iburst"
      when: ansible_os_family == 'Debian'

    - name: Define conteúdo do /etc/bash.bashrc
      ansible.builtin.copy:
        content: |
          # System-wide .bashrc file for interactive bash(1) shells.
          # To enable the settings / commands in this file for login shells as well,
          # this file has to be sourced in /etc/profile.
          # If not running interactively, don't do anything
          [ -z "$PS1" ] && return

          # check the window size after each command and, if necessary,
          # update the values of LINES and COLUMNS.
          shopt -s checkwinsize

          # set variable identifying the chroot you work in (used in the prompt below)
          if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
              debian_chroot=$(cat /etc/debian_chroot)
          fi

          # set a fancy prompt (non-color, overwrite the one in /etc/profile)
          # but only if not SUDOing and have SUDO_PS1 set; then assume smart user.
          if ! [ -n "${SUDO_USER}" -a -n "${SUDO_PS1}" ]; then
            PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
          fi

          # enable bash completion in interactive shells
          if ! shopt -oq posix; then
            if [ -f /usr/share/bash-completion/bash_completion ]; then
              . /usr/share/bash-completion/bash_completion
            elif [ -f /etc/bash_completion ]; then
              . /etc/bash_completion
            fi
          fi

          # if the command-not-found package is installed, use it
          if [ -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ]; then
            function command_not_found_handle {
                    # check because c-n-f could've been removed in the meantime
                          if [ -x /usr/lib/command-not-found ]; then
                /usr/lib/command-not-found -- "$1"
                            return $?
                          elif [ -x /usr/share/command-not-found/command-not-found ]; then
                /usr/share/command-not-found/command-not-found -- "$1"
                            return $?
              else
                printf "%s: command not found\n" "$1" >&2
                return 127
              fi
            }
          fi
          export SHELL=/bin/bash
          export PATH=$PATH:/sbin
        dest: /etc/bash.bashrc
        owner: root
        group: root
        mode: '0644'
        backup: true
      when: ansible_os_family == 'Debian'
      tags: bashrc

    - name: Copia hodprint - Linux
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          gtklp $1
          rm -f $1
        dest: /usr/bin/hodprint
        owner: root
        group: root
        mode: '0755'
      when: ansible_os_family == 'Debian'
    ##################### Fim impressao hodprint

    ##################### Arquivos de configuração do HOD

    - name: Cria diretório /home/hodfiles
      ansible.builtin.file:
        path: /home/hodfiles
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: ansible_os_family == 'Debian'

    - name: Copia arquivos de configuração do HOD - cfg0.df
      ansible.builtin.copy:
        content: |
          [HostPrintTerminal]
          SSLCertificateHash=

          [Icon]
          frameXpos=0
          frameWidth=968
          frameHeight=992
          isMaximized=true
          uid=HOD358072
          isIconified=false
          frameYpos=0

          [Terminal]
          disableKeyBuffer=false
          PrtScrnJavaMode=false

          [KeyRemap]
          disableKeyBuffer=false

          [ZipPrint]
          usePDT=true
          printFileName=/tmp/hodprint.* | hodprint $<
          termTime=0
          RTLFile=false
          printerLUType=2
          suppressAutoNewlineNL=false
          viewJobInBrowser=false
          formFeedPosition=true
          useAdobePDF=true
          pdfPaperSize=6
          PrintCMSFile=false
          useWindowsPrinter=false
          intervTime=10
          inheritParms=false
          FFTakesPrintPos=true
          maxLinesPerPage=48
          useWindowsDefaultPrinter=true
          printerName=/dev/lp0
          tractor=false
          numOfScreens=2
          charsPerInch=12
          windowsPrinterName=
          pdfPaperOrientation=0
          drawFieldAttr=0
          printerFontCodePage=0
          suppressNullLines=false
          NumericSwap=true
          SymmetricSwap=true
          suppressAutoNewlineCR=false
          PDTFile=/pdfpdt/LaserPCL.hodpdt
          useMultiPrintPerPage=false
          AppProfiles=OVNote\t1\t33\tVIEW THE NOTE\t2\t2\tFrom:\t-1\t31\tE N D  O F  N O T E\t5\t1\t20\t-1\t3\t1\t20\t-1\tPF10\tPF11\ttrue\rISPF\t3\t2\tEDIT\t5\t2\t****** ***************************** Top of Data ******************************\t-1\t2\t****** **************************** Bottom of Data ****************************\t6\t2\t24\t-1\t5\t2\t24\t-1\tPF8\tPF7\ttrue
          concatTime=0
          pdfFont=Courier
          printNullsAsSpaces=true
          printDestination=false
          ignoreFFFirstPos=false
          linesPerInch=6
          PrintCustomProfile=false
          bestFit=false
          separateFiles=false
          SCSSense=true
          codePage=037
          skipTRNData=false
          ignoreAttr=false
          maxCharsPerLine=80
        dest: /home/hodfiles/cfg0.df
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == 'Debian'

    - name: Copia arquivos de configuração do HOD - cfg1.df
      ansible.builtin.copy:
        content: |
          [HostPrintTerminal]
          useAdobePDF=true
          printDestination=false
          useWindowsPrinter=false
          linesPerInch=8
          sessionID=B
          charsPerInch=17
          printFileName=/tmp/hodprint.* | hodprint $<

          [Icon]
          frameXpos=745
          frameWidth=420
          frameHeight=422
          uid=HOD611605
          frameYpos=304
        dest: /home/hodfiles/cfg1.df
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == 'Debian'

    - name: Copia arquivos de configuração do HOD - cfg2.df
      ansible.builtin.copy:
        content: |
          [HostPrintTerminal]
          useAdobePDF=true
          printDestination=false
          useWindowsPrinter=false
          linesPerInch=8
          sessionID=B
          charsPerInch=17
          printFileName=/tmp/hodprint.* | hodprint $<

          [Icon]
          frameXpos=745
          frameWidth=420
          frameHeight=422
          uid=HOD413191
          frameYpos=304
        dest: /home/hodfiles/cfg2.df
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == 'Debian'

    - name: Copia arquivos de configuração do HOD - cfg3.df
      ansible.builtin.copy:
        content: |
          [HostPrintTerminal]
          useAdobePDF=true
          printDestination=false
          useWindowsPrinter=false
          linesPerInch=8
          sessionID=B
          charsPerInch=17
          printFileName=/tmp/hodprint.* | hodprint $<

          [Icon]
          uid=HOD772531
          isIconified=false
        dest: /home/hodfiles/cfg3.df
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == 'Debian'

    - name: Cria o Leiame.txt
      ansible.builtin.copy:
        content: |
          # Nesta pasta tem os arquivos de configuraçao do HOD com a Console configurado
          e com a impressora de 132 colunas configurada para usar o hodprint
          # Instalação
          Basta copiar os arquvos de configuração (*.df) para a pasta /home/{USER}/HODData/hodcivws/
        dest: /home/hodfiles/Leiame.txt
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == 'Debian'
