- name: Laboratórios Windows
  hosts: laboratorios_win
  roles:
    # - coolselector2 ## Não aceita instalação silenciosa, apesar de constar na documentação
    - energyplus
    - geogebra
    - glpi_agent
    - microsip
    - papel_de_parede_e_icones
    - revit
    - zoiper
  tasks:
    - name: Ativa servidor NTP para o Windows
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\Microsoft\CurrentControlSet\Services\W32Time\Parameters
        name: "Type"
        data: NTP
      tags: w32
      when: ansible_os_family == 'Windows'

    - name: Ativa atualização automática servidor NTP para o Windows
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\tzautoupdate
        name: Start
        data: "3"
        type: dword
      tags: w32
      when: ansible_os_family == 'Windows'

    - name: Configura servidor NTP para o Windows
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\ControlSet001\Services\W32Time\Parameters
        name: NtpServer
        data: a.st1.ntp.br
      tags: w32
      when: ansible_os_family == 'Windows'

    - name: Configuracao para UTC
      ansible.windows.win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\TimeZoneInformation
        name: RealTimeIsUniversal
        data: "1"
        type: dword
      when: ansible_os_family == 'Windows'
      tags: config_hora

    - name: Set timezime to Pacific Standard time and disable Daylight Saving time adjustments
      community.windows.win_timezone:
        timezone: E. South America Standard Time_dstoff
      when: ansible_os_family == 'Windows'
      tags: config_hora

    - name: Install multiple packages sequentially
      chocolatey.chocolatey.win_chocolatey:
        name:
          - chocolatey
          - dotnet
          - googlechrome
          - firefox
          - libreoffice
          - vlc
          - 7zip
          - glpi-agent
      when: ansible_os_family == 'Windows'

- name: Configurações aplicadas somente para as maquinas dos professores
  hosts: lab_profs_win,meios_cult_win
  roles:
    - ingressa_ldap

# - name: Atualizar computadores Windows do grupo laboratorios_win
#   hosts: laboratorios_win
#   tasks:
#     - name: Verificar e instalar atualizações do Windows Update
#       ansible.windows.win_updates:
#         category_names:
#           - CriticalUpdates
#           - SecurityUpdates
#         reboot: true


######################## ORDEM ALFABÉTICA ########################
- name: Laboratório de Comunicação sem fio
  hosts: csfio_win
  roles:
    - hfss
