- name: Laboratórios Linux
  hosts: laboratorios_lin

  roles:
    - aluno
    - arduino
    - auto_desligamento
    - chaves_ssh
    - dconf
    - docker
    - flatpak
    - gnome-calculator
    - gradle_8.10
    - google_chrome
    - imunes
    - java21-oracle
    - jetbrains
    - matlab
    - mysql_workbench
    - npm
    - papel_de_parede_e_icones
    - quartus20
    - sources_list
    - unattendedUpgrades_labs
    - virtualbox
    - wireshark

  tasks:
    - name: Instala utilitários para o bash
      ansible.builtin.apt:
        pkg:
          - bash-completion
          - command-not-found
      when: ansible_os_family == 'Debian'

    - name: Adiciona conteúdo do /etc/bash.bashrc
      ansible.builtin.blockinfile:
        path: /etc/bash.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        content: |
          # enable bash completion in interactive shells
          if ! shopt -oq posix; then
            if [ -f /usr/share/bash-completion/bash_completion ]; then
              . /usr/share/bash-completion/bash_completion
            elif [ -f /etc/bash_completion ]; then
              . /etc/bash_completion
            fi
          fi
          export SHELL=/bin/bash
          export PATH=$PATH:/sbin
        backup: true
      when: ansible_os_family == 'Debian'
      tags: bashrc

    - name: Cria usuário aluno
      ansible.builtin.user:
        name: aluno
        password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
        shell: /bin/bash
        groups: plugdev,dialout
        append: true
      when: ansible_os_family == 'Debian'

    - name: Define conteúdo do arquivo /etc/sudoers
      ansible.builtin.copy:
        content: |
          #
          # This file MUST be edited with the 'visudo' command as root.
          #
          # Please consider adding local content in /etc/sudoers.d/ instead of
          # directly modifying this file.
          #
          # See the man page for details on how to write a sudoers file.
          #
          Defaults  env_reset
          Defaults  mail_badpass
          Defaults  secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

          # Host alias specification

          # User alias specification

          # Cmnd alias specification

          # User privilege specification
          root  ALL=(ALL:ALL) ALL

          # Allow members of group sudo to execute any command
          %sudo ALL=(ALL:ALL) ALL

          # See sudoers(5) for more information on "@include" directives:

          @includedir /etc/sudoers.d
        dest: /etc/sudoers
        owner: root
        group: root
        mode: '0440'
      when: ansible_os_family == 'Debian'

    - name: Adiciona programas para serem executados pelo sudo sem senha
      ansible.builtin.copy:
        content: |
          ALL   ALL=(ALL) NOPASSWD: SETENV: /usr/sbin/ethtool,/usr/sbin/ifconfig,/usr/bin/tcpdump,\
          /usr/sbin/route,/usr/bin/minicom,/usr/sbin/traceroute,/usr/bin/wireshark,/sbin/iwconfig,\
          /usr/sbin/iwlist,/usr/sbin/iw,/usr/sbin/dhclient,/usr/bin/MercurioIV_Linux_1.1.0.run,\
          /etc/init.d/isc-dhcp-server,/etc/init.d/udev,/usr/bin/rpcgen,/usr/sbin/rfkill,/usr/bin/ip,\
          /usr/bin/systemctl start NetworkManager,/usr/bin/systemctl stop NetworkManager,\
          /usr/bin/systemctl start NetworkManager.service,/usr/bin/systemctl stop NetworkManager.service
        dest: /etc/sudoers.d/packages
        owner: root
        group: root
        mode: '0440'
      when: ansible_os_family == 'Debian'

    - name: Permite dar um cat em todos os arquivos do /proc
      ansible.builtin.copy:
        content: |
          ALL   ALL=(ALL) NOPASSWD: SETENV: /usr/bin/cat /proc/*
        dest: /etc/sudoers.d/cat
        owner: root
        group: root
        mode: '0440'
      when: ansible_os_family == 'Debian'

    - name: Mantem o estado do arquivo /etc/init.d/apagaAluno.sh - Debian
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          rm -rf /var/spool/cron/crontabs/aluno
          rm -rf /home/aluno
          tar -zxvf /opt/backup/aluno.tgz -C / --exclude=home/aluno/.ssh/known_hosts
        dest: /etc/init.d/apagaAluno.sh
        owner: root
        group: root
        mode: '0755'
      when: ansible_os_family == 'Debian'

    - name: Mantem o estado do arquivo /lib/systemd/system/apagaAluno.service - Linux
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Usuário padrão
          DefaultDependencies=no
          Before=shutdown.target

          [Service]
          Type=oneshot
          ExecStart=/etc/init.d/apagaAluno.sh

          [Install]
          WantedBy=reboot.target halt.target poweroff.target
        dest: /lib/systemd/system/apagaAluno.service
        owner: root
        group: root
        mode: '0644'
      when: ansible_os_family == 'Debian'

    - name: Aplica o daemon-reload e o enable no servico apagaAluno - Linux
      ansible.builtin.systemd:
        enabled: true
        daemon_reload: true
        name: apagaAluno
      when: ansible_os_family == 'Debian'

    - name: Criando script WoL
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Configure Wake-up on LAN

          [Service]
          Type=oneshot
          ExecStart=/sbin/ethtool -s eth0 wol g

          [Install]
          WantedBy=basic.target
        dest: /lib/systemd/system/wol.service
        owner: root
        group: root
        mode: '0644'
      when: ansible_os_family == 'Debian'

    - name: Ativa o servico WoL
      ansible.builtin.systemd:
        enabled: true
        daemon_reload: true
        name: wol
      when: ansible_os_family == 'Debian'

    - name: Enable i386 architecture
      ansible.builtin.command: dpkg --add-architecture i386
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Run the equivalent of "apt-get clean" as a separate step
      ansible.builtin.apt:
        clean: true
      when: ansible_os_family == 'Debian'

    - name: Instalar pacotes
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - abntex
          - android-tools-adb
          - apt-transport-https
          - as31
          - audacity
          - avahi-daemon
          - avahi-utils
          - avarice
          - avrdude
          - avr-libc
          - binutils-avr
          - chrony
          - chrpath
          - cmake
          - cutecom
          - dia
          - diffstat
          - distcc
          - distccmon-gnome
          - dnsutils
          - ethtool
          - figlet
          - firmware-amd-graphics
          - firmware-ath9k-htc
          - firmware-atheros
          - firmware-linux
          - firmware-misc-nonfree
          - firmware-realtek
          - fish
          - flameshot
          - fping
          - fritzing
          - gcc-arm-none-eabi
          - gcc-avr
          - gdb
          - gdb-avr
          - geany
          - gedit
          - gimp
          - git
          - glade
          - gnupg
          - gnuradio
          - google-chrome-stable
          - graphviz
          - grub2
          - htop
          - inkscape
          - ipcalc
          - iperf
          - ipython3
          - kalzium
          - kdenlive
          - kicad
          - kolourpaint
          - konsole
          - latexila
          - lib32z1
          - libasound2
          - libbz2-1.0:i386
          - libc6-dev-i386
          - libc6:i386
          - libfontconfig1:i386
          - libfreetype6:i386
          - libgl1-mesa-dri
          - libglu1-mesa
          - libgtk2.0-0:i386
          - libncurses5
          - libncurses5:i386
          - libpng16-16:i386
          - libreoffice
          - libreoffice-l10n-pt-br
          - libsm6:i386
          - libstdc++6:i386
          - libxext6:i386
          - libxft2
          - libxft2:i386
          - libxi6:i386
          - libxrender1:i386
          - libxtst6:i386
          - libzmq3-dev
          - linux-image-amd64
          - linux-headers-amd64
          - logisim
          - ltrace
          - mariadb-client
          - mate-applet-brisk-menu
          - maven
          - mcu8051ide
          - minicom
          - mosquitto-clients
          - net-tools
          - nmap
          - nodejs
          - ntfs-3g
          - okular
          - pcaputils
          - pdfsam
          - python3
          - python3-dev
          - python3-pil
          - python3-pil.imagetk
          - python3-pip
          - python3-tk
          - python3-venv
          - qalc
          - rabbitmq-server
          - resolvconf
          - rfkill
          - snapd
          - snmp-mibs-downloader
          - sqlite3
          - sqlitebrowser
          - strace
          - subversion
          - swig
          - tcpdump
          - texlive-extra-utils
          - texlive-lang-portuguese
          - traceroute
          - tree
          - ttf-ancient-fonts
          - twinkle
          - u-boot-tools
          - unrar
          - uuid-dev
          - valgrind
          - vim
          - vlc
          - vokoscreen
          - whois
          - wireless-tools
          - wxmaxima
          - x2goclient
          - xournal
          - xpdf
          - xterm
      when: ansible_os_family == 'Debian'

    - name: Remover programas  - Linux
      ansible.builtin.apt:
        state: absent
        pkg:
          - transmission
          - transmission-common
          - linux-image-6.5.0-0.deb12.4-amd64
          - linux-headers-6.5.0-0.deb12.4-amd64
          - linux-headers-6.5.0-0.deb12.4-common
          - gnome-calculator
      when: ansible_os_family == 'Debian'

- name: Configurações aplicadas somente para os alunos
  hosts: laboratorios_lin:!lab_profs_lin
  roles:
    - lightdm-autologin

- name: Configurações aplicadas somente para as maquinas dos professores
  hosts: lab_profs_lin
  roles:
    - configura_monitores
    - iptables_prof


########### INDIVIDUALIDADE DOS LABORATÓRIOS ###########
- name: Laboratório de Informática
  hosts: info_lin
  roles:
    - google_earth
    - tracker
    - scidavis
    - qgis
    - role: grub
      tipo: grub_soh_lin
  tasks:
    - name: Cria o arquivo tcp_rmem chamado IFSC#2023050410000449
      ansible.builtin.copy:
        content: |
          10000 10000 10000
        dest: /proc/sys/net/ipv4/tcp_rmem
        owner: root
        group: root
        mode: '0644'
        unsafe_writes: true
      when: ansible_os_family == 'Debian'

    - name: Instala tiled via SNAP
      community.general.snap:
        name:
          - tiled
      when: ansible_os_family == 'Debian'
      tags: tiled

- name: Laboratório de Meios de Transmissão
  hosts: meios_lin
  roles:
    - role: grub
      tipo: grub_soh_lin
    - dbeaver
    - sqlitestudio

- name: Laboratório de Meios da cultura geral
  hosts: meios_cult_lin
  roles:
    - ingressa_ldap

- name: Laboratório de Programação
  hosts: programacao_lin
  roles:
    - dbeaver
    - sqlitestudio
  tasks:
    - name: Instala tiled via SNAP
      community.general.snap:
        name:
          - tiled
      when: ansible_os_family == 'Debian'
      tags: tiled

- name: Laboratório de comunicação sem fio
  hosts: csfio_lin
  roles:
    - role: grub
      tipo: grub_lin

- name: Laboratório de CAD1, CAD2 e CAD3
  hosts: cad1_lin,cad2_lin,cad3_lin
  roles:
    - role: grub
      tipo: grub_win

- name: Computadores da biblioteca para alunos
  hosts: biblio_aluno_lin
  roles:
    - role: grub
      tipo: grub_lin
