- hosts: all:!wol
  # #any_errors_fatal: true
  tasks:
    - name: Instalar o aptitude, necessario para o modulo apt
      apt: name=aptitude state=latest
      when: ansible_os_family == 'Debian'
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      when: ansible_os_family == 'Debian'
    - name: Remove useless packages from the cache
      apt: autoclean=yes
      when: ansible_os_family == 'Debian'
    - name: Remove dependencies that are no longer required
      apt: autoremove=yes
      when: ansible_os_family == 'Debian'
    - name: Upgrade all packages to the latest version
      apt: name="*" state=latest
      when: ansible_os_family == 'Debian'
    - name: Instalar o apt-transport-https
      apt: name=apt-transport-https state=latest
      when: ansible_os_family == 'Debian'

# Administrativos
- import_playbook: auditorios_vconf.yml
- import_playbook: biblio.yml
- import_playbook: cepe.yml
- import_playbook: cgp.yml
- import_playbook: coger.yml
- import_playbook: comaf.yml
- import_playbook: contra.yml
- import_playbook: computadores_interativos.yml
- import_playbook: comum_administrativo.yml
- import_playbook: cotel.yml
- import_playbook: cotur.yml
- import_playbook: corac.yml
- import_playbook: ctic.yml
- import_playbook: dae.yml
- import_playbook: depe.yml
- import_playbook: des1.yml
- import_playbook: des2.yml
- import_playbook: dire.yml
- import_playbook: labfisica.yml
- import_playbook: ledis.yml
- import_playbook: mcul.yml
- import_playbook: manut.yml
- import_playbook: mtele.yml
- import_playbook: nead.yml
- import_playbook: patrim.yml
- import_playbook: registro_academico.yml
- import_playbook: secretaria.yml
- import_playbook: sala.yml
- import_playbook: almox.yml
- import_playbook: vconf.yml

# Laboratorios
- import_playbook: almoxrac.yml
- import_playbook: ciehu.yml
- import_playbook: comum_laboratorios.yml
- import_playbook: labaplicada.yml
- import_playbook: labcad1.yml
- import_playbook: labcad2.yml
- import_playbook: labcad3.yml
- import_playbook: labcomex.yml
- import_playbook: labcsfio.yml
- import_playbook: labic.yml
- import_playbook: labmeios.yml
- import_playbook: labprogramacao.yml
- import_playbook: labredes.yml
- import_playbook: labinfo.yml
- import_playbook: labsidi.yml
- import_playbook: mrac.yml
- import_playbook: note.yml
- import_playbook: elerac.yml

#Comentei porque isso faz mais dentido quando usa com o ansible AWX, na mão é melhor que não seja executado.

# - hosts: all
#   gather_facts: false
#   tasks:
#     - meta: clear_host_errors
