- name: Administrativo Linux
  hosts: administrativos_lin

  roles:
    - upgrade_11to12
    - ingressa_ldap
    - sources_list
    - openaudit
    - acesso_remoto
    - fonte_garamound
    - unattendedUpgrades_adm
    - glpi_agent
    - auto_desligamento
    - warsaw
    - foxit
    - cadeia_certificados
    - java8-oracle
    - role: grub
      tipo: grub_soh_lin

  tasks:
    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.apt_key:
        id: 4EB27DB2A3B88B8B
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        keyring: /etc/apt/trusted.gpg.d/google-chrome.gpg
      when: ansible_os_family == 'Debian'

    - name: Instala utilitários para o bash
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - aptitude
          - bash-completion
          - chrony
          - command-not-found
          - dia
          - dkms
          - firmware-linux-free
          - firmware-linux-nonfree
          - gnome-terminal
          - google-chrome-stable
          - gscan2pdf
          - icedtea-netx
          - kdenlive
          - kolourpaint4
          - libcurl4
          - network-manager
          - network-manager-gnome
          - nfs-common
          - okular
          - pdfshuffler
          - ssh
          - system-config-printer
          - unrar
          - vim
          - vlc
      when: ansible_os_family == 'Debian'

    - name: Instala pacotes .deb
      ansible.builtin.apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      when: ansible_os_family == 'Debian'

    - name: Remover programas  - Linux
      ansible.builtin.apt:
        state: absent
        pkg:
          - transmission
          - transmission-common
      when: ansible_os_family == 'Debian'

    - name: Inclui o role do NTP do Linux
      ansible.builtin.include_role:
        name: geerlingguy.ntp
      vars:
        ntp_timezone: America/Sao_Paulo
        ntp_manage_config: true
        ntp_servers:
          - "pool.ntp.br iburst"
          - "ntp.cais.rnp.br iburst"
          - "ntp.ufsc.br iburst"
      when: ansible_os_family == 'Debian'

    - name: Define conteúdo do /etc/bash.bashrc
      ansible.builtin.copy:
        content: |
          # System-wide .bashrc file for interactive bash(1) shells.
          # To enable the settings / commands in this file for login shells as well,
          # this file has to be sourced in /etc/profile.
          # If not running interactively, don't do anything
          [ -z "$PS1" ] && return

          # check the window size after each command and, if necessary,
          # update the values of LINES and COLUMNS.
          shopt -s checkwinsize

          # set variable identifying the chroot you work in (used in the prompt below)
          if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
              debian_chroot=$(cat /etc/debian_chroot)
          fi

          # set a fancy prompt (non-color, overwrite the one in /etc/profile)
          # but only if not SUDOing and have SUDO_PS1 set; then assume smart user.
          if ! [ -n "${SUDO_USER}" -a -n "${SUDO_PS1}" ]; then
            PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
          fi

          # enable bash completion in interactive shells
          if ! shopt -oq posix; then
            if [ -f /usr/share/bash-completion/bash_completion ]; then
              . /usr/share/bash-completion/bash_completion
            elif [ -f /etc/bash_completion ]; then
              . /etc/bash_completion
            fi
          fi

          # if the command-not-found package is installed, use it
          if [ -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ]; then
            function command_not_found_handle {
                    # check because c-n-f could've been removed in the meantime
                          if [ -x /usr/lib/command-not-found ]; then
                /usr/lib/command-not-found -- "$1"
                            return $?
                          elif [ -x /usr/share/command-not-found/command-not-found ]; then
                /usr/share/command-not-found/command-not-found -- "$1"
                            return $?
              else
                printf "%s: command not found\n" "$1" >&2
                return 127
              fi
            }
          fi
          export SHELL=/bin/bash
          export PATH=$PATH:/sbin
        dest: /etc/bash.bashrc
        owner: root
        group: root
        mode: '0644'
        backup: true
      when: ansible_os_family == 'Debian'
      tags: bashrc
