- name: Laboratórios Linux
  hosts: laboratorios_lin

  roles:
    - upgrade_11to12
    - flatpak
    - virtualbox
    - java21-oracle
    - gradle_8.5
    - jetbrains
    - docker

  tasks:

    - name: Instala utilitários para o bash
      ansible.builtin.apt:
        pkg:
          - bash-completion
          - command-not-found
      when: ansible_os_family == 'Debian'

    - name: Define conteúdo do /etc/bash.bashrc
      ansible.builtin.copy:
        content: |
          # System-wide .bashrc file for interactive bash(1) shells.
          # To enable the settings / commands in this file for login shells as well,
          # this file has to be sourced in /etc/profile.
          # If not running interactively, don't do anything
          [ -z "$PS1" ] && return

          # check the window size after each command and, if necessary,
          # update the values of LINES and COLUMNS.
          shopt -s checkwinsize

          # set variable identifying the chroot you work in (used in the prompt below)
          if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
              debian_chroot=$(cat /etc/debian_chroot)
          fi

          # set a fancy prompt (non-color, overwrite the one in /etc/profile)
          # but only if not SUDOing and have SUDO_PS1 set; then assume smart user.
          if ! [ -n "${SUDO_USER}" -a -n "${SUDO_PS1}" ]; then
            PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
          fi

          # enable bash completion in interactive shells
          if ! shopt -oq posix; then
            if [ -f /usr/share/bash-completion/bash_completion ]; then
              . /usr/share/bash-completion/bash_completion
            elif [ -f /etc/bash_completion ]; then
              . /etc/bash_completion
            fi
          fi

          # if the command-not-found package is installed, use it
          if [ -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ]; then
            function command_not_found_handle {
                    # check because c-n-f could've been removed in the meantime
                          if [ -x /usr/lib/command-not-found ]; then
                /usr/lib/command-not-found -- "$1"
                            return $?
                          elif [ -x /usr/share/command-not-found/command-not-found ]; then
                /usr/share/command-not-found/command-not-found -- "$1"
                            return $?
              else
                printf "%s: command not found\n" "$1" >&2
                return 127
              fi
            }
          fi
          export SHELL=/bin/bash
          export PATH=$PATH:/sbin
        dest: /etc/bash.bashrc
        owner: root
        group: root
        mode: '0644'
        backup: true
      when: ansible_os_family == 'Debian'
      tags: bashrc

 #Import de playbooks
- import_playbook: labcad1.yml
- import_playbook: labcad2.yml
- import_playbook: labcad3.yml
- import_playbook: labprogramacao.yml
- import_playbook: labredes.yml
- import_playbook: labinfo.yml
- import_playbook: labsidi.yml
