- hosts: mtele
  #any_errors_fatal: true
  roles:
    - packettracer
    - kile
    - virtualbox
    # - programas_padroes_labs

- hosts: sj-lin-mtele-577558.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - zoiper
    - code
    - virtualbox

- hosts: sj-lin-mtele-703868.maquinas.sj.ifsc.edu.br
  roles:
    - role: grub
      tipo: grub_lin

- hosts: sj-lin-mtele-710798.maquinas.sj.ifsc.edu.br
  roles:
    - imunes
