- hosts: mtele
  #any_errors_fatal: true
  roles:
    - packettracer
    - kile
    - virtualbox
    # - programas_padroes_labs

- hosts: sj-lin-mtele-577558.maquinas.sj.ifsc.edu.br
  #any_errors_fatal: true
  roles:
    - zoiper
    - code
    - virtualbox
  tasks:
    - name: Adiciona usuaria mayara.sousa no grupo sudo
      user:
        name: mayara.sousa
        groups: sudo
        append: yes
      when: ansible_os_family == 'Debian'

- hosts: sj-lin-mtele-703868.maquinas.sj.ifsc.edu.br
  roles:
    - role: grub
      tipo: grub_lin

- hosts: sj-lin-mtele-710798.maquinas.sj.ifsc.edu.br
  roles:
    - imunes
