- name: Computador da Ana Martens
  hosts: sj-lin-patrim-710789.maquinas.sj.ifsc.edu.br
  roles:
    - ingressa_ldap_sem_cups_client
    - role: instala_impressora_cups
      install: 0
      argox: 1
      compras: 1
      cgp: 1
      financeiro: 1

  tasks:
    - name: Instalar o software para criar as etiquetas Linux Debian
      ansible.builtin.apt:
        name:
          - glabels

- name: Notebook emprestado
  hosts: sj-lin-patri-cgwhd33.maquinas.sj.ifsc.edu.br
  tasks:
    - name: Pacote necessario para ativar wifi
      ansible.builtin.apt:
        pkg:
          - firmware-iwlwifi
  roles:
    - configura_wifi
    - role: grub
      tipo: grub_soh_lin
    - role: instala_impressora_cups
      install: 0
      argox: 1
