- hosts: radio
  #any_errors_fatal: true
  roles:
    - sources_list
    - openaudit
    - programas_padroes_adm
    - config_padrao_adm
    - acesso_remoto
    - fonte_garamound
    - papel_de_parede_e_icones_adm
    - unattendedUpgrades_adm
  tasks:
  - name: Cria usuário radio com a senha radio
    user:
      name: radio
      password: $6$a3vEHVzD$3b8g8edHiFm2lWR6LGhbgZgHqGL4c9Cw6RIFVQGapw0VP.KobPinHezoyV4213IzVxRYhyB7876rgGHVbumXW.
      append: yes
  - name: Pacotes especiais para o pc da radio
    apt:
      state: latest
      pkg:
      - audacity
