####################  NÃO ESTÁ EM USO

# - name: Instalação spotyfy
#   hosts: sje-lin-radio-926196.maquinas.sj.ifsc.edu.br
#   tasks:
#     - name: Baixar chave GPG do Spotify
#       ansible.builtin.shell:
#         path: /etc/passwd
#         backup: true
#         block: |
#           radio:x:1001:1001::/home/radio:
#       when: ansible_os_family == 'Debian'

#     - name: Adiciona linha do usuario radio no group
#       ansible.builtin.blockinfile:
#         path: /etc/group
#         backup: true
#         block: |
#           radio:x:1001:radio
#       when: ansible_os_family == 'Debian'

#     - name: Cria usuário radio com a senha radio
#       ansible.builtin.user:
#         name: radio
#         shell: /bin/bash
#         password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
#         groups: radio
#         append: true
#       when: ansible_os_family == 'Debian'

#     - name: Pacotes especiais
#       ansible.builtin.apt:
#         pkg:
#           - x2goclient
#           - wxmaxima
#           - python3-matplotlib
#           - python3-numpy
#           - python3-scipy
#           - python3-pandas
#           - python3-pip
#       tags: pacotes

# ##### Configuração do script para apagar o aluno do radio a cade inicialização
#     - name: Adiciona script para zerar o aluno do radio
#       ansible.builtin.copy:
#         content: |
#           #!/bin/bash

#           ##Este arquivo eh gerado automaticamente pelo Ansible, nao adianta editar.

#           #Restaurar o usuario aluno quando manda desligar a maquina ou reiniciar.
#           rm -rf /var/spool/cron/crontabs/aluno
#           rm -rf /home/aluno
#           tar -zxvf /home/backup/aluno.tgz -C / --exclude=home/aluno/.ssh/known_hosts
#         dest: /etc/init.d/apagaaluno.sh
#         owner: root
#         group: root
#         mode: '0755'
#       when: ansible_os_family == 'Debian'
#       tags: apagaaluno

#     - name: Adiciona o arquivo /lib/systemd/system/apagaaluno.service
#       ansible.builtin.copy:
#         content: |
#           [Unit]
#           Description=Usuário padrão
#           DefaultDependencies=no
#           Before=shutdown.target

#           [Service]
#           Type=oneshot
#           ExecStart=/etc/init.d/apagaaluno.sh

#           [Install]
#           WantedBy=reboot.target halt.target poweroff.target
#         dest: /lib/systemd/system/apagaaluno.service
#         owner: root
#         group: root
#         mode: '0644'
#       when: ansible_os_family == 'Debian'
#       tags: apagaaluno

#     - name: Aplica o daemon-reload e o enable no servico apagaaluno - Linux
#       ansible.builtin.systemd:
#         enabled: true
#         daemon_reload: true
#         name: apagaaluno
#       when: ansible_os_family == 'Debian'
#       tags: apagaaluno

# ###################### Fim do Apagaaluno
