- name: Garante a desinstalação da versão antiga
  ansible.builtin.apt:
    name:
      - gnome-calculator
    state: absent
  when: ansible_os_family == 'Debian'

- name: Instala o GNOME Calculator via flatpak
  community.general.flatpak:
    name:
      - org.gnome.Calculator
    state: present
  when: ansible_os_family == 'Debian'
