---
# Debian e Ubuntu
- name: Apagar disk1 antes de restaurar as máquinas virtuais - Linux
  file:
    path: /opt/vdi/{{ item }}/UbuntuGrafico-disk001.vdi
    state: absent
  with_items: "{{nome_vms}}"
  when: ansible_os_family == 'Debian'

- name: Apagar disk2 antes de restaurar as máquinas virtuais - Linux
  file:
    path: /opt/vdi/{{ item }}/UbuntuGrafico-disk002.vdi
    state: absent
  with_items: "{{nome_vms}}"
  when: ansible_os_family == 'Debian'

- name: Restaurar as máquinas virtuais - Linux
  unarchive:
    src: /opt/backup/{{ item }}.bz
    dest: /
    remote_src: yes
  with_items: "{{nome_vms}}"
  when: ansible_os_family == 'Debian'
