---

- name: Cria diretório gradle - Linux Debian
  ansible.builtin.file:
    path: /opt/gradle
    state: directory
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Baixando e extraindo o Gradle 8.2.1 - Linux Debian
  ansible.builtin.unarchive:
    src: https://services.gradle.org/distributions/gradle-8.2.1-all.zip
    dest: /opt/gradle
    creates: /opt/gradle/instalado
    remote_src: yes
    owner: aluno
    group: 513
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada no /etc/bash.bashrc  - Linux
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    line: 'export PATH=$PATH:/opt/gradle/gradle-8.2.1/bin'
  when: ansible_os_family == 'Debian'

- name: Executa o gradle - Linux Debian
  ansible.builtin.command: /opt/gradle/gradle-8.2.1/bin/gradle
  args:
    creates: /opt/gradle/instalado
  when: ansible_os_family == 'Debian'

- name: Finaliza instalacao - Linux Debian
  changed_when: False
  ansible.builtin.file:
    path: /opt/gradle/instalado
    state: touch
  when: ansible_os_family == 'Debian'

- name: Create a symbolic link
  ansible.builtin.file:
    src: /opt/gradle/gradle-8.2.1/bin/gradle
    dest: /usr/bin/gradle
    state: link
