# Linux
- name: Instalar geogebra - flatpak
  community.general.flatpak:
    name: org.geogebra.GeoGebra
    state: present
  when: ansible_os_family == 'Debian'

# Windows
- name: Baixar e instalar Geogebra - Windows
  chocolatey.chocolatey.win_chocolatey:
    name: geogebra
  when: ansible_os_family == 'Windows'
