- name: Adicionar a chave do repositório do AnyDesk
  apt_key:
    url: https://keys.anydesk.com/repos/DEB-GPG-KEY
    state: present
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório AnyDesk
  apt_repository:
    repo: deb http://deb.anydesk.com/ all main
  when: ansible_os_family == 'Debian'

- name: Instala AnyDesk
  apt:
    pkg:
    - anydesk
  when: ansible_os_family == 'Debian'
