#Linux

- name: Instalar pacote NPM - Linux
  ansible.builtin.apt:
    name: npm
    state: present
  when: ansible_os_family == 'Debian'

- name: Instala pacotes globalmente.
  community.general.npm:
    name: "{{ npm_pkgs }}"
    global: true
  loop:
      - angular
      - vue
      - create-react-app
  loop_control:
    loop_var: npm_pkgs
  when: ansible_os_family == 'Debian'
