- name: Adicionar a chave do repositório do assinador serpro - Linux
  ansible.builtin.apt_key:
    url: https://assinadorserpro.estaleiro.serpro.gov.br/repository/AssinadorSERPROpublic.asc
    keyring: /etc/apt/trusted.gpg.d/AssinadorSERPROpublic.gpg
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório para instalar assinador Serpro
  ansible.builtin.apt_repository:
    repo: deb https://www.assinadorserpro.estaleiro.serpro.gov.br/repository/ universal stable
    update_cache: true
  when: (ansible_os_family == 'Debian')

- name: Instalar pacotes assinador-serpro
  ansible.builtin.apt:
    pkg:
      - assinador-serpro
  when: (ansible_os_family == 'Debian')
