#Linux

- name: Copia script para a maquina do professor - Linux
  copy:
    src: firewall.sh
    dest: /etc/init.d/firewall.sh
    owner: root
    group: root
    mode: 0755
  with_items:
    - sidi-918545
    - redes-906284
    - prog-744523
    - cad1-916082
    - cad2-905476
    - cad3-744517
  when: ( ansible_os_family == 'Debian' and  ansible_hostname is search("^sj-lin-{{ item }}") )

- name: Copia o arquivo com os patrimonios para a maquina do professor - Linux
  copy:
    src: pat
    dest: /var/pat
    owner: root
    group: root
    mode: 0755
  with_items:
    - sidi-918545
    - redes-906284
    - prog-744523
    - cad1-916082
    - cad2-905476
    - cad3-744517
  when: ( ansible_os_family == 'Debian' and ansible_hostname is search("^sj-lin-{{ item }}") )

- name: Copia regras ipv6 de bloqueio para todas as maquinas - Linux
  copy:
    src: block6
    dest: /var/block6
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Copia regras ipv6 da wiki para todas as maquinas - Linux
  copy:
    src: wiki6
    dest: /var/wiki6
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Copia regras de libera para todas as maquinas - Linux
  template:
    src: 'templates/libera.j2'
    dest: /var/libera
  when: ansible_os_family == 'Debian'

- name: Copia regras ipv4 de bloqueio para todas as maquinas - Linux
  template:
    src: 'templates/block4.j2'
    dest: /var/block4
  when: ansible_os_family == 'Debian'

- name: Copia regras ipv4 da wiki para todas as maquinas - Linux
  template:
    src: 'templates/wiki4.j2'
    dest: /var/wiki4
  when: ansible_os_family == 'Debian'
