########## Linux ##########
- name: Baixando e extraindo LTspice
  ansible.builtin.unarchive:
    src: LTC.zip
    dest: /opt/
    creates: /opt/LTC/update
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: Cria atalho
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Name=LTspice XVII
      Comment=LTspice
      Exec=wine /opt/LTC/LTspiceXVII/XVIIx64.exe
      Terminal=false
      Type=Application
      Categories=Development;
    dest: /usr/share/applications/ltspice.desktop
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

########## Windows ##########
- name: Copia o arquivo de configuracao do LTSpice - Windows
  ansible.windows.win_copy:
    src: LTC.zip
    dest: C:\instaladores\LTC.zip
  when: ansible_os_family == 'Windows'

- name: Extrai o LTC LTspice em C:\Program Files\
  community.windows.win_unzip:
    src: C:\instaladores\LTC.zip
    dest: C:\Program Files\
    creates: C:\Program Files\LTC\update
  when: ansible_os_family == 'Windows'

- name: Cria o atalho do Ltspice - Windows
  community.windows.win_shortcut:
    src: C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe
    dest: C:\Users\Public\Desktop\LTspiceXVII.lnk
    icon: C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe,0
  when: ansible_os_family == 'Windows'
