########## Linux ##########
- name: Baixando e extraindo LTspice
  ansible.builtin.unarchive:
    src: LTC.zip
    dest: /opt/
    creates: /opt/LTC
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: Cria atalho
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Name=LTspice XVII
      Comment=LTspice
      Exec=wine /opt/LTC/LTspiceXVII/XVIIx64.exe
      Terminal=false
      Type=Application
      Categories=Development;
    dest: /usr/share/applications/ltspice.desktop
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Copia os arquivo LM741.lib e LM741.asy
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: LM741.asy,
        dest: /opt/LTC/LTspiceXVII/lib/sym/Opamps/LM741.asy, }
    - { src: LM741.lib,
        dest: /opt/LTC/LTspiceXVII/lib/sub/LM741.lib, }
  when: ansible_os_family == 'Debian'

########## Windows ##########
- name: Copia o arquivo de configuracao do LTSpice - Windows
  ansible.windows.win_copy:
    src: LTC.zip
    dest: C:\instaladores\LTC.zip
  when: ansible_os_family == 'Windows'

- name: Extrai o LTC LTspice em C:\Program Files\
  community.windows.win_unzip:
    src: C:\instaladores\LTC.zip
    dest: C:\Program Files\
    creates: C:\Program Files\LTC
  when: ansible_os_family == 'Windows'

- name: Cria o atalho do Ltspice - Windows
  community.windows.win_shortcut:
    src: C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe
    dest: C:\Users\Public\Desktop\LTspiceXVII.lnk
    icon: C:\Program Files\LTC\LTspiceXVII\XVIIx64.exe,0
  when: ansible_os_family == 'Windows'

- name: Copia arquivo LM741.lib
  ansible.windows.win_copy:
    src: LM741.lib
    dest: C:\Program Files\LTC\LTspiceXVII\lib\sub\LM741.lib
  when: ansible_os_family == 'Windows'

- name: Copia arquivo LM741.asy
  ansible.windows.win_copy:
    src: LM741.asy
    dest: C:\Program Files\LTC\LTspiceXVII\lib\sym\Opamps\LM741.asy
  when: ansible_os_family == 'Windows'
