---
# Linux

- name: Baixar e instalar zoiper 5.5.15 - Linux
  ansible.builtin.apt:
    deb: http://ansiblefiles.sj.ifsc.edu.br/Zoiper5_5.5.15_x86_64.deb
  when: ansible_os_family == 'Debian'

# Windows
- name: Baixar e instalar o Zoiper 5.6.4 - Windows
  ansible.windows.win_package:
    path: http://ansiblefiles.sj.ifsc.edu.br/Zoiper_Installer_5.6.4.exe
    product_id: "Zoiper5"
    arguments:
      - --mode
      - unattended
      - --unattendedmodeui
      - minimal
    state: present
  when: ansible_os_family == 'Windows'
