- name: Adiciona repositório do node para o 'Debian'
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/trusted.gpg.d/nodesource.asc
    mode: '0644'
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: Adiciona repositório do node para o 'Debian'
  ansible.builtin.copy:
    content: |
      deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/nodesource.asc] https://deb.nodesource.com/node_24.x nodistro main
    dest: /etc/apt/sources.list.d/nodejs.list
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Instala o nodejs do repositorio
  ansible.builtin.apt:
    name: nodejs
    state: latest
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Apaga pasta antiga do npm
  ansible.builtin.file:
    path: /npm    
    state: absent
  when: ansible_os_family == 'Debian'
