- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /opt/backup/
    state: directory
    mode: '0755'
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: aluno tgz
  ansible.builtin.copy:
    src: aluno.tgz
    dest: /opt/backup/aluno.tgz
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
