- name: Instalar o lusermod
  ansible.builtin.apt:
    name: libuser
  when: ansible_os_family == 'Debian'

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /opt/backup/
    state: directory
    mode: '0755'
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: Copia aluno tgz
  ansible.builtin.get_url:
    url: http://ansiblefiles.sj.ifsc.edu.br/aluno.tgz
    dest: /opt/backup/aluno.tgz
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == 'Debian'

- name: Cria usuário aluno com a senha aluno
  ansible.builtin.user:
    name: aluno
    shell: /bin/bash
    password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
    append: true
    local: true
  when: ansible_os_family == 'Debian'

- name: Configuracao aba anonima chrome - Linux
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Version=1.0
      Name=Google Chrome
      GenericName=Web Browser
      GenericName[pt_BR]=Navegador da Internet
      Exec=/usr/bin/google-chrome-stable %U --incognito
      StartupNotify=true
      Terminal=false
      Icon=google-chrome
      Type=Application
      Categories=Network;WebBrowser;
      MimeType=application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;
      Actions=new-window;new-private-window;

      [Desktop Action new-window]
      Name[pt_BR]=Nova janela
      Exec=/usr/bin/google-chrome-stable --incognito

      [Desktop Action new-private-window]
      Name=New Incognito Window
      Name[pt_BR]=Nova janela anônima
      Exec=/usr/bin/google-chrome-stable --incognito

    dest: /usr/share/applications/google-chrome.desktop
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Configuracao aba anonima firefox - Linux
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Name=Firefox ESR
      Name[pt_BR]=Firefox ESR
      Comment[pt_BR]=Navegue na Internet
      GenericName[pt_BR]=Navegador Web
      X-GNOME-FullName[pt_BR]=Navegador Web Firefox ESR
      Exec=/usr/lib/firefox-esr/firefox-esr %u --private-window
      Terminal=false
      X-MultipleArgs=false
      Type=Application
      Icon=firefox-esr
      Categories=Network;WebBrowser;
      MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
      StartupWMClass=Firefox-esr
      StartupNotify=true
    dest: /usr/share/applications/firefox-esr.desktop
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

##### Configuração do script para apagar o home do aluno quando desliga ou reinicia
- name: Adiciona script para zerar o home do aluno
  ansible.builtin.copy:
    content: |
      #!/bin/bash

      ##Este arquivo eh gerado automaticamente pelo Ansible, nao adianta editar.

      #Restaurar o usuario aluno quando manda desligar a maquina ou reiniciar.
      rm -rf /var/spool/cron/crontabs/aluno
      rm -rf /home/aluno
      tar -zxvf /opt/backup/aluno.tgz -C / --exclude=home/aluno/.ssh/known_hosts
    dest: /etc/init.d/apagaAluno.sh
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family == 'Debian'
  tags: apagaAluno

- name: Adiciona o arquivo /lib/systemd/system/apagaAluno.service
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Usuário padrão
      DefaultDependencies=no
      Before=shutdown.target

      [Service]
      Type=oneshot
      ExecStart=/etc/init.d/apagaAluno.sh
      StandardOutput=journal

      [Install]
      WantedBy=reboot.target halt.target poweroff.target
    dest: /lib/systemd/system/apagaAluno.service
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'
  tags: apagaAluno

- name: Aplica o daemon-reload e o enable no servico apagaAluno - Linux
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: true
    name: apagaAluno
  when: ansible_os_family == 'Debian'
  tags: apagaAluno

- name: Script que apaga alguns arquivos na inicialização
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      rm -rf /home/aluno/.bash_history
      rm -rf /home/aluno/.gitconfig
      rm -rf /home/aluno/.gradle
      rm -rf /home/aluno/.ssh
      rm -rf /home/aluno/.vscode
      rm -rf /home/aluno/.config/Code
      rm -rf /home/aluno/.mozilla
    dest: /etc/init.d/apagaArquivosAluno.sh
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family == 'Debian'
  tags: apagaArquivosAluno

- name: Adiciona o arquivo /lib/systemd/system/apagaArquivosAluno.service
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Executa o script apagaArquivosAluno.sh

      [Service]
      Type=oneshot
      ExecStart=/etc/init.d/apagaArquivosAluno.sh
      StandardOutput=journal

      [Install]
      WantedBy=multi-user.target
    dest: /lib/systemd/system/apagaArquivosAluno.service
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'
  tags: apagaArquivosAluno

- name: Aplica o daemon-reload e o enable no servico apagaAluno - Linux
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: true
    name: apagaArquivosAluno
  when: ansible_os_family == 'Debian'
  tags: apagaArquivosAluno
