#! /bin/sh
# /etc/init.d/x11vnc

case "$1" in
  start)
    echo "Starting script x11vnc "
    /usr/bin/x11vnc -auth guess -noxdamage -rfbport 5900 -shared -forever -nopw -accept popup:0 &
    ;;
  *)
    echo "Usage: /etc/init.d/x11vnc {start}"
    exit 1
    ;;
esac

exit 0
