- name: Baixa e extrai tracker
  unarchive:
    src: http://ansiblefiles.sj.ifsc.edu.br/tracker-6.1.3.bz
    dest: /opt/
    creates: /opt/tracker
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Criando o arquivo tracker.desktop - Linux Debian
  copy:
    src: tracker.desktop
    dest: /usr/share/applications/tracker.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
