---

- name: Instalar Gradle 7.5.1 chamado Emerson Mello - Linux
  apt:
    state: absent
    pkg:
      - gradle
  when: ansible_os_family == 'Debian'
- name: Cria diretório gradle - Linux Debian
  file:
    path: /opt/gradle
    state: directory
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Baixando e extraindo o Gradle 7.5.1 - Linux Debian
  unarchive:
    src: https://services.gradle.org/distributions/gradle-7.5.1-all.zip
    dest: /opt/gradle
#    creates: /opt/gradle/instalado
    remote_src: yes
    owner: aluno
    group: 513
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada no /etc/bash.bashrc  - Linux
  lineinfile:
    path: /etc/bash.bashrc
    line: 'export PATH=$PATH:/opt/gradle/gradle-7.5.1/bin'
  when: ansible_os_family == 'Debian'

- name: Executa o gradle - Linux Debian
  command: /opt/gradle/gradle-7.5.1/bin/gradle
  args:
    creates: /opt/gradle/instalado
  when: ansible_os_family == 'Debian'

- name: Finaliza instalacao - Linux Debian
  changed_when: False
  file:
    path: /opt/gradle/instalado
    state: touch
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada no /etc/bash.bashrc  - Linux
  lineinfile:
    path: /etc/bash.bashrc
    line: 'export PATH=$PATH:/opt/gradle/gradle-7.4.2/bin'
    state: absent
  when: ansible_os_family == 'Debian'
