#Windows

- name: Baixar e instalar o SR2015 - Windows
  ansible.windows.win_package:
    path: http://ansiblefiles.sj.ifsc.edu.br/sr2015.exe
    product_id: "SR 2015_is1"
    arguments:
      - /VERYSILENT
      - /SUPPRESSMSGBOXES
      - /NORESTART
      - /SP-
    state: present
  when: ansible_os_family == 'Windows'

- name: Atalho para o SR2015
  community.windows.win_shortcut:
    description: Atalho para o SR2015
    src: 'C:\Program Files (x86)\SR 2015\SR2015.exe'
    dest: '%Public%\Desktop\SR 2015.lnk'
    icon: 'C:\Program Files (x86)\SR 2015\SR2015.exe,0'
    state: present
  when: ansible_os_family == 'Windows'
