#Linux

- name: Instalar pacotes para o Wireshark - Linux
  ansible.builtin.apt:
    state: latest
    pkg:
    - wireshark
    - wireshark-doc
  when: ansible_os_family == 'Debian'

- name: Set CAP_NET_RAW+eip on /usr/bin/dumpcap for Wireshark - Linux
  community.general.capabilities:
    path: /usr/bin/dumpcap
    capability: CAP_NET_RAW+eip
    state: present
  changed_when: False

  when: ansible_os_family == 'Debian'

- name: Set CAP_NET_ADMIN+eip on /usr/bin/dumpcap for Wireshark - Linux
  community.general.capabilities:
    path: /usr/bin/dumpcap
    capability: CAP_NET_ADMIN+eip
    state: present
  changed_when: False
  when: ansible_os_family == 'Debian'

#Windows
- name: Instalar o Wireshark - Windows
  chocolatey.chocolatey.win_chocolatey:
    name: wireshark
    # state: latest
  when: ansible_os_family == 'Windows'
