- name: Instala flatpak
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - flatpak
  when: ansible_os_family == 'Debian'

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  when: ansible_os_family == 'Debian'

- name: Automatic update flatpak --user
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Update user Flatpaks

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/flatpak update --assumeyes --noninteractive

      [Install]
      WantedBy=default.target
    owner: root
    group: root
    mode: '0644'
    dest: /etc/systemd/user/update-user-flatpaks.service
  when: ansible_os_family == 'Debian'


- name: Automatic update flatpak --system
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Update system Flatpaks
      After=network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/flatpak update --assumeyes --noninteractive --system

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'
    dest: /etc/systemd/system/update-system-flatpaks.service
  when: ansible_os_family == 'Debian'

- name: Timer for automatic update flatpak --user
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Update user Flatpaks daily

      [Timer]
      OnCalendar=daily
      Persistent=true

      [Install]
      WantedBy=timers.target
    owner: root
    group: root
    mode: '0644'
    dest: /etc/systemd/user/update-user-flatpaks.timer
  when: ansible_os_family == 'Debian'

- name: Timer for automatic update flatpak --system
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Update system Flatpaks daily

      [Timer]
      OnCalendar=daily
      Persistent=true

      [Install]
      WantedBy=timers.target
    owner: root
    group: root
    mode: '0644'
    dest: /etc/systemd/system/update-system-flatpaks.timer
  when: ansible_os_family == 'Debian'

- name: Enable systemd update-user-flatpaks.timer
  ansible.builtin.systemd_service:
    name: update-user-flatpaks.timer
    state: started
    enabled: true
    scope: user
    daemon_reload: true
  when: ansible_os_family == 'Debian'

- name: Enable systemd update-system-flatpaks.timer
  ansible.builtin.systemd_service:
    name: update-system-flatpaks.timer
    state: started
    enabled: true
    scope: system
  when: ansible_os_family == 'Debian'
