### Site onde baixar.
# https://www.gov.br/iti/pt-br/assuntos/navegadores/
# https://www.gov.br/iti/pt-br/assuntos/repositorio/repositorio-ac-raiz

- name: Cria o diretório /home/certificados
  ansible.builtin.file:
    path: /home/certificados
    state: directory
    mode: "0755"
  when: ansible_os_family == 'Debian'

- name: Extrai certificados da Cadeia ICP Brasil
  ansible.builtin.unarchive:
    src: ACcompactado.zip
    dest: "{{ item }}"
    creates: "{{ item }}/ICP-Brasilv12.crt"
  loop:
    - /home/certificados
    - /usr/local/share/ca-certificates
  when: ansible_os_family == 'Debian'

- name: Executa update-ca-certificates
  ansible.builtin.command:
    cmd: update-ca-certificates
  when: ansible_os_family == 'Debian'

- name: Instala libnss3-tools
  ansible.builtin.apt:
    pkg:
      - libnss3-tools
  when: ansible_os_family == 'Debian'

- name: Copia script para importar certificados
  ansible.builtin.copy:
    src: importa_cadeia.sh
    dest: /usr/local/bin
    mode: "0755"
  when: ansible_os_family == 'Debian'
  tags: importa_cadeia

- name: Cria lançador do script para importar certificados
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Version=1.0
      Name= Importa cadeia ICP Brasil
      Comment=Importa cadeia de certificados da ICP Brasil para os navegadores do usuário
      Exec=bash -c '/usr/local/bin/importa_cadeia.sh && exit'
      Icon=utilities-terminal
      Terminal=true
      Type=Application
      Categories=Application;
    dest: /usr/share/applications/importa_cadeia.desktop
    mode: "0644"
  when: ansible_os_family == 'Debian'
