- name: Todos os hosts
  hosts: all

  tasks:
    - name: Libera dns
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: 53
        table: filter
        jump: ACCEPT
      when: ansible_os_family == 'Debian'

    - name: Entrada ssh
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: 22
        match:
          - conntrack
        ctstate:
          - NEW
          - ESTABLISHED
        table: filter
        jump: ACCEPT
      when: ansible_os_family == 'Debian'

    - name: Saída ssh
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        source_port: 22
        match:
          - conntrack
        ctstate:
          - ESTABLISHED
        table: filter
        jump: ACCEPT
      when: ansible_os_family == 'Debian'

    - name: Libera wiki.sj.ifsc.edu.br
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: wiki.sj.ifsc.edu.br
        table: filter
        jump: ACCEPT
      when: ansible_os_family == 'Debian'

    - name: Libera license-server.sj.ifsc.edu.br
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: license-server.sj.ifsc.edu.br
        table: filter
        jump: ACCEPT
      when: ansible_os_family == 'Debian'

    - name: Libera sigaa.ifsc.edu.br
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: sigaa.ifsc.edu.br
        table: filter
        jump: ACCEPT
      when: ansible_os_family == 'Debian'

    - name: Libera moodle.ifsc.edu.br
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: moodle.ifsc.edu.br
        table: filter
        jump: ACCEPT
      when: ansible_os_family == 'Debian'

    - name: Bloqueia saída
      ansible.builtin.iptables:
        chain: OUTPUT
        table: filter
        jump: DROP
      when: ansible_os_family == 'Debian'

    - name: Bloqueia entrada
      ansible.builtin.iptables:
        chain: INPUT
        table: filter
        jump: DROP
      when: ansible_os_family == 'Debian'
