- name: Todos os hosts
  hosts: all

  tasks:
    - name: Libera localhost IPv4
      ansible.builtin.iptables:
        chain: "{{ item }}"
        protocol: all
        ip_version: ipv4
        destination: 127.0.0.0/8
        table: filter
        jump: ACCEPT
      loop:
        - OUTPUT
        - INPUT
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Libera localhost IPv6
      ansible.builtin.iptables:
        chain: "{{ item }}"
        protocol: all
        ip_version: ipv6
        destination: ::1
        table: filter
        jump: ACCEPT
      loop:
        - OUTPUT
        - INPUT
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Libera dns
      ansible.builtin.iptables:
        chain: "{{ item }}"
        protocol: udp
        destination_port: 53
        table: filter
        jump: ACCEPT
      loop:
        - OUTPUT
        - INPUT
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Libera saída epoptes server
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: 789
        table: filter
        jump: ACCEPT
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Libera entrada epoptes server
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        source_port: 789
        table: filter
        jump: ACCEPT
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    # - name: Definir o valor do source com base no nome do host
    #   ansible.builtin.set_fact:
    #     epoptes_server: sje-lin-sidi-918545.maquinas.sj.ifsc.edu.br
    #   tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
    #   when: ansible_hostname.startswith("sj-lin-sidi")

    # - name: Definir o valor do source com base no nome do host
    #   ansible.builtin.set_fact:
    #     epoptes_server: 192.168.3.162
    #   tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
    #   when: ansible_hostname.startswith("debian12-")

    - name: Definir o valor do epoptes_server
      ansible.builtin.set_fact:
        epoptes_server: >
          {%- if ansible_hostname.startswith("sj-lin-sidi") -%}
            sje-lin-sidi-918545.maquinas.sj.ifsc.edu.br
          {%- elif ansible_hostname.startswith("sje-lin-redes") -%}
            sje-lin-redes-906284.maquinas.sj.ifsc.edu.br
          {%- elif ansible_hostname.startswith("sje-lin-prog") -%}
            sje-lin-prog-744523.maquinas.sj.ifsc.edu.br
          {%- elif ansible_hostname.startswith("sje-lin-cad1") -%}
            sje-lin-cad1-916082.maquinas.sj.ifsc.edu.br
          {%- elif ansible_hostname.startswith("sje-lin-cad2") -%}
            sje-lin-cad2-905476.maquinas.sj.ifsc.edu.br
          {%- elif ansible_hostname.startswith("sje-lin-cad3") -%}
            sje-lin-cad3-744517.maquinas.sj.ifsc.edu.br
          {%- elif ansible_hostname.startswith("sje-lin-info") -%}
            sje-lin-info-895203.maquinas.sj.ifsc.edu.br
          {%- elif ansible_hostname.startswith("sje-lin-mtrans") -%}
            sje-lin-mtrans-926158.maquinas.sj.ifsc.edu.br
          {%- else -%}
            "Não foi possível determinar o servidor epoptes. Por favor, verifique o nome do host."
          {%- endif -%}
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje

    - name: Limpa os caracteres do epoptes_server
      ansible.builtin.set_fact:
        epoptes_server: "{{ epoptes_server | trim }}"
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje

    - name: Libera toda conexao de entrada a partir do host do professor
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        source: "{{ epoptes_server }}"
        table: filter
        jump: ACCEPT
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Libera toda conexao de saída a partir do host do professor
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: "{{ epoptes_server }}"
        table: filter
        jump: ACCEPT
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Libera entrada ICMP
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{ item }}"
        ctstate:
          - NEW
          - ESTABLISHED
          - RELATED
        table: filter
        jump: ACCEPT
      loop:
        - ICMP
        - ICMPv6
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Libera saída ICMP
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: "{{ item }}"
        ctstate:
          - NEW
          - ESTABLISHED
          - RELATED
        table: filter
        jump: ACCEPT
      loop:
        - ICMP
        - ICMPv6
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Entrada ssh
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 22
        match:
          - conntrack
        ctstate:
          - NEW
          - ESTABLISHED
        table: filter
        jump: ACCEPT
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Saída ssh
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        source_port: 22
        match:
          - conntrack
        ctstate:
          - ESTABLISHED
        table: filter
        jump: ACCEPT
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    # - name: Libera license-server.sj.ifsc.edu.br
    #   ansible.builtin.iptables:
    #     chain: OUTPUT
    #     protocol: tcp
    #     destination: license-server.sj.ifsc.edu.br
    #     table: filter
    #     jump: ACCEPT
    #   tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
    #   when: ansible_os_family == 'Debian'

    - name: Libera wiki.sj.ifsc.edu.br
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: wiki.sj.ifsc.edu.br
        table: filter
        jump: ACCEPT
        action: insert
      tags: wiki
      when: ansible_os_family == 'Debian'

    - name: Libera sigaa.ifsc.edu.br
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: sigaa.ifsc.edu.br
        table: filter
        jump: ACCEPT
        action: insert
      tags: sigaa
      when: ansible_os_family == 'Debian'

    - name: Libera sig.ifsc.edu.br
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: sig.ifsc.edu.br
        table: filter
        jump: ACCEPT
        action: insert
      tags: sigaa
      when: ansible_os_family == 'Debian'

    - name: Libera moodle.ifsc.edu.br IPv4
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: "{{ item }}"
        table: filter
        jump: ACCEPT
        action: insert
      tags: moodle
      loop:
        - moodle.ifsc.edu.br
        - use.fontawesome.com
        - fonts.googleapis.com
        - fonts.gstatic.com
      when: ansible_os_family == 'Debian'

    - name: Libera moodle.ifsc.edu.br IPv6
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        destination: "{{ item }}"
        table: filter
        jump: ACCEPT
        action: insert
        ip_version: ipv6
      tags: moodle
      loop:
        - use.fontawesome.com
        - fonts.googleapis.com
        - fonts.gstatic.com
      when: ansible_os_family == 'Debian'

    - name: Libera para a faixa ip do campus SJE
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        ip_version: "{{ item.ip_version }}"
        destination: "{{ item.destination }}"
        table: filter
        jump: ACCEPT
        action: insert
      loop:
        - { ip_version: ipv4,
            destination: 191.36.8.0/21, }
        - { ip_version: ipv6,
            destination: 2804:1454:1004::/48, }
      tags: ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Libera para a faixa ip do IFSC
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: tcp
        ip_version: "{{ item.ip_version }}"
        destination: "{{ item.destination }}"
        table: filter
        jump: ACCEPT
        action: insert
      loop:
        - { ip_version: ipv4,
            destination: 191.36.0.0/17, }
        - { ip_version: ipv4,
            destination: 200.135.190.0/24, }
        - { ip_version: ipv6,
            destination: 2804:1454::/32, }
      tags: ifsc
      when: ansible_os_family == 'Debian'

    - name: Permite a entrada de conexões relacionadas
      ansible.builtin.iptables:
        chain: INPUT
        match:
          - conntrack
        ctstate:
          - ESTABLISHED
          - RELATED
        table: filter
        jump: ACCEPT
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Bloqueia entrada
      ansible.builtin.iptables:
        chain: INPUT
        table: filter
        ip_version: "{{ item }}"
        jump: DROP
      loop:
        - ipv4
        - ipv6
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Bloqueia saída
      ansible.builtin.iptables:
        chain: OUTPUT
        table: filter
        ip_version: "{{ item }}"
        jump: DROP
      loop:
        - ipv4
        - ipv6
      tags: wiki, moodle, sigaa, bloqueia, ifsc, ifsc-sje
      when: ansible_os_family == 'Debian'

    - name: Iptables flush filter
      ansible.builtin.iptables:
        ip_version: "{{ item }}"
        flush: true
      loop:
        - ipv4
        - ipv6
      tags: libera
      when: ansible_os_family == 'Debian'
