### configura o Unattended Upgrades
# https://wiki.debian.org/UnattendedUpgrades
# http://man7.org/linux/man-pages/man7/systemd.time.7.html

- name: Instala unattended-upgrades
  ansible.builtin.apt:
    pkg:
      - unattended-upgrades
  when: ansible_os_family == 'Debian'

- name: Define arquivo /etc/apt/apt.conf.d/50unattended-upgrades
  ansible.builtin.copy:
    content: |
      Unattended-Upgrade::Origins-Pattern {
        "o=*";
      };
      Unattended-Upgrade::AutoFixInterruptedDpkg "true";
      Unattended-Upgrade::MinimalSteps "true";
      Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Define arquivo /etc/apt/apt.conf.d/20auto-upgrades
  ansible.builtin.copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "1";
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Define download das atualizações - /lib/systemd/system/apt-daily.timer
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Daily apt download activities

      [Timer]
      OnCalendar=*-*-* 8,12,17:00
      RandomizedDelaySec=2h
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /lib/systemd/system/apt-daily.timer
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Define instalação das atualizações - /lib/systemd/system/apt-daily-upgrade.timer
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Daily apt upgrade and clean activities
      After=apt-daily.timer

      [Timer]
      OnCalendar=*-*-* 10,14,19:00
      RandomizedDelaySec=2h
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /lib/systemd/system/apt-daily-upgrade.timer
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_os_family == 'Debian'
