# Lista de pacotes: https://github.com/mathworks-ref-arch/container-images/blob/main/matlab-deps/r2024a/ubuntu22.04/base-dependencies.txt
- name: Instala pacotes necessários para o Matlab
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - libasound2
      - libc6
      - libcairo-gobject2
      - libcairo2
      - libcap2
      - libcups2
      - libdrm2
      - libfontconfig1
      - libgbm1
      - libgdk-pixbuf-2.0-0
      - libgl1
      - libglib2.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libice6
      - libltdl7
      - libnspr4
      - libnss3
      - libpam0g
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libsndfile1
      - libudev1
      - libuuid1
      - libwayland-client0
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxfixes3
      - libxft2
      - libxinerama1
      - libxrandr2
      - libxt6
      - libxtst6
      - libxxf86vm1
      - locales
      - locales-all
      - make
      - net-tools
      - procps
      - sudo
      - unzip
      - zlib1g
      - libncurses5
  when: ansible_distribution == 'Debian'

- name: Descompacta o arquivo de instalação do Matlab
  ansible.builtin.unarchive:
    src: http://ansiblefiles.sj.ifsc.edu.br/matlab_r2015a_modificado.tgz
    dest: /opt/
    creates: /opt/MATLAB/R2015a
    remote_src: true
    owner: root
    group: root
    mode: '0755'
  when: ansible_distribution == 'Debian'

- name: Cria link simbólico para o Matlab
  ansible.builtin.file:
    src: /opt/MATLAB/R2015a/bin/matlab
    dest: /usr/local/bin/matlab
    state: link
  when: ansible_distribution == 'Debian'
