# Lista de pacotes: https://github.com/mathworks-ref-arch/container-images/blob/main/matlab-deps/r2024a/ubuntu22.04/base-dependencies.txt
- name: Instala pacotes necessários para o Matlab
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - libasound2
      - libc6
      - libcairo-gobject2
      - libcairo2
      - libcap2
      - libcups2
      - libdrm2
      - libfontconfig1
      - libgbm1
      - libgdk-pixbuf-2.0-0
      - libgl1
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libice6
      - libltdl7
      - libnspr4
      - libnss3
      - libpam0g
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libsndfile1
      - libudev1
      - libuuid1
      - libwayland-client0
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxfixes3
      - libxft2
      - libxinerama1
      - libxrandr2
      - libxt6
      - libxtst6
      - libxxf86vm1
      - locales
      - locales-all
      - make
      - net-tools
      - procps
      - sudo
      - unzip
      - zlib1g
      - libncurses5
  when: ansible_distribution == 'Debian'

- name: Instala pacotes necessários para o Matlab - Debian 12
  ansible.builtin.apt:
    pkg:
      - libglib2.0-0
      - libgtk-3-0
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'bookworm'

- name: Instala pacotes necessários para o Matlab - Debian 13
  ansible.builtin.apt:
    pkg:
      - libglib2.0-0t64
      - libgtk-3-0t64
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'trixie'

- name: Descompacta o arquivo de instalação do Matlab
  ansible.builtin.unarchive:
    src: http://ansiblefiles.sj.ifsc.edu.br/matlab_r2015a_modificado.tgz
    dest: /opt/
    creates: /opt/matlab/R2015a
    remote_src: true
    owner: root
    group: root
    mode: '0755'
  when: ansible_distribution == 'Debian'

- name: Cria link simbólico para o Matlab
  ansible.builtin.file:
    src: /opt/matlab/R2015a/bin/matlab
    dest: /usr/local/bin/matlab
    state: link
  when: ansible_distribution == 'Debian'

- name: Cria arquivo para resolver problemas de OpenGL
  ansible.builtin.copy:
    content: |
      -Djogl.disable.openglarbcontext=1
    dest: /opt/matlab/R2015a/bin/glnxa64/java.opts
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == 'Debian'
  tags: matlab_correcao

- name: Apaga arquivos para resolver problema do simulink
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /opt/matlab/R2015a/bin/glnxa64/libfreetype.so.6
    - /opt/matlab/R2015a/bin/glnxa64/libfreetype.so.6.11.1
    - /opt/matlab/R2015a/sys/os/glnxa64/libfreetype.rights
    - /opt/matlab/R2015a/sys/os/glnxa64/libstdc++.so.6
  when: ansible_distribution == 'Debian'
  tags: matlab_correcao

- name: Copia log do Matlab
  ansible.builtin.copy:
    src: matlab_logo_preview.png
    dest: /opt/matlab/
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == 'Debian'

- name: Mantem o estado do arquivo /usr/share/applications/matlab2015a.desktop - Linux
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Version=1.0
      Encoding=UTF-8
      Type=Application
      Icon=/opt/matlab/matlab_logo_preview.png
      Name=Matlab 2015a
      Comment=Start MATLAB 2015a - The Language of Technical Computing
      Exec=/opt/matlab/R2015a/bin/matlab -desktop -nosplash
      Terminal=false
      Categories=Development;
    dest: /usr/share/applications/matlab2015a.desktop
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /usr/share/applications/matlab2015a.desktop - Linux
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Version=1.0
      Encoding=UTF-8
      Type=Application
      Icon=/opt/matlab/matlab_logo_preview.png
      Name=Matlab 2015a - Software OpenGL
      Comment=Start MATLAB 2015a - The Language of Technical Computing
      Exec=/opt/matlab/R2015a/bin/matlab -desktop -nosplash -softwareopengl
      Terminal=false
      Categories=Development;
    dest: /usr/share/applications/matlab2015a-softwareopengl.desktop
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'
