- name: Adicionar chave do repositório Dropbox
  ansible.builtin.get_url:
    url: https://linux.dropbox.com/fedora/rpm-public-key.asc
    dest: /etc/apt/keyrings/dropbox.asc
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório Dropbox - Linux Debian 12
  ansible.builtin.copy:
    content: "deb [arch=i386,amd64 signed-by=/etc/apt/keyrings/dropbox.asc] http://linux.dropbox.com/debian bookworm main"
    dest: /etc/apt/sources.list.d/dropbox.list
    owner: root
    group: root
    mode: '0644'
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')

- name: Adicionar repositório Dropbox - Linux Debian 13
  ansible.builtin.copy:
    content: "deb [arch=amd64] http://linux.dropbox.com/debian trixie main"
    dest: /etc/apt/sources.list.d/dropbox.list
    owner: root
    group: root
    mode: '0644'
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'trixie')

- name: Instalar o dropbox
  ansible.builtin.apt:
    name:
      - dropbox
    update_cache: true
  when: ansible_os_family == 'Debian'

# Windows
- name: Install Dropbox - Windows
  chocolatey.chocolatey.win_chocolatey:
    name: dropbox
  when: ansible_os_family == 'Windows'
