---

#Linux
# - name: Garantir que o snapd esteja instalado - Linux
#   ansible.builtin.apt:
#     state: latest
#     pkg: snapd
#   when: ansible_os_family == 'Debian'

# - name: Verifica versao do GLPI-agent  - Linux
#   ansible.builtin.shell: GET https://github.com/glpi-project/glpi-agent/releases |grep glpi-agent_ |grep snap |cut -d'/' -f8 |head -n1
#   register: versao_glpi
#   changed_when: False
#   when: ansible_os_family == 'Debian'

# - name: Baixar o snap do glpi v{{ versao_glpi.stdout }} - Linux
#   ansible.builtin.get_url:
#     url: 'https://github.com/glpi-project/glpi-agent/releases/download/{{ versao_glpi.stdout }}/glpi-agent_{{ versao_glpi.stdout }}_amd64.snap'
#     dest: '/var/GLPI-Agent-{{ versao_glpi.stdout }}_amd64.snap'
#   when: ansible_os_family == 'Debian'

# - name: Instala GPLI Agent via SNAP - Linux
#   ansible.builtin.command: snap install --classic --dangerous /var/GLPI-Agent-{{ versao_glpi.stdout }}_amd64.snap
#   args:
#     creates: /snap/glpi-agent
#   when: ansible_os_family == 'Debian'

- name: Instala GPLI Agent 1.4 - Linux
  ansible.builtin.apt:
    deb: https://github.com/glpi-project/glpi-agent/releases/download/1.4/glpi-agent_1.4-1_all.deb
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Setar GPLI Agent - Linux
  ansible.builtin.command: glpi-agent -s https://glpi.ifsc.edu.br/front/inventory.php
  # args:
  #   creates: /snap/glpi-agent
  when: ansible_os_family == 'Debian'

# Windows
###### Nao consigo remover um \r\n que aparece no final da requisicao
# - name: Verifica versao do GLPI Agent - Windows
#   # win_shell: "(((New-Object System.Net.WebClient).DownloadString('https://github.com/glpi-project/glpi-agent/releases') |findstr glpi-agent |findstr snap).substring(89,3) |select -first 1)"
#   win_shell: "((Invoke-WebRequest https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html -UseBasicParsing).Content |findstr .msi |findstr style).substring(41,3)"
#   register: versao_glpiwin
#   ignore_errors: True
#   changed_when: False
#   when: ansible_os_family == 'Windows'

- name: Baixar o instalador do GLPI Agent v1.4 - Windows
  win_get_url:
    url: 'https://github.com/glpi-project/glpi-agent/releases/download/1.4/GLPI-Agent-1.4-x64.msi'
    dest: 'C:\instaladores\GLPI-Agent-1.4-x64.msi'
    timeout: 120
  when: ansible_os_family == 'Windows'

- name: Instalar o GLPI Agent - Windows
  win_package:
    path: 'C:\instaladores\GLPI-Agent-1.4-x64.msi'
    arguments: '/quiet SERVER=https://glpi.ifsc.edu.br/front/inventory.php'
    product_id: '{E1BE6C18-6BF4-1014-844A-F1F114E3EA24}'
    state: present
  when: ansible_os_family == 'Windows'
