- name: Instala fusioninventory - Linux
  ansible.builtin.apt:
    pkg: fusioninventory-agent
  when: ansible_os_family == 'Debian'

- name: Setar GPLI Agent - Linux
  ansible.builtin.lineinfile:
    path: /etc/fusioninventory/agent.cfg
    state: present
    regexp: '^#server = http://server.domain.com/glpi/plugins/fusioninventory/'
    line: 'server = https://glpi.ifsc.edu.br/front/inventory.php'
  when: ansible_os_family == 'Debian'
  notify:
    - Restart fusioninventory

# Windows
###### Nao consigo remover um \r\n que aparece no final da requisicao
# - name: Verifica versao do GLPI Agent - Windows
#   # win_shell: "(((New-Object System.Net.WebClient).DownloadString('https://github.com/glpi-project/glpi-agent/releases') |findstr glpi-agent |findstr snap).substring(89,3) |select -first 1)"
#   win_shell: "((Invoke-WebRequest https://glpi-agent.readthedocs.io/en/latest/installation/windows-command-line.html -UseBasicParsing).Content |findstr .msi |findstr style).substring(41,3)"
#   register: versao_glpiwin
#   ignore_errors: True
#   changed_when: False
#   when: ansible_os_family == 'Windows'

- name: Baixar o instalador do GLPI Agent v1.4 - Windows
  win_get_url:
    url: 'https://github.com/glpi-project/glpi-agent/releases/download/1.4/GLPI-Agent-1.4-x64.msi'
    dest: 'C:\instaladores\GLPI-Agent-1.4-x64.msi'
    timeout: 120
  when: ansible_os_family == 'Windows'

- name: Instalar o GLPI Agent - Windows
  win_package:
    path: 'C:\instaladores\GLPI-Agent-1.4-x64.msi'
    arguments: '/quiet SERVER=https://glpi.ifsc.edu.br/front/inventory.php'
    product_id: '{E1BE6C18-6BF4-1014-844A-F1F114E3EA24}'
    state: present
  when: ansible_os_family == 'Windows'
