# Debian e Ubuntu
- name: Adicionar a chave para o x2goserver - Linux
  apt_key:
    keyserver: keys.gnupg.net
    id: E1F958385BFE2B6E
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

- name: Arquivo do source list x2goserver - Linux
  copy:
    src: x2go.list
    dest: /etc/apt/sources.list.d/x2go.list
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')
  notify:
    - update apt cache

- name: Instalar os pacotes x2go-keyring - Linux
  apt: name=x2go-keyring state=latest update_cache=yes
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

- name: Instalar pacotes para o x2goserver - Linux
  apt:
    state: latest
    pkg:
    - x2goserver
    - x2goserver-xsession
  when: ansible_os_family == 'Debian'
