#!/bin/bash

WAN=eth0
#LAB=redes
echo -n "Qual laboratório: "
read LAB

testa_ping(){
    target=${1}
    timeout 1 ping -q -i 0.2 -c2 ${target} > /dev/null 2>&1
    teste="$?"
    if [ ${teste} = "0" ] ; then
      ssh root@${target} "$(typeset -f ${comando}); ${comando}" 2> /dev/null
    fi
}

limpa(){
  cat <<EOF > /var/iptables-free
# Generated by iptables-save v1.6.0 on Mon Feb 11 16:04:53 2019
*filter
:INPUT ACCEPT [107:24295]
:OUTPUT ACCEPT [100:19398]
COMMIT
EOF
}

pagina(){
  cat <<EOF > /var/iptables-saved
# Generated by iptables-save v1.6.0 on Mon Feb 11 15:54:57 2019
*filter
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -d www.sj.ifsc.edu.br -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -d wiki.sj.ifsc.edu.br -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -d tele.sj.ifsc.edu.br -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT
EOF
}

bloqueia(){
  cat <<EOF > /var/iptables-saved
# Generated by iptables-save v1.6.0 on Mon Feb 11 15:54:57 2019
*filter
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT
EOF
}

quartus(){
cat <<EOF > /var/iptables-saved
# Generated by iptables-save v1.6.0 on Mon Feb 11 16:07:50 2019
*filter
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -d 191.36.8.3/32 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -d 172.18.110.2/32 -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT
EOF
}

if [ ${LAB} = "sidi" ] ; then
  ##Maquinas do SiDi
  maquinas=(703872 703873 703874 703875 703876 703877 703878 703879 703880 703881 703882 703883 703884 703885 744600 744603 744604 744605 744606 744609 756046 756047 756048 756049 756050)
elif [ ${LAB} = "prog" ] ; then
  ##Maquinas do prog
  maquinas=(38111 38125 744522 744523 744527 744531 744532 744534 744535 744537 744538 744601 744602 744607 756043 756045 756051 866459 866460 866461 866462 866463 866464 866465 866466)
elif [ ${LAB} = "redes" ] ; then
  ## Maquinas do redes
  maquinas=(38103 38106 38107 38109 38110 38114 38115 38116 38117 38118 38119 38120 38123 38126 38127 38128 38130 38131 38132 38135 38136 613025 710812 744530)
elif [ ${LAB} = "cad1" ] ; then
  ## Maquinas do cad1
  maquinas=(37247 38097 38108 38133 38310 38844 38854 565463 608618 6wkdxp1 744515 744517 744519 744526 744539 7nhdqn1 brg250fhqx brg250fhsc bskdxp1 clhdqn1 fskdxp1)
elif [ ${LAB} = "cad2" ] ; then
  ## Maquinas do cad2
  maquinas=(38841 38842 38847 38851 38852 710789 710801 710804 710805 710806 710809 710811 710817 710819 710823)
elif [ ${LAB} = "cad3" ] ; then
  ## Maquinas do cad3
  maquinas=(38096 38098 38099 38100 38101 38102 744389 744390 744391 744392 744394 744395 744397 744402 744403 744528 744536 756052 7vkdxp1 hskdxp1 jvkdxp1)
else
  echo "Não existe um laboratório chamado ${LAB}."
fi

if [ $# -ne 1 ];
    then
        echo "Sintaxe errada. Exemplo:"
        echo ".$0 (limpa|bloqueia)"
        exit
fi

# Testa se a maquina esta na rede e executa o comando do firewall
comando=${1}
for line in ${maquinas[@]}; do
    testa_ping sj-lin-${LAB}-${line}.maquinas.sj.ifsc.edu.br
done
