#!/bin/bash

copy_file(){
    target=${1}
    timeout 1 ping -q -i 0.2 -c2 ${target} > /dev/null 2>&1
    teste="$?"
    if [ ${teste} = "0" ] ; then
      ssh root@${target} "$(typeset -f libera); libera" 2> /dev/null
      ssh root@${target} "$(typeset -f ${comando}); ${comando}" 2> /dev/null
      echo "${target} bloqueada."
    else
      echo "Máquina ${target} não bloqueada."
    fi
}

libera(){
  echo "# Generated by iptables-save v1.6.0
*filter
:INPUT ACCEPT [107:24295]
:OUTPUT ACCEPT [100:19398]
COMMIT" |tee /var/iptables-saved |tee /var/ip6tables-saved
}

wiki(){
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -d www.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d wiki.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d tele.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d lic.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d vm-lan2.sj.ifsc.edu.br -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/iptables-saved
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -d www.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d wiki.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d tele.sj.ifsc.edu.br -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/ip6tables-saved
}

bloqueia(){
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -d lic.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d vm-lan2.sj.ifsc.edu.br -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/iptables-saved
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/ip6tables-saved
}

if [ $# -ne 1 ];
    then
        echo "Sintaxe errada. Exemplo:"
        echo ".$0 (libera|bloqueia|wiki)"
        exit
fi

maquinas=(703872 703873 703874 703875 703876 703877 703878 703879 703880 703881 703882 703883 703884 703885 744600 744603 744604 744605 744606 744609 756046 756047 756048 756049 756050)

# Testa se a maquina esta na rede e executa o comando do firewall
comando=${1}
for line in ${maquinas[@]}; do
   ssh root@${target} "iptables -F && ip6tables -F" 2> /dev/null
   copy_file sj-lin-sidi-${line}.maquinas.sj.ifsc.edu.br
   ssh root@${target} "iptables-restore < /var/iptables-saved && ip6tables-restore < /var/iptables-saved" 2> /dev/null
done
