#!/bin/bash

exec_cmd(){}
  # Testa se a maquina esta na rede e executa o comando do firewall
  maquinas=(38103 38106 38107 38109 38110 38114 38115 38116 38117 38118 38119 38120 38123 38126 38127 38128 38130 38131 38132 38135 38136 613025 710812)
  for line in ${maquinas[@]}; do
    ssh root@${target} "iptables -F && ip6tables -F" 2> /dev/null
    copy_file sj-lin-sidi-${line}.maquinas.sj.ifsc.edu.br
    ssh root@${target} "iptables-restore < /var/iptables-saved && ip6tables-restore < /var/iptables-saved" 2> /dev/null
  done
}

copy_file(){
  target=${1}
  timeout 1 ping -q -i 0.2 -c2 ${target} > /dev/null 2>&1
  teste="$?"
  if [ ${teste} = "0" ] ; then
    ssh root@${target} "$(typeset -f ${comando}); ${comando}" 2> /dev/null
    echo "Máquina ${target} OK."
  else
    echo "Máquina ${target} falhou na aplicação da regra."
  fi
}

libera(){
  echo "# Generated by iptables-save v1.6.0
*filter
:INPUT ACCEPT [107:24295]
:OUTPUT ACCEPT [100:19398]
COMMIT" |tee /var/iptables-saved |tee /var/ip6tables-saved
}

wiki(){
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -d www.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d wiki.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d tele.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d lic.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d vm-lan2.sj.ifsc.edu.br -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/iptables-saved
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -d www.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d wiki.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d tele.sj.ifsc.edu.br -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/ip6tables-saved
}

bloqueia(){
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -d lic.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d vm-lan2.sj.ifsc.edu.br -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/iptables-saved
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/ip6tables-saved
}

case ${1} in
  "libera")
    comando=${1}
    exec_cmd
    ;;
  "bloqueia")
    comando=${1}
    exec_cmd
    ;;
  "wiki")
    comando=${1}
    exec_cmd
    ;;
  *)
    echo "Sintaxe errada. Exemplo:"
    echo ".$0 (libera|bloqueia|wiki)"
    exit
esac
