#!/bin/bash

copy_file(){
    target=${1}
    timeout 1 ping -q -i 0.2 -c2 ${target} > /dev/null 2>&1
    teste="$?"
    if [ ${teste} = "0" ] ; then
      ssh root@${target} "$(typeset -f libera); libera" 2> /dev/null
      ssh root@${target} "$(typeset -f ${comando}); ${comando}" 2> /dev/null
    else
      echo "Máquina ${target} não bloqueada. Desligada ou sem rede."
    fi
}

libera(){
  echo "# Generated by iptables-save v1.6.0
*filter
:INPUT ACCEPT [107:24295]
:OUTPUT ACCEPT [100:19398]
COMMIT" |tee /var/iptables-saved |tee /var/ip6tables-saved
}

wiki(){
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -d www.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d wiki.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d tele.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d lic.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d vm-lan2.sj.ifsc.edu.br -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/iptables-saved
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -d www.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d wiki.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d tele.sj.ifsc.edu.br -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/ip6tables-saved
}

bloqueia(){
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -d lic.sj.ifsc.edu.br -j ACCEPT
-A OUTPUT -p tcp -d vm-lan2.sj.ifsc.edu.br -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/iptables-saved
  echo "# Generated by iptables-save v1.6.0
*filter
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -j DROP
COMMIT" | tee /var/ip6tables-saved
}

if [ $# -ne 1 ];
    then
        echo "Sintaxe errada. Exemplo:"
        echo ".$0 (libera|bloqueia|wiki)"
        exit
fi

maquinas=(38111 38125 744522 744527 744531 744532 744534 744535 744537 744538 744601 744602 744607 756043 756045 756051 866459 866460 866461 866462 866463 866464 866465 866466)

# Testa se a maquina esta na rede e executa o comando do firewall
comando=${1}
for line in ${maquinas[@]}; do
   ssh root@${target} "iptables -F && ip6tables -F" 2> /dev/null
   copy_file sj-lin-prog-${line}.maquinas.sj.ifsc.edu.br
   ssh root@${target} "iptables-restore < /var/iptables-saved && ip6tables-restore < /var/ip6tables-saved" 2> /dev/null
done
