- name: Adicionar a chave do repositório do TeamViewer
  apt_key:
    url: https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc
    state: present
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório TeamViewer
  apt_repository:
    repo: deb https://linux.teamviewer.com/deb stable main
  when: ansible_os_family == 'Debian'

- name: Instala TeamViewer
  apt:
    pkg:
    - teamviewer
  when: ansible_os_family == 'Debian'
