#### Linux

- name: Instala pacotes
  ansible.builtin.apt:
    pkg:
      - quota
      - libpam-modules
  when: ansible_os_family == 'Debian'

- name: Configura /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    after: 'ext4'
    before: "0"
    regexp: '^.*errors=remount-ro.*$'
    replace: '  defaults,usrquota,grpquota,errors=remount-ro  '
  when: ansible_os_family == 'Debian'

- name: Remount a mounted volume and append exec to the existing options
  ansible.posix.mount:
    path: /
    state: remounted
    opts: defaults,usrquota,grpquota,errors=remount-ro
  when: ansible_os_family == 'Debian'

- name: Configura /etc/pam.d/common-session
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-session
    line: 'session  required   pam_setquota.so bsoftlimit=10000000 bhardlimit=12000000 startuid=1002 enduid=0 fs=/'
    backup: true
    state: present
  when: ansible_os_family == 'Debian'

- name: Executar quotaon -ap e registrar a saída
  ansible.builtin.command: quotaon -ap
  register: quotaon_output
  ignore_errors: true
  when: ansible_os_family == 'Debian'
  tags: quotaon

- name: Exibir a saída do comando quotaon
  ansible.builtin.debug:
    var: quotaon_output.stdout_lines
  when: ansible_os_family == 'Debian'
  tags: quotaon

- name: Cria e ativa quotas e reinicia o sistema
  ansible.builtin.command: quotacheck -cuM /
  register: quotacheck_output
  when: "'user quota on / (/dev/sda1) is off' in quotaon_output.stdout_lines"
  tags: quotaon

- name: Reiniciar o sistema
  ansible.builtin.command: /sbin/reboot
  when: "'user quota on / (/dev/sda1) is off' in quotaon_output.stdout_lines"
  tags: quotaon
