#!/bin/bash

if [ $# -ne 2 ]; then
        echo "Uso: pesquisaODF CaminhoPesquisa TermoPesquisa"
        exit 1
fi

find $1 -name "*.od?" | while read file
do
        unzip -ca "$file" content.xml | grep -qli "$2"
        if [ $? -eq 0 ]; then
                echo "Termo encontrado em: " $file
        fi
done
