---

#Linux
- name: Instalar pacotes necessários e referentes ao dong-SDR - Linux
  ansible.builtin.apt:
    state: latest
    pkg:
    - git
    - cmake
    - build-essential
    - libusb-1.0-0-dev
  when: ansible_os_family == 'Debian'

- name: Baixa repositorio no git do osmocom
  ansible.builtin.git:
    repo: 'https://github.com/osmocom/rtl-sdr.git'
    dest: /opt/rtl-sdr
    clone: yes
    update: no
  when: ansible_os_family == 'Debian'

- name: Executa o make install
  community.general.make:
    chdir: /opt/rtl-sdr/build
    target: install
  become: yes
  changed_when: False
  when: ansible_os_family == 'Debian'

- name: Copia arquivo rules para o local certo - Linux
  ansible.builtin.copy:
    src: /opt/rtl-sdr/rtl-sdr.rules
    dest: /etc/udev/rules.d/
    remote_source: yes
  ignore_errors: True
  when: ansible_os_family == 'Debian'

- name: Adicionar o dvb_usb_rtl28xxu no blacklist - Linux
  community.general.kernel_blacklist:
    name: dvb_usb_rtl28xxu
    state: present
  ignore_errors: True
  when: ansible_os_family == 'Debian'

- name: Remove module dvb_usb_rtl28xxu do kernel - Linux
  community.general.modprobe:
    name: dvb_usb_rtl28xxu
    state: absent
  ignore_errors: True
  when: ansible_os_family == 'Debian'
