# Debian

- name: Instalar os pacotes para o qgis
  ansible.builtin.apt:
    pkg:
      - qgis
      - python3-qgis
      - qgis-plugin-grass
  when: ansible_os_family == 'Debian'

# Windows
- name: Install qgis - Windows
  chocolatey.chocolatey.win_chocolatey:
    name: qgis
    # state: latest
  when: ansible_os_family == 'Windows'
