# Debian e Ubuntu

- name: Instalar os pacotes para o qgis
  apt:
    state: latest
    pkg:
    - qgis
    - python-qgis
    - qgis-plugin-grass
  when: ansible_os_family == 'Debian'

  #Windows
- name: Install qgis - Windows
  win_chocolatey:
    name: qgis
    # state: latest
  when: ansible_os_family == 'Windows'
