- name: Verificando se tem o software do scanner epson instalado - Linux Debian
  ansible.builtin.stat:
    path: /opt/iscan-perfection-v330-bundle-2.30.4.x64.deb/installed
  register: result_epson
  changed_when: false
  failed_when: false
  when: ansible_os_family == 'Debian'

- name: Baixando e extraindo software scanner - Linux Debian
  ansible.builtin.unarchive:
    src: https://download2.ebz.epson.net/iscan/plugin/perfection-v330/deb/x64/iscan-perfection-v330-bundle-2.30.4.x64.deb.tar.gz
    dest: /opt
    creates: /opt/iscan-perfection-v330-bundle-2.30.4.x64.deb/installed
    remote_src: true
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family == 'Debian' and not result_epson.stat.exists

- name: Instala scanner perfection v330 - Linux Debian
  ansible.builtin.shell: /opt/iscan-perfection-v330-bundle-2.30.4.x64.deb/install.sh
  when: ansible_os_family == 'Debian' and not result_epson.stat.exists

- name: Cria arquivo de controle - Linux Debian
  ansible.builtin.file:
    path: /opt/iscan-perfection-v330-bundle-2.30.4.x64.deb/installed
    state: touch
    mode: '0755'
  when: ansible_os_family == 'Debian' and not result_epson.stat.exists
