- name: Adiciona chave do r-cran
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7
    dest: /etc/apt/trusted.gpg.d/cran-r.asc
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório r-cran - Linux Debian 12
  ansible.builtin.copy:
    content: |
      deb http://cloud.r-project.org/bin/linux/debian bookworm-cran40/
    dest: /etc/apt/sources.list.d/cran-r.list
    owner: root
    group: root
    mode: '0644'
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')

- name: Adicionar repositório r-cran - Linux Debian 13
  ansible.builtin.copy:
    content: |
      deb http://cloud.r-project.org/bin/linux/debian trixie-cran40/
    dest: /etc/apt/sources.list.d/cran-r.list
    owner: root
    group: root
    mode: '0644'
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'trixie')

- name: Instalar os pacotes para o r-project - Linux
  ansible.builtin.apt:
    pkg:
      - r-base
      - r-base-dev
      - libxml2-dev
      - libatlas3-base
      - r-cran-rjava
      - libjpeg62
  when: ansible_os_family == 'Debian'

#### Instalação do RStudio - Linux
- name: Instalar o RStudio - Linux
  ansible.builtin.apt:
    deb: http://ansiblefiles.sj.ifsc.edu.br/rstudio-2025.09.1-401-amd64.deb
  when: ansible_os_family == 'Debian'

# Windows
- name: Verifica versao do R
  ansible.windows.win_shell: "(choco search R.Project | findstr R.Project).substring(10,5)"
  register: versao_R
  ignore_errors: true
  changed_when: false
  when: ansible_os_family == 'Windows'

- name: Instalar o R versao {{ versao_R.stdout |trim}} - Windows
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ instala_r }}"
    state: latest
    ignore_checksums: true
  loop:
    - r.project
    - r.studio
  loop_control:
    loop_var: instala_r
  when: ansible_os_family == 'Windows'
  tags: rstudio

- name: Atalho para o r-project versao {{ versao_R.stdout | trim}} - Windows
  community.windows.win_shortcut:
    description: Atalho para o r-project
    src: '%ProgramFiles%\R\R-{{ versao_R.stdout |trim }}\bin\x64\Rgui.exe'
    dest: '%Public%\Desktop\R.lnk'
    icon: '%ProgramFiles%\R\R-{{ versao_R.stdout |trim }}\bin\x64\Rgui.exe,0'
    args: '--cd-to-userdocs'
    state: present
  when: ansible_os_family == 'Windows'

- name: Atalho para o RStudio - Windows
  community.windows.win_shortcut:
    description: Atalho para o RStudio
    src: '%ProgramFiles%\RStudio\bin\rstudio.exe'
    dest: '%Public%\Desktop\RStudio.lnk'
    state: present
  when: ansible_os_family == 'Windows'
