# Linux

- name: Adiciona apt key do r-cran
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório r-cran - Linux Debian 12
  ansible.builtin.apt_repository:
    repo: deb http://cloud.r-project.org/bin/linux/debian bookworm-cran40/
    filename: cran-r
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')

- name: Instalar os pacotes para o r-project - Linux
  ansible.builtin.apt:
    pkg:
      - r-base
      - r-base-dev
      - libxml2-dev
      - libatlas3-base
      - r-cran-rjava
      - libjpeg62
  when: ansible_os_family == 'Debian'


# # Bibliotecas Linux
# - name: Instalar bibliotecas para o r-studio - Linux
#   apt:
#   state: latest
#     pkg:
#     - r-cran-gdata
#     - r-cran-gmodels
#     - r-cran-gtools
#   when: ansible_os_family == 'Debian'

- name: Verifica versao do RWeka
  ansible.builtin.shell: GET https://cran.r-project.org/src/contrib |grep RWeka| cut -d'"' -f8| cut -d'"' -f1| head -n 1
  register: versao_rweka
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: Verifica versao do RWekajars
  ansible.builtin.shell: GET https://cran.r-project.org/src/contrib |grep RWekajars| cut -d'"' -f8| cut -d'"' -f1| head -n 1
  register: versao_rwekajars
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: Verifica versao do rJava
  ansible.builtin.shell: GET https://cran.r-project.org/src/contrib |grep rJava| cut -d'"' -f8| cut -d'"' -f1| head -n 1
  register: versao_rjava
  changed_when: false
  when: ansible_os_family == 'Debian'

# - name: Baixa Biblioteca RWeka e Rwekajars - Linux
#   ansible.builtin.get_url:
#     url: https://cran.r-project.org/src/contrib/{{ baixaweka }}
#     dest: /var/{{ baixaweka }}
#   loop:
#     - "{{ versao_rjava.stdout }}"
#     - "{{ versao_rwekajars.stdout }}"
#     - "{{ versao_rweka.stdout }}"
#   loop_control:
#     loop_var: baixaweka
#   when: ansible_os_family == 'Debian'

# - name: Instala Biblioteca RWeka e Rwekajars - Linux
#   ansible.builtin.command: /usr/bin/R CMD INSTALL /var/{{ instalaweka }}
#   args:
#     creates: /usr/local/lib/R/site-library/RWeka
#   loop:
#     - "{{ versao_rjava.stdout }}"
#     - "{{ versao_rwekajars.stdout }}"
#     - "{{ versao_rweka.stdout }}"
#   loop_control:
#     loop_var: instalaweka
#   when: ansible_os_family == 'Debian'

#### Instalação do RStudio - Linux
- name: Instalar o RStudio - Linux
  ansible.builtin.apt:
    deb: https://download1.rstudio.org/electron/jammy/amd64/rstudio-2024.12.1-563-amd64.deb
  when: ansible_os_family == 'Debian'

#Windows
- name: Verifica versao do R
  ansible.windows.win_shell: "(choco search R.Project | findstr R.Project).substring(10,5)"
  register: versao_R
  ignore_errors: true
  changed_when: false
  when: ansible_os_family == 'Windows'

- name: Instalar o R versao {{ versao_R.stdout |trim}} - Windows
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ instala_r }}"
    state: latest
    ignore_checksums: true
  loop:
    - r.project
    - r.studio
  loop_control:
    loop_var: instala_r
  when: ansible_os_family == 'Windows'
  tags: rstudio

- name: Atalho para o r-project versao {{ versao_R.stdout | trim}} - Windows
  community.windows.win_shortcut:
    description: Atalho para o r-project
    src: '%ProgramFiles%\R\R-{{ versao_R.stdout |trim }}\bin\x64\Rgui.exe'
    dest: '%Public%\Desktop\R.lnk'
    icon: '%ProgramFiles%\R\R-{{ versao_R.stdout |trim }}\bin\x64\Rgui.exe,0'
    args: '--cd-to-userdocs'
    state: present
  when: ansible_os_family == 'Windows'

- name: Atalho para o RStudio - Windows
  community.windows.win_shortcut:
    description: Atalho para o RStudio
    src: '%ProgramFiles%\RStudio\bin\rstudio.exe'
    dest: '%Public%\Desktop\RStudio.lnk'
    state: present
  when: ansible_os_family == 'Windows'
