---
### Role criado para adicionar todos os tipos de instaladores
### de pacotes diferentes do padrão e fora do convencional

#Linux

- name: Instalando gerenciadores de pacotes - Linux Debian 11
  apt:
    state: latest
    pkg:
    - flatpak
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Instalar flathub usando flatpak - Linux Debian 11
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  changed_when: False
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Instalar Logisim evolution - flatpak
  flatpak:
    name: com.github.reds.LogisimEvolution
    state: present
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')
