- name: Remove Intellij-IDEA softwares from flathub
  community.general.flatpak:
    name:
      - com.jetbrains.IntelliJ-IDEA-Ultimate
    state: absent
  when: ansible_os_family == 'Debian'

- name: Instala pacotes performance Android
  ansible.builtin.apt:
    name:
      - android-sdk-common
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
  when: ansible_os_family == 'Debian'

- name: Configura grupos secundários para aluno
  ansible.builtin.user:
    name: aluno
    groups: plugdev, libvirt, kvm
    append: true
  when: ansible_os_family == 'Debian'

- name: Baixa e instala intellij-idea-ultimate
  ansible.builtin.unarchive:
    src: http://ansiblefiles.sj.ifsc.edu.br/ideaIU-2025.1.4.tar.gz
    dest: /opt/
    remote_src: true
    creates: /opt/ideaIU/bin/idea
    owner: root
    group: root
    mode: '0755'
    extra_opts:
      - --transform
      - 's:^[^/]*:ideaIU:'
  when: ansible_os_family == 'Debian'

- name: Cria atalho do intellij na lista de aplicativos
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=Intellij IDEA
      Icon=/opt/ideaIU/bin/idea.png
      Exec="/opt/ideaIU/bin/idea" %f
      Comment=Capable and Ergonomic IDE for the Java Virtual Machine
      Categories=Development;IDE;
      Terminal=false
    dest: /usr/share/applications/intellij-IDEA.desktop
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Descomenta linha no arquivo /opt/ideaIU/bin/idea.properties
  ansible.builtin.lineinfile:
    path: /opt/ideaIU/bin/idea.properties
    regexp: "# idea.plugins.path=${idea.config.path}/plugins"
    line: "idea.plugins.path=${idea.config.path}/plugins"
  when: ansible_os_family == 'Debian'

- name: Cria diretórios
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: aluno
    group: aluno
    mode: '0755'
  loop:
    - /opt/aluno/JetBrains
    - /opt/aluno/Android
    - /home/aluno/.config/JetBrains/IntelliJIdea2025.1
  when: ansible_os_family == 'Debian'

- name: Cria links para Android e JetBrains
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
    - { src: /opt/aluno/Android,
        dest: /home/aluno/Android, }
    - { src: /opt/aluno/JetBrains,
        dest: /home/aluno/.config/JetBrains/IntelliJIdea2025.1/plugins, }
  when: ansible_os_family == 'Debian'

- name: Instala plugins do intellij
  become: true
  become_user: aluno
  ansible.builtin.command:
    cmd: /opt/ideaIU/bin/idea.sh installPlugins '{{ item }}'
  loop:
    - org.jetbrains.android
    - com.android.tools.design
    - androidx.compose.plugins.idea
  when: ansible_os_family == 'Debian'
