---

- name: Mantem o estado do arquivo /etc/init.d/apagaAluno.sh - Linux
  copy:
    src: apagaAluno.sh
    dest: /etc/init.d/apagaAluno.sh
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /lib/systemd/system/apagaAluno.service - Linux
  copy:
    src: apagaAluno.service
    dest: /lib/systemd/system/apagaAluno.service
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Aplica o daemon-reload e o enable no servico apagaAluno - Linux
  systemd:
    enabled: yes
    daemon_reload: yes
    name: apagaAluno
  when: ansible_os_family == 'Debian'

###################### Inicio senha_aluno

- name: Cria usuário aluno com a senha aluno
  user:
    name: aluno
    # groups: [vboxusers] #Nao tem o grupo ainda
    password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
    append: yes
  when: ansible_os_family == 'Debian'

###################### Fim do senha_aluno
