# Linux

- name: Desativa a hibernação
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: true
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target
  when: ansible_os_family == 'Debian'

- name: Tarefa para desligar computador - Linux
  ansible.builtin.cron:
    name: "desligamento"
    minute: "0"
    hour: "23"
    user: "root"
    job: "/sbin/poweroff"
    state: present
  when: ansible_os_family == 'Debian'

# Windows
- name: Tarefa para desligar os computadores as 23h - Windows
  community.windows.win_scheduled_task:
    name: desliga
    description: Desligar as 23h
    actions:
      - path: shutdown.exe
        arguments: -s -f -t 0
    triggers:
      - type: "daily"
        start_boundary: '23:00:00'
    username: SYSTEM
    state: present
    enabled: true
  when: ansible_os_family == 'Windows'

- name: Altera plano de energia para alto desempenho (não hiberna)
  community.windows.win_power_plan:
    name: alto desempenho
  when: ansible_os_family == 'Windows'
