# Debian 11
- name: Adiciona uma chave para o virtualbox - Debian 11
  ansible.builtin.apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Adicionar repositório para Virtualbox - Linux Debian 11
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bullseye contrib
    state: present
    filename: virtualbox.list
    update_cache: true
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Instalar os pacotes para o Virtualbox do buster - Linux Debian 11
  ansible.builtin.apt:
    pkg:
      - virtualbox-6.1
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Cria usuário aluno com a senha aluno
  ansible.builtin.user:
    name: aluno
    groups: [vboxusers]
    password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
    append: true
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

# Debian 12
- name: Remove /etc/apt/source.list.d/virtualbox.list.list
  ansible.builtin.file:
    state: absent
    path: /etc/apt/sources.list.d/virtualbox.list.list
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')

- name: Adiciona uma chave para o virtualbox - Debian 12
  ansible.builtin.apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
    keyring: /usr/share/keyrings/oracle-virtualbox-2016.gpg
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')

- name: Adicionar repositório para Virtualbox - Linux Debian 12
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian bookworm contrib
    state: present
    filename: virtualbox
    update_cache: true
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')

- name: Instalar os pacotes para o Virtualbox do buster - Linux Debian 12
  ansible.builtin.apt:
    pkg:
      - virtualbox-7.0
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')

- name: Adiciona aluno ao grupo vboxusers
  ansible.builtin.user:
    name: aluno
    groups: [vboxusers]
    password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
    append: true
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')
