# Debian 12
- name: Remove /etc/apt/source.list.d/virtualbox.list.list
  ansible.builtin.file:
    state: absent
    path: /etc/apt/sources.list.d/virtualbox.list.list
  when: (ansible_os_family == 'Debian' and (ansible_distribution_release == 'bookworm' or ansible_distribution_release == 'trixie'))

- name: Adiciona uma chave para o virtualbox - Debian 12
  ansible.builtin.get_url:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    dest: /etc/apt/trusted.gpg.d/oracle-virtualbox-2016.asc
    mode: '0644'
    owner: root
    group: root
  when: (ansible_os_family == 'Debian' and (ansible_distribution_release == 'bookworm' or ansible_distribution_release == 'trixie'))

- name: Adicionar repositório para Virtualbox - Linux Debian 12
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian bookworm contrib
    state: present
    filename: virtualbox
    update_cache: true
  when: (ansible_os_family == 'Debian' and (ansible_distribution_release == 'bookworm' or ansible_distribution_release == 'trixie'))

- name: Instalar os pacotes para o Virtualbox do buster - Linux Debian 12
  ansible.builtin.apt:
    pkg:
      - virtualbox-7.0
  when: (ansible_os_family == 'Debian' and (ansible_distribution_release == 'bookworm' or ansible_distribution_release == 'trixie'))

- name: Adiciona aluno ao grupo vboxusers
  ansible.builtin.user:
    name: aluno
    groups: [vboxusers]
    append: true
  when: (ansible_os_family == 'Debian' and (ansible_distribution_release == 'bookworm' or ansible_distribution_release == 'trixie'))

- name: Cria diretórios para o VirtualBox
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: '0777'
  loop:
    - /opt/vms/VirtualBox VMs
    - /opt/vms/.config/VirtualBox
  when: ansible_os_family == 'Debian'
