- name: Remove /etc/apt/source.list.d/virtualbox.list.list
  ansible.builtin.file:
    state: absent
    path: /etc/apt/sources.list.d/virtualbox.list.list
  when: ansible_os_family == 'Debian'

- name: Adiciona uma chave para o virtualbox
  ansible.builtin.get_url:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    dest: /etc/apt/trusted.gpg.d/oracle-virtualbox-2016.asc
    mode: '0644'
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório para Virtualbox
  ansible.builtin.copy:
    content: |
      deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/oracle-virtualbox-2016.asc] https://download.virtualbox.org/virtualbox/debian bookworm contrib
    dest: /etc/apt/sources.list.d/virtualbox.list
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm'

- name: Adicionar repositório para Virtualbox
  ansible.builtin.copy:
    content: |
      deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/oracle-virtualbox-2016.asc] https://download.virtualbox.org/virtualbox/debian trixie contrib
    dest: /etc/apt/sources.list.d/virtualbox.list
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian' and ansible_distribution_release == 'trixie'

- name: Instalar o Virtualbox
  ansible.builtin.apt:
    pkg:
      - virtualbox-7.1
    update_cache: true
  when: (ansible_os_family == 'Debian' and (ansible_distribution_release == 'bookworm' or ansible_distribution_release == 'trixie'))
