---
#Linux

### Remove os pacotes em conflito do owncloud-client. Deve ser executado de forma manual.

# - name: remove o Owncloud Client - Linux Debian
#   ansible.builtin.apt:
#     state: absent
#     purge: yes
#     autoclean: yes
#     default_release: Debian_9.0
#     pkg:
#     - ocqt5125-libsqlite0-dev
#     - owncloud-client
#     - owncloud-client-l10n
#   when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'stretch')

- name: remove a chave do reposit贸rio do owncloud-client - Linux Debian
  ansible.builtin.apt_key:
    id: 1B07204CD71B690D409F57D24ABE1AC7557BEFF9
    state: absent
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

- name: remove reposit贸rio owncloud - Linux Debian
  ansible.builtin.apt_repository:
    repo: deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/ /
    state: absent
    update_cache: yes
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

- name: Instala o Owncloud Client - Linux Debian Stretch
  ansible.builtin.apt:
    state: present
    default_release: stretch-backports
    pkg:
    - owncloud-client
    - owncloud-client-l10n
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'stretch')

- name: Instala o Owncloud Client - Linux Debian Buster
  ansible.builtin.apt:
    state: present
    pkg:
    - owncloud-client
    - owncloud-client-l10n
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'buster')

#### Debian 11
- name: Adicionar a chave do reposit贸rio do owncloud
  apt_key:
    url: https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Debian_11/Release.key
    state: present
  when: ansible_distribution_release == 'bullseye'

- name: Adicionar reposit贸rio owncloud - Linux Debian 11
  ansible.builtin.apt_repository:
    repo: 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Debian_11/ /'
    state: present
    update_cache: yes
  when: ansible_distribution_release == 'bullseye'

#Windows
- name: Install owncloud-client - Windows
  chocolatey.chocolatey.win_chocolatey:
    name: owncloud-client
    # state: latest
  when: ansible_os_family == 'Windows'
