---

- name: Alterar tempo de retry do dhcp no lab - Linux
  copy:
    src: dhclient.conf
    dest: /etc/dhcp/dhclient.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

###################### Inicio Adiciona no grupo dialout

# Permissao para gravar na placa
- name: Adiciona no grupo dialout
  user:
    name: "{{ add_dialout }}"
    groups: [dialout]
    append: yes
  loop:
    - aluno
    - mayara.sousa
    - arliones.hoeller
    - roberto.matos
    - elen
  loop_control:
    loop_var: add_dialout
  when: ansible_os_family == 'Debian'

###################### Fim Adiciona no grupo dialout

###################### Inicio Solicitado pelo Mello no chamado IFSC#2018060710000808 de 07/06/18

- name: Adiciona no grupo plugdev
  user:
    name: "{{ grupo_plugdev }}"
    groups: [plugdev]
    append: yes
  loop:
    - aluno
  loop_control:
    loop_var: grupo_plugdev
  when: ansible_os_family == 'Debian'

###################### Fim Solicitado pelo Mello no chamado

### Bau: Liberacao da porta paralela
# - name: Adiciona no grupo dialout
#   file:
#     path: /dev/parport0
#     mode: "a+rw"
#     state: file
#   when: ansible_os_family == 'Debian'

### Para resolver o problema da janela de informacao que ficava fundo amarelo com letra branca do chamado IFSC#2017082510000862
# - name: Remove arquivo Troll
#   file:
#     path: /home/aluno/.config/Trolltech.conf
#     state: absent
#   when: ansible_distribution == 'Ubuntu'

###################### Inicio Gerencia sudoers aluno

- name: Adiciona e modifica entrada do usuario aluno no sudoers - Linux
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^aluno '
    line: 'aluno ALL=(ALL) NOPASSWD: SETENV: /sbin/ethtool,/usr/local/netkit2/bin/tap.py,/sbin/ifconfig,/usr/sbin/iptraf,/usr/sbin/tcpdump,/sbin/route,/usr/local/netkit/bin/vclean,/usr/bin/minicom,/usr/sbin/brctl,/usr/sbin/traceroute,/usr/local/netkit/bin/manage_tuntap,/usr/bin/wireshark,/sbin/iwconfig,/sbin/iwlist,/sbin/iw,/etc/init.d/firewall.sh,/usr/bin/usb-creator-gtk,/sbin/dhclient,/usr/bin/MercurioIV_Linux_1.1.0.run,/etc/init.d/isc-dhcp-server,/etc/init.d/udev,/usr/bin/rpcgen,/sbin/rpcbind,/usr/sbin/rfkill'
    validate: '/usr/sbin/visudo -cf %s'
  when: ansible_os_family == 'Debian'

###################### Fim Gerencia sudoers aluno

###################### Inicio do ApagaAluno

- name: Mantem o estado do arquivo /etc/init.d/apagaAluno.sh - Linux
  copy:
    src: apagaAluno.sh
    dest: /etc/init.d/apagaAluno.sh
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /lib/systemd/system/apagaAluno.service - Linux
  copy:
    src: apagaAluno.service
    dest: /lib/systemd/system/apagaAluno.service
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Aplica o daemon-reload e o enable no servico apagaAluno - Linux
  systemd:
    enabled: yes
    daemon_reload: yes
    name: apagaAluno
  when: ansible_os_family == 'Debian'

###################### Fim do ApagaAluno

##################### Inicio adiciona arquitetura i386

- name: Check if i386 is enabled
  shell: dpkg --print-foreign-architectures | grep i386
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1
  when: ansible_os_family == 'Debian'

- name: Enable i386 architecture
  command: dpkg --add-architecture i386
  when: ansible_os_family == 'Debian' and result_i386_check.rc == 1

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian' and result_i386_check.rc == 1

##################### Fim adiciona arquitetura i386

###################### Inicio senha_aluno

- name: Cria usuário aluno com a senha aluno
  user:
    name: aluno
    # groups: [vboxusers] #Nao tem o grupo ainda
    password: $6$B5dpvoG43l67q0sx$r0LDKV2TgNItf/kYx/76l89ZN4LhP/ksYIxp.SSVGttHoSZXLSoB6Hkg2A6y7M7aFJ8zEuauf5kS/yA/P61kN1
    append: yes
  when: ansible_os_family == 'Debian'

###################### Fim do senha_aluno

###################### Inicio do atalhos_e_icones

- name: Mantem o estado do arquivo /usr/share/applications/quartus13.0sp1.desktop - Linux
  copy:
    src: quartus13.0sp1.desktop
    dest: /usr/share/applications/quartus13.0sp1.desktop
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

- name: Mantem o estado do arquivo /usr/share/applications/matlab2012b.desktop - Linux
  copy:
    src: matlab2012b.desktop
    dest: /usr/share/applications/matlab2012b.desktop
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

- name: Mantem o estado do arquivo /usr/share/applications/matlab2015a.desktop - Linux
  copy:
    src: matlab2015a.desktop
    dest: /usr/share/applications/matlab2015a.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

# Configuracao da variavel de licenca e biblioteca lib32
- name: Adicionar entrada MGLS_LICENSE_FILE export no /etc/security/pam_env.conf - Linux
  lineinfile:
    regexp: '^MGLS_LICENSE_FILE'
    path: /etc/security/pam_env.conf
    line: 'MGLS_LICENSE_FILE   DEFAULT=1800@license-server.sj.ifsc.edu.br'
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada LD_LIBRARY_PATH export no /etc/security/pam_env.conf - Linux
  lineinfile:
    regexp: '^LD_LIBRARY_PATH'
    path: /etc/security/pam_env.conf
    line: 'LD_LIBRARY_PATH     DEFAULT=/opt/altera/13.0sp1/lib32'
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada LM_LICENSE_FILE export no /etc/security/pam_env.conf - Linux
  lineinfile:
    regexp: '^LM_LICENSE_FILE'
    path: /etc/security/pam_env.conf
    line: 'LM_LICENSE_FILE     DEFAULT=1800@license-server.sj.ifsc.edu.br'
  when: ansible_os_family == 'Debian'

## Feito para resolver o chamado IFSC#2017062710000273 do Moecke:
- name: Mantem o estado do arquivo /usr/share/applications/modelsim10.1d.desktop - Linux
  copy:
    src: modelsim10.1d.desktop
    dest: /usr/share/applications/modelsim10.1d.desktop
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

# - name: Mantem o estado do arquivo /usr/share/applications/modelsim.png - Linux
#   copy:
#     src: modelsim.png
#     dest: /opt/altera/13.0sp1/modelsim_ae/modelsim.png
#     owner: root
#     group: root
#     mode: 0644
#   when: ansible_os_family == 'Debian'

# - name: Mantem o estado do arquivo /opt/altera/13.0sp1/modelsim_ae/vco - Linux
#   copy:
#     src: vco
#     dest: /opt/altera/13.0sp1/modelsim_ae/vco
#     owner: root
#     group: root
#     mode: 0555
#   when: ansible_os_family == 'Debian'

# - name: Cria um link do /opt/altera/13.0sp1/modelsim_ae/bin/vsim para ../vco - Linux
#   file:
#     src: /opt/altera/13.0sp1/modelsim_ae/vco
#     dest: /opt/altera/13.0sp1/modelsim_ae/bin/vsim
#     force: yes
#     state: link
#   when: ansible_os_family == 'Debian'

# - name: Cria um link do vsim no /usr/local/bin - Linux
#   file:
#     src: /opt/altera/13.0sp1/modelsim_ae/bin/vsim
#     dest: /usr/local/bin/vsim
#     state: link
#   when: ansible_os_family == 'Debian'

# - name: Cria um link do matlab15 no /usr/local/bin - Linux
#   file:
#     src: /opt/matlab/R2015a/bin/matlab
#     dest: /usr/local/bin/matlab15
#     state: link
#   when: ansible_os_family == 'Debian'

# - name: Cria um link do matlab12 no /usr/local/bin - Linux
#   file:
#     src: /opt/matlab/R2012b/bin/matlab
#     dest: /usr/local/bin/matlab12
#     state: link
#   when: ansible_os_family == 'Debian'

# - name: Cria um link do salve seus trabalhos aqui no home do aluno - Linux
#   file:
#     src: /media/aluno/trabalhos
#     dest: /home/aluno/trabalhos
#     owner: aluno
#     group: aluno
#     state: link
#     force: yes
#   when: ansible_os_family == 'Debian'

# Para solucionar problemas com Ctrl + C Ctrl + v no matlab
# Deixei comentado porque podemos modificar e deixar já no home do aluno
# - name: Mantem o estado do arquivo /home/aluno/.matlab/R2015a/matlab.prf - Linux
#   copy:
#     src: matlab.prf
#     dest: /home/aluno/.matlab/R2015a/matlab.prf
#     owner: aluno
#     group: aluno
#     mode: 0644
#   when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /home/aluno/.x2goclient - Linux
  copy:
    src: sessions
    dest: /home/aluno/.x2goclient/sessions
    owner: aluno
    group: aluno
    mode: 0644
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')
  tags:
    - packages

###################### Fim do atalhos_e_icones

###################### Início do NTP do Linux

- name: Inclui o role do NTP do Linux
  include_role:
    name: geerlingguy.ntp
  vars:
    ntp_timezone: America/Sao_Paulo
    ntp_manage_config: true
    ntp_servers:
      - "pool.ntp.br iburst"
      - "ntp.cais.rnp.br iburst"
      - "ntp.ufsc.br iburst"
  when: ansible_os_family == 'Debian'

###################### Fim do NTP do Linux

###################### Correcao Bug do xpdf pe do NTP do Linux

- name: Modifica o arquivo /usr/bin/xpdf - Linux
  copy:
    src: xpdf
    dest: /usr/bin/xpdf
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

###################### Fim do NTP do Linux

################# Copiar Chave pub Marcelo
- name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys do Marcelo - Linux
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'marcelo.id_rsa.pub') }}"
  when: ansible_os_family == 'Debian'

################# Copiar Chave pub Davi
- name: Adicionar entrada da chave pública no /root/.ssh/authorized_keys do Davi - Linux
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'davi.id_rsa.pub') }}"
  when: ansible_os_family == 'Debian'

###################### Inicio configuração SP1
- name: Cria o arquivo /etc/X11/Xsession.d/99SP1 - Linux
  copy:
    src: SP1
    dest: /etc/X11/Xsession.d/99SP1
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Cria o arquivo cat /etc/profile.d/99SP1.sh - Linux
  copy:
    src: SP1
    dest: /etc/profile.d/99SP1.sh
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada export no /home/aluno/.bashrc - Linux
  lineinfile:
    regexp: '^export PS1='
    path: /home/aluno/.bashrc
    line: 'export PS1="\u: \[\e[34m\]\W\[\e[m\]\\$ "'
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

###################### Fim configuração SP1

###################### Inicio configuração VIM
- name: Cria o arquivo /etc/vim/vimrc - Linux
  copy:
    src: vimrc
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

###################### Fim configuração VIM

##################### Inicio configuracao interfaces
- name: Mantem o estado do arquivo /etc/network/interfaces - Linux
  copy:
    content: |
      auto lo
      iface lo inet loopback
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  tags:
  - rede
  when: ansible_os_family == 'Debian'

- name: Define o backend do cliente dhcp - Linux
  copy:
    content: |
      [main]
      dhcp=dhclient
    dest: /etc/NetworkManager/conf.d/dhcp-client.conf
    owner: root
    group: root
    mode: 0644
  tags:
  - rede
  when: ansible_os_family == 'Debian'

- name: Altera parâmetro para que o dhclient não morra depois de pegar IPv6 e fique sem IPv4
  shell: nmcli connection modify Wired\ connection\ 1 ipv4.may-fail no
  changed_when: False
  tags:
  - rede
  when: ansible_os_family == 'Debian'

- name: Remove arquivo /etc/network/interfaces.d/eth0
  file:
    path: /etc/network/interfaces.d/eth0
    state: absent
  tags:
  - rede
  when: ansible_distribution == 'Debian'
##################### Fim configuracao interfaces

##################### Corrige problema no Matlab
## https://www.mathworks.com/matlabcentral/answers/260924-why-do-i-get-a-segmentation-fault-when-i-try-to-start-matlab-on-ubuntu-15-04-or-newer
- name: Remove arquivo /opt/matlab/R2015a/sys/os/glnxa64/libstdc++.so.6
  file:
    path: /opt/matlab/R2015a/sys/os/glnxa64/libstdc++.so.6
    state: absent
  when: ansible_distribution == 'Debian'
##################### Fim do corrige problema no Matlab

##################### Definir versao do java e javac padroes
# - name: Definir versão java padrão - Linux
#   alternatives:
#     name: java
#     path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
#   when: ansible_distribution == 'Debian'

# - name: Definir versão javac padrão - Linux
#   alternatives:
#     name: javac
#     path: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
#   when: ansible_distribution == 'Debian'
##################### Fim do Definir versao do java e javac padroes


##################### Cria e aplica SWAP

- name: Create swap file
  command: fallocate -l 4GB /swapfile
  args:
    creates: /swapfile
  when: ( ansible_distribution == 'Debian' and ansible_swaptotal_mb < 1 )

- name: Change swap file permissions
  file:
    path: /swapfile
    owner: root
    group: root
    mode: 0600
  when: ( ansible_distribution == 'Debian' and ansible_swaptotal_mb < 1 )

- name: Check swap file type
  command: file /swapfile
  register: swapfile
  when: ( ansible_distribution == 'Debian' and ansible_swaptotal_mb < 1 )

- name: Make swap file
  command: "mkswap /swapfile"
  when: ( ansible_distribution == 'Debian' and ansible_swaptotal_mb < 1 and swapfile.stdout.find('swap file') == -1 )

- name: Write swap entry in fstab
  mount:
    name: none
    src: /swapfile
    fstype: swap
    opts: sw
    passno: "0"
    dump: "0"
    state: present
  when: ( ansible_distribution == 'Debian' and ansible_swaptotal_mb < 1 )

- name: Mount swap
  command: "swapon /swapfile"
  when: (ansible_distribution == 'Debian' and ansible_swaptotal_mb < 1)

##################### Fim e aplica SWAP

###################### Inicio do arquivo para gravar FPGA no Quartus

- name: Copia o arquivo altera-usb-blaster.rules - Linux
  copy:
    src: altera-usb-blaster.rules
    dest: /etc/udev/rules.d/altera-usb-blaster.rules
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

##################### Fim do arquivo para gravar FPGA no Quartus

###################### Inicio da conf de atalho para abrir o terminal

- name: Cria o arquivo /etc/X11/Xsession.d/99AtalhoTerminal - Linux
  copy:
    content: |
      dconf write /org/mate/marco/global-keybindings/run-command-terminal "'<Primary><Alt>t'"

    dest: /etc/X11/Xsession.d/99AtalhoTerminal
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

##################### Fim da conf de atalho para abrir o terminal

###################### Inicio da configuracao do gdb chamado 2019032610000179

- name: Adicionar entrada SHELL no /etc/bash.bashrc  - Linux
  lineinfile:
    regexp: "^export SHELL="
    state: present
    path: /etc/bash.bashrc
    line: 'export SHELL=/bin/bash'
  when: ansible_os_family == 'Debian'

  #Descomentar o codigo abaixo caso o codigo acima nao funcionar
- name: Adicionar entrada SHELL export no /etc/security/pam_env.conf - Linux
  lineinfile:
    regexp: '^SHELL'
    path: /etc/security/pam_env.conf
    line: 'SHELL     DEFAULT=/bin/bash'
  when: ansible_os_family == 'Debian'

##################### Fim da configuracao do gdb chamado 2019032610000179

### WINDOWS ###

###################### Inicio pasta instaladores Windows
- name: Cria a pasta C:\instaladores\ - Windows
  win_file:
    path: C:\instaladores\
    state: directory
  when: ansible_os_family == 'Windows'
###################### Fim pasta instaladores Windows

###################### Inicio criacao de atalhos Windows
- name: Atalho para o D - Windows
  win_shortcut:
    description: Atalho para trabalhos
    src: 'D:\'
    dest: '%Public%\Desktop\SALVE SEUS TRABALHOS AQUI.lnk'
    icon: 'C:\Windows\system32\imageres.dll,24'
    state: present
  when: ansible_os_family == 'Windows'
  ###################### Fim criacao de atalhos Windows

###################### Início do NTP Windows
- name: Configura servidor NTP para o Windows 1
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
    name: "1"
    data: gps.ntp.br
  when: ansible_os_family == 'Windows'

- name: Configura servidor NTP para o Windows 2
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
    name: "2"
    data: a.st1.ntp.br
  when: ansible_os_family == 'Windows'

###################### Fim do NTP Windows

###################### Configuracao biblioteca do proteus, chamado IFSC#2020021310000059
- name: Copia os arquivos solicitados para o proteus - Windows
  win_copy:
    src: "{{ files_arduino }}"
    dest: C:\ProgramData\Labcenter Electronics\Proteus 8 Professional\LIBRARY\
  loop:
    - ARDUINO.IDX
    - ARDUINO.LIB
    - ArduinoTEP.IDX
    - ArduinoTEP.LIB
  loop_control:
    loop_var: files_arduino
  when: ansible_os_family == 'Windows'
  tags:
  - proteus

- name: Copia arquivo para a biblioteca do proteus - Windows
  win_copy:
    src: ARDUINO.LML
    dest: C:\ProgramData\Labcenter Electronics\Proteus 8 Professional\MODELS\
  when: ansible_os_family == 'Windows'
  tags:
  - proteus

###################### Início da configuracao do UTC Windows
- name: Configuracao no registro necessaria para UTC - Windows
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\TimeZoneInformation
    name: RealTimeIsUniversal
    data: "1"
    type: dword
  when: ansible_os_family == 'Windows'

#OBS: _dstoff desativa o horario de verao
- name: Setar timezone no Windows
  win_shell: |
    tzutil /s "E. South America Standard Time_dstoff"
  when: ansible_os_family == 'Windows'
#OBS2: na linha abaixo nao consegui adicionar o _dstoff
#   win_timezone:
#     timezone: E. South America Standard Time
#   when: ansible_os_family == 'Windows'
###################### Fim da configuracao do UTC Windows

###################### Inicio dos Includes

- name: Inclusão de roles config_padrao_labs
  include_role:
    name: "{{ roles_labs }}"
  loop:
    - sshd_config
    - auto_desligamento
    - openaudit
    - protege_win
    - chaves_ssh
    - firewall_labs
  loop_control:
    loop_var: roles_labs

###################### Fim dos Includes
