###################### Inicio do atalhos_e_icones

- name: Mantem o estado do arquivo /usr/share/applications/quartus13.0sp1.desktop - Linux
  ansible.builtin.copy:
    src: quartus13.0sp1.desktop
    dest: /usr/share/applications/quartus13.0sp1.desktop
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

- name: Mantem o estado do arquivo /usr/share/applications/matlab2012b.desktop - Linux
  ansible.builtin.copy:
    src: matlab2012b.desktop
    dest: /usr/share/applications/matlab2012b.desktop
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

- name: Mantem o estado do arquivo /usr/share/applications/matlab2015a.desktop - Linux
  ansible.builtin.copy:
    src: matlab2015a.desktop
    dest: /usr/share/applications/matlab2015a.desktop
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

# Configuracao da variavel de licenca e biblioteca lib32
- name: Adicionar entrada MGLS_LICENSE_FILE export no /etc/security/pam_env.conf - Linux
  ansible.builtin.lineinfile:
    regexp: '^MGLS_LICENSE_FILE'
    path: /etc/security/pam_env.conf
    line: 'MGLS_LICENSE_FILE   DEFAULT=1800@license-server.sj.ifsc.edu.br'
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada LD_LIBRARY_PATH export no /etc/security/pam_env.conf - Linux
  ansible.builtin.lineinfile:
    regexp: '^LD_LIBRARY_PATH'
    path: /etc/security/pam_env.conf
    line: 'LD_LIBRARY_PATH     DEFAULT=/opt/altera/13.0sp1/lib32'
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada LM_LICENSE_FILE export no /etc/security/pam_env.conf - Linux
  ansible.builtin.lineinfile:
    regexp: '^LM_LICENSE_FILE'
    path: /etc/security/pam_env.conf
    line: 'LM_LICENSE_FILE     DEFAULT=1800@license-server.sj.ifsc.edu.br'
  when: ansible_os_family == 'Debian'

## Feito para resolver o chamado IFSC#2017062710000273 do Moecke:
- name: Mantem o estado do arquivo /usr/share/applications/modelsim10.1d.desktop - Linux
  ansible.builtin.copy:
    src: modelsim10.1d.desktop
    dest: /usr/share/applications/modelsim10.1d.desktop
    owner: root
    group: root
    mode: 0644
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')


# - name: Mantem o estado do arquivo /usr/share/applications/modelsim.png - Linux
#   copy:
#     src: modelsim.png
#     dest: /opt/altera/13.0sp1/modelsim_ae/modelsim.png
#     owner: root
#     group: root
#     mode: 0644
#   when: ansible_os_family == 'Debian'

# - name: Mantem o estado do arquivo /opt/altera/13.0sp1/modelsim_ae/vco - Linux
#   copy:
#     src: vco
#     dest: /opt/altera/13.0sp1/modelsim_ae/vco
#     owner: root
#     group: root
#     mode: 0555
#   when: ansible_os_family == 'Debian'

# - name: Cria um link do /opt/altera/13.0sp1/modelsim_ae/bin/vsim para ../vco - Linux
#   file:
#     src: /opt/altera/13.0sp1/modelsim_ae/vco
#     dest: /opt/altera/13.0sp1/modelsim_ae/bin/vsim
#     force: yes
#     state: link
#   when: ansible_os_family == 'Debian'

# - name: Cria um link do vsim no /usr/local/bin - Linux
#   file:
#     src: /opt/altera/13.0sp1/modelsim_ae/bin/vsim
#     dest: /usr/local/bin/vsim
#     state: link
#   when: ansible_os_family == 'Debian'

# - name: Cria um link do matlab15 no /usr/local/bin - Linux
#   file:
#     src: /opt/matlab/R2015a/bin/matlab
#     dest: /usr/local/bin/matlab15
#     state: link
#   when: ansible_os_family == 'Debian'

# - name: Cria um link do matlab12 no /usr/local/bin - Linux
#   file:
#     src: /opt/matlab/R2012b/bin/matlab
#     dest: /usr/local/bin/matlab12
#     state: link
#   when: ansible_os_family == 'Debian'

# - name: Cria um link do salve seus trabalhos aqui no home do aluno - Linux
#   file:
#     src: /media/aluno/trabalhos
#     dest: /home/aluno/trabalhos
#     owner: aluno
#     group: aluno
#     state: link
#     force: yes
#   when: ansible_os_family == 'Debian'

####### Corrigir problema moecke IFSC#2023032810000711
- name: Solucao de contorno criado pelo joao
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Configurar jtag

      [Service]
      Type=oneshot
      ExecStart=pkill -f jtagd -9 ; /opt/altera/intelFPGA/20.1/quartus/bin/jtagd --user-start ; /opt/altera/intelFPGA/20.1/quartus/bin/jtagconfig

      [Install]
      WantedBy=basic.target
    dest: /lib/systemd/system/jtagd.service
    owner: root
    group: root
    mode: 0644
  tags: jtag
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Aplica o daemon-reload e o enable do script para correcao do quartus - Linux
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: true
    name: jtagd
  tags: jtag
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

# Para solucionar problemas com Ctrl + C Ctrl + v no matlab
# Deixei comentado porque podemos modificar e deixar já no home do aluno
# - name: Mantem o estado do arquivo /home/aluno/.matlab/R2015a/matlab.prf - Linux
#   copy:
#     src: matlab.prf
#     dest: /home/aluno/.matlab/R2015a/matlab.prf
#     owner: aluno
#     group: aluno
#     mode: 0644
#   when: ansible_os_family == 'Debian'

- name: Mantem o estado do arquivo /home/aluno/.x2goclient - Linux
  ansible.builtin.copy:
    src: sessions
    dest: /home/aluno/.x2goclient/sessions
    owner: aluno
    group: aluno
    mode: 0644
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')
  tags:
    - packages

###################### Fim do atalhos_e_icones

###################### Início do NTP do Linux

- name: Inclui o role do NTP do Linux
  ansible.builtin.include_role:
    name: geerlingguy.ntp
  vars:
    ntp_timezone: America/Sao_Paulo
    ntp_manage_config: true
    ntp_servers:
      - "pool.ntp.br iburst"
      - "ntp.cais.rnp.br iburst"
      - "ntp.ufsc.br iburst"
  when: ansible_os_family == 'Debian'

###################### Fim do NTP do Linux

- name: Adicionar entrada export no /home/aluno/.bashrc - Linux
  ansible.builtin.lineinfile:
    regexp: '^export PS1='
    path: /home/aluno/.bashrc
    line: 'export PS1="\u: \[\e[34m\]\W\[\e[m\]\\$ "'
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

###################### Fim configuração SP1

###################### Inicio configuração VIM
- name: Cria o arquivo /etc/vim/vimrc - Linux
  ansible.builtin.copy:
    src: vimrc
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

###################### Fim configuração VIM

##################### Fim configuracao interfaces

##################### Corrige problema no Matlab
## https://www.mathworks.com/matlabcentral/answers/260924-why-do-i-get-a-segmentation-fault-when-i-try-to-start-matlab-on-ubuntu-15-04-or-newer
- name: Remove arquivo /opt/matlab/R2015a/sys/os/glnxa64/libstdc++.so.6
  ansible.builtin.file:
    path: /opt/matlab/R2015a/sys/os/glnxa64/libstdc++.so.6
    state: absent
  when: ansible_distribution == 'Debian'
##################### Fim do corrige problema no Matlab

###################### Inicio do arquivo para gravar FPGA no Quartus

- name: Copia o arquivo altera-usb-blaster.rules - Linux
  ansible.builtin.copy:
    src: altera-usb-blaster.rules
    dest: /etc/udev/rules.d/altera-usb-blaster.rules
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

### WINDOWS ###

###################### Inicio pasta instaladores Windows
- name: Cria a pasta C:\instaladores\ - Windows
  ansible.windows.win_file:
    path: C:\instaladores\
    state: directory
  when: ansible_os_family == 'Windows'
###################### Fim pasta instaladores Windows

###################### Inicio criacao de atalhos Windows
- name: Atalho para o D - Windows
  community.windows.win_shortcut:
    description: Atalho para trabalhos
    src: 'D:\'
    dest: '%Public%\Desktop\SALVE SEUS TRABALHOS AQUI.lnk'
    icon: 'C:\Windows\system32\imageres.dll,24'
    state: present
  when: ansible_os_family == 'Windows'
  ###################### Fim criacao de atalhos Windows

###################### Início do NTP Windows
- name: Configura servidor NTP para o Windows 1
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
    name: "1"
    data: gps.ntp.br
  when: ansible_os_family == 'Windows'

- name: Configura servidor NTP para o Windows 2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers
    name: "2"
    data: a.st1.ntp.br
  when: ansible_os_family == 'Windows'

###################### Fim do NTP Windows

###################### Configuracao biblioteca do proteus, chamado IFSC#2020021310000059
- name: Copia os arquivos solicitados para o proteus - Windows
  ansible.windows.win_copy:
    src: "{{ files_arduino }}"
    dest: C:\ProgramData\Labcenter Electronics\Proteus 8 Professional\LIBRARY\
  loop:
    - ARDUINO.IDX
    - ARDUINO.LIB
    - ArduinoTEP.IDX
    - ArduinoTEP.LIB
  loop_control:
    loop_var: files_arduino
  when: ansible_os_family == 'Windows'
  tags:
  - proteus

- name: Copia arquivo para a biblioteca do proteus - Windows
  ansible.windows.win_copy:
    src: ARDUINO.LML
    dest: C:\ProgramData\Labcenter Electronics\Proteus 8 Professional\MODELS\
  when: ansible_os_family == 'Windows'
  tags:
  - proteus

###################### Início da configuracao do UTC Windows
- name: Configuracao no registro necessaria para UTC - Windows
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\TimeZoneInformation
    name: RealTimeIsUniversal
    data: "1"
    type: dword
  when: ansible_os_family == 'Windows'

#OBS: _dstoff desativa o horario de verao
- name: Setar timezone no Windows
  ansible.windows.win_shell: |
    tzutil /s "E. South America Standard Time_dstoff"
  when: ansible_os_family == 'Windows'
#OBS2: na linha abaixo nao consegui adicionar o _dstoff
#   win_timezone:
#     timezone: E. South America Standard Time
#   when: ansible_os_family == 'Windows'
###################### Fim da configuracao do UTC Windows

###################### Inicio dos Includes

- name: Inclusão de roles config_padrao_labs
  ansible.builtin.include_role:
    name: "{{ roles_labs }}"
  loop:
    - sshd_config
    - auto_desligamento
    - openaudit
    - protege_win
    - chaves_ssh
    - firewall_labs
  loop_control:
    loop_var: roles_labs

###################### Fim dos Includes
