- name: Enable i386 architecture
  command: dpkg --add-architecture i386
  when: ansible_os_family == 'Debian'

- name: Instalar pacotes
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - abntex
      - android-tools-adb
      - apt-transport-https
      - as31
      - audacity
      - avahi-daemon
      - avahi-utils
      - avarice
      - avrdude
      - avr-libc
      - binutils-avr
      - chrony
      - chrpath
      - cmake
      - cutecom
      - dia
      - diffstat
      - distcc
      - distccmon-gnome
      - dnsutils
      - ethtool
      - figlet
      - firmware-amd-graphics
      - firmware-ath9k-htc
      - firmware-atheros
      - firmware-linux
      - firmware-misc-nonfree
      - firmware-realtek
      - fish
      - flameshot
      - fping
      - fritzing
      - gcc-arm-none-eabi
      - gcc-avr
      - gdb
      - gdb-avr
      - geany
      - gedit
      - gimp
      - git
      - glade
      - gnupg
      - google-chrome-stable
      - graphviz
      - htop
      - inkscape
      - ipcalc
      - iperf
      - ipython3
      - kalzium
      - kdenlive
      - kicad
      - kolourpaint
      - konsole
      - latexila
      - lib32z1
      - libasound2
      - libbz2-1.0:i386
      - libc6-dev-i386
      - libc6:i386
      - libfontconfig1:i386
      - libfreetype6:i386
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgtk2.0-0:i386
      - libncurses5
      - libncurses5:i386
      - libpng16-16:i386
      - libreoffice
      - libreoffice-l10n-pt-br
      - libsm6:i386
      - libstdc++6:i386
      - libxext6:i386
      - libxft2
      - libxft2:i386
      - libxi6:i386
      - libxrender1:i386
      - libxtst6:i386
      - libzmq3-dev
      - linux-headers-{{ ansible_kernel }}
      - logisim
      - ltrace
      - mariadb-client
      - mate-applet-brisk-menu
      - maven
      - mcu8051ide
      - minicom
      - mosquitto-clients
      - net-tools
      - nmap
      - nodejs
      - ntfs-3g
      - okular
      - pcaputils
      - pdfsam
      - python3
      - python3-dev
      - python3-pip
      - python3-tk
      - python3-venv
      - qalc
      - rabbitmq-server
      - resolvconf
      - rfkill
      - snapd
      - snmp-mibs-downloader
      - sqlite3
      - sqlitebrowser
      - strace
      - subversion
      - swig
      - tcpdump
      - texlive-extra-utils
      - texlive-lang-portuguese
      - traceroute
      - tree
      - ttf-ancient-fonts
      - twinkle
      - u-boot-tools
      - unrar
      - uuid-dev
      - valgrind
      - vim
      - vlc
      - vokoscreen
      - whois
      - wireless-tools
      - wxmaxima
      - x2goclient
      - xournal
      - xpdf
      - xterm
  when: ansible_os_family == 'Debian'

- name: Remover programas  - Linux
  ansible.builtin.apt:
    state: absent
    pkg:
      - transmission
      - transmission-common
      - zoiper5
  when: ansible_os_family == 'Debian'

# Windows --------------------------------------------------------------------------------------------------------------
- name: Install multiple packages
  win_chocolatey:
    name:
      - googlechrome
      - jre8
      - firefox
      - 7zip
      - vlc
      - cutepdf
      - adobereader
      - putty
      - librecad
      - cadconverter
    state: present
  when: ansible_os_family == 'Windows'
