# Linux --------------------------------------------------------------------------------------------------------------

- name: Install a .deb Google Chrome - Linux Debian
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: ansible_os_family == 'Debian'

- name: Install a .deb GBStudio - Linux Debian
  apt:
    deb: https://github.com/chrismaltby/gb-studio/releases/download/v1.1.0/gb-studio_1.1.0_amd64.deb
  when: ansible_os_family == 'Debian'

- name: Instalar pacotes GUI ou "conhecidos" padroes de laboratorios - Linux
  apt:
    state: latest
    pkg:
    - apt-transport-https
    - geany
    - audacity
    - gimp
    - inkscape
    - latexila
    - xournal
    - abntex
    - fritzing
    - kalzium
    - kdenlive
    - kicad
    - kolourpaint4
    - konsole
    - gedit
    - okular
    - mcu8051ide
    - vlc
    - x2goclient
    - xpdf
    - libreoffice
    - libreoffice-l10n-pt-br
    - google-chrome-stable
    - pdfsam
    - pdfshuffler
    - mate-applet-brisk-menu
    - dia
    - vokoscreen
  when: ansible_os_family == 'Debian'

- name: Instalar pacotes GUI ou "conhecidos" padroes de laboratorios - Debian 10
  apt:
    state: latest
    pkg:
    - unrar
    - qalculate
    - dconf-tools
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'buster')

- name: Instalar pacotes GUI ou "conhecidos" padroes de laboratorios - Debian 11
  apt:
    state: latest
    pkg:
    - qalc
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Instalar pacotes de ferramentas "conhecidas" padroes de laboratorios - Linux
  apt:
    state: latest
    pkg:
    - unrar-free
    - xterm
    - ethtool
    - minicom
    - nmap
    - ntfs-3g
    - iperf
    - ipcalc
    - tcpdump
    - snmp-mibs-downloader
    - cutecom
    - gdb
    - ipython3
    - git
    - logisim
    - mosquitto-clients
    - nemiver
    - nodejs
    - vim
    - whois
    - wxmaxima
    - traceroute
    - tree
    - u-boot-tools
    - uuid-dev
    - resolvconf
    - spyder3
    - subversion
    - as31
    - chrpath
    - diffstat
    - dnsutils
    - fish
    - g++-arm-linux-gnueabi
    - gcc-arm-linux-gnueabi
    - gcc-arm-none-eabi
    - glade
    - gnupg
    - swig
    - texlive-extra-utils
    - texlive-lang-portuguese
    - python3-pip
    - htop
    - firmware-amd-graphics
    - firmware-misc-nonfree
    - firmware-linux
    - net-tools
    - fping
    - libpcre++-dev
    - python3-tk
    - ntpdate
    - avahi-daemon
    - graphviz
    - avahi-utils
    - wireless-tools
    - pcaputils
    - rfkill
    - strace
    - ltrace
    - twinkle
  when: ansible_os_family == 'Debian'

- name: Instalar pacotes de ferramentas "conhecidas" padroes de laboratorios - Debian 10
  apt:
    state: latest
    pkg:
    - mysql-client
    - python-rope
    - gir1.2-appindicator3-0.1
    - linux-headers-{{ ansible_kernel }}
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'buster')


- name: Instalar lista de pacotes pedida pelo Roberto de Matos Chamado IFSC#2019030810001087 - Linux
  apt:
    state: latest
    pkg:
    - binutils-avr
    - gcc-avr
    - gdb-avr
    - avr-libc
    # - simulavr #incompativel com debian 11
    - avrdude
    - avarice
  when: ansible_os_family == 'Debian'

- name: Instalar lista de pacotes pedida pelo Emerson Mello - Linux
  apt:
    state: latest
    pkg:
    - gradle
    - sqlite3
    - sqlitebrowser
    - rabbitmq-server
    # - python-virtualenv #incompativel com debian 11
    - maven
    # - mysql-workbench #incompativel com debian 11
    - python-dev
    # - python-pip #incompativel com debian 11
    - python3
    - python3-dev
    - libzmq3-dev
    - distcc
    - distccmon-gnome
    - ttf-ancient-fonts
    - android-tools-adb
    - python3-venv
    - figlet
  when: ansible_os_family == 'Debian'


# # java
- name: Instalar os pacotes  Java openjdk - Linux
  apt:
    state: latest
    pkg:
    - openjdk-11-doc
    - openjdk-11-jdk
    - openjdk-11-jre
    # - openjdk-8-doc #incompativel com debian 11
    # - openjdk-8-jdk #incompativel com debian 11
    # - openjdk-8-jre #incompativel com debian 11
    - default-jre
    - default-jdk
  when: ansible_os_family == 'Debian'


# - name: Instalar lista de pacotes pedida pelo Arliones - Linux
#   apt: name={{ packages }} state=latest
#   vars:
#     packages:
#     - cmake
#     - pkg-config
#     - libavcodec-dev
#     - libavformat-dev
#     - libswscale-dev
#     - python-numpy
#     - libtbb2
#     - libtbb-dev
#     - libjpeg-dev
#     - libjasper-dev
#     - libdc1394-22-dev
#     - libopencv-*
#     - qemu-system-x86
#     - qemu-utils
#     - qemu-common
#     - libxt6:i386
#     - libdbus-glib-1-2:i386
#     - libasound2:i386
#     - libxpm4:i386
#     - libusb-0.1-4:i386
#   when: ansible_os_family == 'Debian'

# - name: Instalar lista de pacotes pedida pelo Arliones - Linux
#   apt: name={{ packages }} state=latest
#   vars:
#     packages:
#     - libcppunit-dev
#     - cxxtest
#     - libcunit1
#     - libcunit1-dev
#   when: ansible_os_family == 'Debian'

- name: Instala flask com python pip  - Linux
  pip:
    state: latest
    name:
      - flask
      - flask-httpauth
  when: ansible_os_family == 'Debian'

### Inicio pacotes necessarios para o Quartus

- name: Instalar lista de pacotes necessarios para o quartus no Debian - Linux
  apt:
    state: latest
    pkg:
    - libbz2-1.0:i386
    - libsm6:i386
    - libc6:i386
    - libpng16-16:i386
    - libncurses5:i386
    - libstdc++6:i386
    - libxft2:i386
    - libxext6:i386
    - lib32z1
    - libxrender1:i386
    - libfreetype6:i386
    - libfontconfig1:i386
  when: (ansible_os_family == 'Debian' and ansible_distribution_release != 'bullseye')

- name: Instalar lista de pacotes necessarios para o quartus no Debian - Debian 11
  apt:
    state: latest
    pkg:
    - lib32z1
    - libc6-dev-i386
    - libc6:i386
    - libfontconfig1:i386
    - libfreetype6:i386
    - libgtk2.0-0:i386
    - libncurses5:i386
    - libsm6:i386
    - libstdc++6:i386
    - libxext6:i386
    - libxft2
    - libxft2:i386
    - libxi6:i386
    - libxrender1:i386
    - libxtst6:i386
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

# - name: Install a .deb libpng12:i386 - Linux Debian
#   apt:
#     deb: http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_i386.deb
#   when: ansible_os_family == 'Debian'

# - name: Install a .deb libpng12 - Linux Debian
#   apt:
#     deb: http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb
#   when: ansible_os_family == 'Debian'

- name: Instalar lista de pacotes necessarios para o Matlab no Debian - Linux
  apt:
    state: latest
    pkg:
    - libglu1-mesa
    - libasound2
    - libgl1-mesa-dri
  when: ansible_os_family == 'Debian'

### Fim pacotes necessarios para o Quartus

### Comentado pois não tem mais o repositorio
# - name: Instalar dependência para cmake atualizado do stretch-backports
#   apt:
#     default_release: stretch-backports-sloppy
#     state: latest
#     pkg:
#     - libarchive13
#   when: ansible_os_family == 'Debian'

# - name: Instalar pacotes do cmake atualizado do stretch-backports
#   apt:
#     default_release: stretch-backports
#     state: latest
#     pkg:
#     - cmake
#   when: ansible_os_family == 'Debian'

- name: Remover programas  - Linux
  apt:
    state: absent
    pkg:
    - transmission
    - transmission-common
    - zoiper5
  when: ansible_os_family == 'Debian'

# Windows --------------------------------------------------------------------------------------------------------------
- name: Instalar pacotes padroes laboratorios - Windows
  win_chocolatey: name={{ pkgs_win }} # state=latest timeout=9000
  loop:
  - googlechrome
  - jre8
  - firefox
  - 7zip
  - vlc
  - cutepdf
  - adobereader
  - putty
  - adobeair
  - librecad
  - cadconverter
  - subtitleworkshop
  loop_control:
    loop_var: pkgs_win
  when: ansible_os_family == 'Windows'

- name: Instalar o microsoftsecurityessentials - Windows 7
  win_chocolatey:
    name: microsoftsecurityessentials
    # version: latest
  when: (ansible_os_family == 'Windows' and ansible_os_name == 'Microsoft Windows 7 Professional')

# - name: Instalar o LibreOffice Fresh - Windows
#   win_chocolatey:
#     # version: latest
#     # force: yes
#     name: libreoffice-Fresh
#   when: ansible_os_family == 'Windows'

- name: Instalar o Unity 2018.2.10 - Windows
  win_chocolatey:
    name: unity
    version: '2018.2.10'
  when: ansible_os_family == 'Windows'

# Comentado porque nao estava funcionando
# - name: Instalar o FreeCad 0.17 - Windows
#   win_chocolatey:
    # version: latest
#     name: freecad
#   when: ansible_os_family == 'Windows'

# Windows atalhos --------------------------------------------------------------------------------------------------------------

- name: Cria o atalho do LibreCad - Windows
  win_shortcut:
    src: '%ProgramFiles(x86)%\LibreCAD\LibreCAD.exe'
    dest: '%Public%\Desktop\LibreCAD.lnk'
    icon: '%ProgramFiles(x86)%\LibreCAD\LibreCAD.exe,0'
  when: ansible_os_family == 'Windows'

- name: Cria o atalho do CADConverter - Windows
  win_shortcut:
    src: '%ProgramFiles%\CoolUtils\TotalCADConverter\CADConverter.exe'
    dest: '%Public%\Desktop\CADConverter.lnk'
    icon: '%ProgramFiles%\CoolUtils\TotalCADConverter\CADConverter.exe,0'
  when: ansible_os_family == 'Windows'

- name: Cria o atalho do Subtitleworkshop - Windows
  win_shortcut:
    src: '%ProgramFiles(x86)%\Subtitle Workshop\SubtitleWorkshop.exe'
    dest: '%Public%\Desktop\SUbtitleWorkshop.lnk'
    icon: '%ProgramFiles(x86)%\Subtitle Workshop\SubtitleWorkshop.exe,0'
  when: ansible_os_family == 'Windows'
