- name: Configurações Debian12 servidor web
  hosts: debian12
  vars:
    server_name: "meusite.com"
    document_root: "/var/www/meusite"

  tasks:
    - name: Instala pacote nginx
      ansible.builtin.apt:
        pkg:
          - nginx
        state: present
      notify: Reiniciar nginx

    - name: Copia arquivo de configuração do nginx
      ansible.builtin.copy:
        dest: /etc/nginx/nginx.conf
        content: |
          worker_processes auto;

          events {
              worker_connections 1024;
          }

          http {
              include       mime.types;
              default_type  application/octet-stream;

              sendfile        on;
              keepalive_timeout  65;

              server {
                  listen       80;
                  server_name  {{ server_name }};

                  location / {
                      root   {{ document_root }};
                      index  index.html index.htm;
                  }
              }
          }
        owner: root
        group: root
        mode: '0644'
      notify: Reiniciar nginx

    - name: Cria diretório
      ansible.builtin.file:
        state: directory
        path: "{{ document_root }}"
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Define arquivo index.html
      ansible.builtin.copy:
        dest: /var/www/meusite/index.html
        content: |
          <H1> Meu Site! </H1>
        owner: www-data
        group: www-data
        mode: '0644'
      notify: Reiniciar nginx

  handlers:
    - name: Reiniciar nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
