---
#Windows
- name: Copiando papel de parede - Windows
  win_copy:
    src: fundo_ifsc_sj_novo.jpg
    dest: C:\Users\
  when: ansible_os_family == 'Windows'

- name: Copiando icone ifsc - Windows
  win_copy:
    src: Icone_ifsc.bmp
    dest: C:\ProgramData\Microsoft\User Account Pictures\Icone_ifsc.bmp
  when: ansible_os_family == 'Windows'

- name: Copiando icone ctic - Windows
  win_copy:
    src: user.bmp
    dest: C:\ProgramData\Microsoft\User Account Pictures\user.bmp
  when: ansible_os_family == 'Windows'

- name: Criando registro chamado Wallpaper dentro do System - Windows
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    name: Wallpaper
    data: C:\Users\fundo_ifsc_sj_novo.jpg
  when: ansible_os_family == 'Windows'

- name: Criando registro chamado WallpaperStyle dentro do System - Windows
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    name: WallpaperStyle
    data: 4
  when: ansible_os_family == 'Windows'

- name: Criando registro chamado UseDefaultTile dentro do Explorer - Windows
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: UseDefaultTile
    data: 1
  when: ansible_os_family == 'Windows'

# Debian

- name: Copiando o plano de fundo para a máquina - Linux
  copy:
    src: fundo_ifsc_sj_novo.jpg
    dest: /home/fundo_ifsc_sj.jpg
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Cria o script que modifica o papel de parede - Linux
  copy:
    src: trocaplanodefundo.sh
    dest: /etc/profile.d/trocaplanodefundo.sh
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'
