---

- name: Baixar Daikin DS-HL2
  ansible.windows.win_get_url:
    url: http://ansiblefiles.sj.ifsc.edu.br/ds_hl2_setup_R1.7.exe
    dest: 'C:\instaladores\ds_hl2_setup_R1.7.exe'
    force: false
    timeout: 300 # 5 minutos
  when: ansible_os_family == 'Windows'

- name: Baixar o patch do ds-hl2 - Windows
  ansible.windows.win_get_url:
    url: http://ansiblefiles.sj.ifsc.edu.br/202209_ds-hl2_r1.7g_p3_patch.dkhlpat
    dest: 'C:\instaladores\202209_ds-hl2_r1.7g_p3_patch.dkhlpat'
    force: false
    timeout: 300 # 5 minutos
  when: ansible_os_family == 'Windows'

