- name: Update all packages to their latest version
  ansible.builtin.apt:
    upgrade: full
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Upgrade the /etc/apt/sources.list
  ansible.builtin.copy:
    content: |
      deb http://debian.c3sl.ufpr.br/debian trixie main contrib non-free non-free-firmware
      deb http://debian.c3sl.ufpr.br/debian trixie-updates main contrib non-free non-free-firmware
      deb http://debian.c3sl.ufpr.br/debian trixie-backports main contrib non-free non-free-firmware

      # Official Debian repositories
      deb http://deb.debian.org/debian trixie main contrib non-free non-free-firmware
      deb http://deb.debian.org/debian trixie-updates main contrib non-free non-free-firmware
      deb http://deb.debian.org/debian trixie-backports main contrib non-free non-free-firmware

      # Debian Security repository
      deb http://security.debian.org/debian-security trixie-security main contrib non-free non-free-firmware
    owner: root
    group: root
    mode: '0644'
    dest: /etc/apt/sources.list
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')

- name: Upgrade the OS (apt-get dist-upgrade) and pass options to dpkg on run
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    dpkg_options: 'force-confold,force-confdef'
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: true
    purge: true
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')

- name: Unconditionally reboot the machine with all defaults
  ansible.builtin.reboot:
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')
