---
#Linux

# Debian stretch
- name: Instalar pacotes necessários do Docker
  apt:
    state: latest
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
  when: (ansible_os_family == 'Debian')

- name: Adicionar a chave do repositório do docker no Debian
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Adicionar repositório do docker no stretch
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present
    update_cache: yes
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'stretch')

- name: Adicionar repositório do docker no buster
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present
    update_cache: yes
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'buster')

- name: Adicionar repositório do docker no bullseye
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
    state: present
    update_cache: yes
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Instalar o docker no debian
  apt:
    state: latest
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: ansible_os_family == 'Debian'

- name: Adiciona ao usuário aluno o grupo docker
  user:
    name: aluno
    groups: [docker]
    append: yes
  when: ansible_os_family == 'Debian'
