---
- name: Cria e configura a conta aluno com a senha aluno em hosts windows
  collections:
    - ansible.windows
  # hosts: sj-labter-614120.maquinas.sj.ifsc.edu.br 
  tasks:
    - name: Create user account "aluno" with password "aluno"
      win_user:
        name: aluno
        password: aluno
        state: present
        
    - name: Set password to never expire for user "aluno"
      win_shell: |
        net user aluno /expires:never
      args:
        executable: cmd

    - name: Prevent user "aluno" from changing the password
      win_shell: |
        net user aluno /passwordchg:no
      args:
        executable: cmd

    - name: Add user "aluno" to local group "Usuários"
      win_group_membership:
        name: Usuários
        members: aluno
        state: present
