#role para colocar o KVM em uma blacklist por conta do virtualbox. VirtualBox trazia o seguinte erro: Please disable KVM kernel extension...

- name: Garantir que o arquivo de blacklist exista
  ansible.builtin.file:
    path: /etc/modprobe.d/blacklist-kvm.conf
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Adicionar blacklist do módulo kvm
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist-kvm.conf
    line: "blacklist kvm"
    state: present

- name: Adicionar blacklist do módulo kvm_amd
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist-kvm.conf
    line: "blacklist kvm_amd"
    state: present

- name: Remover módulos KVM carregados atualmente
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  loop:
    - kvm_amd
    - kvm
  ignore_errors: true

- name: Atualizar initramfs (Debian/Ubuntu)
  ansible.builtin.command: update-initramfs -u
  when: ansible_os_family == "Debian"
  changed_when: true