# Linux
- name: Instalar os pacotes para o octave - Linux
  ansible.builtin.apt:
    pkg:
      - octave
      - octave-communications
      - octave-control
      - octave-signal
      - octave-statistics
  when: ansible_os_family == 'Debian'

# Windows
- name: Baixar e instalar Octave - Windows
  chocolatey.chocolatey.win_chocolatey:
    name: octave
  when: ansible_os_family == 'Windows'
