- name: Instalar pacotes necessarios para o Quartus 20 - Linux Debian 11
  ansible.builtin.apt:
    pkg:
      - libc6:i386
      - libncurses5:i386
      - libstdc++6:i386
      - libfreetype6:i386
      - libsm6:i386
      - libxrender1:i386
      - libfontconfig1:i386
      - libxext6:i386
      - libxtst6:i386
      - libxi6:i386
      - libgtk2.0-0:i386
      - libxft2
      - libxft2:i386
      - libc6-dev-i386
      - lib32z1
  when: ansible_os_family == 'Debian'

- name: Extraindo Quartus 20.1
  ansible.builtin.unarchive:
    src: http://ansiblefiles.sj.ifsc.edu.br/quartus_20.1.tgz
    dest: /opt/
    creates: /opt/intelFPGA
    remote_src: true
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'Debian'

- name: Copiando o icone do modelsim - Debian 11
  ansible.builtin.copy:
    src: modelsim.png
    dest: /opt/intelFPGA/20.1/modelsim_ae/modesim.png
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Adiciona LOCALE en_US.UTF-8
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    insertafter: "# en_US.UTF-8 UTF-8"
    line: en_US.UTF-8 UTF-8
    state: present
  when: ansible_os_family == 'Debian'

- name: Define o /usr/share/applications/{{ altera_desktop }}
  copy:
    src: "{{ altera_desktop }}"
    dest: /usr/share/applications/
    owner: root
    group: root
    mode: 0644
  loop:
    - quartus20.1.desktop
    - modelsim20.1.desktop
  loop_control:
    loop_var: altera_desktop
  when: ansible_os_family == 'Debian'
