- name: Enable i386 architecture
  ansible.builtin.command: dpkg --add-architecture i386
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: Instalar pacotes necessarios para o Quartus 20 - Linux Debian 11
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - libc6:i386
      - libncurses5:i386
      - libstdc++6:i386
      - libfreetype6:i386
      - libsm6:i386
      - libxrender1:i386
      - libfontconfig1:i386
      - libxext6:i386
      - libxtst6:i386
      - libxi6:i386
      - libgtk2.0-0:i386
      - libxft2
      - libxft2:i386
      - libc6-dev-i386
      - lib32z1
      - xterm
  when: ansible_os_family == 'Debian'

- name: Create directory /opt/altera
  ansible.builtin.file:
    path: /opt/altera
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family == 'Debian'

- name: Extraindo Quartus 20.1
  ansible.builtin.unarchive:
    src: http://ansiblefiles.sj.ifsc.edu.br/quartus_20.1.tgz
    dest: /opt/altera
    creates: /opt/altera/intelFPGA
    remote_src: true
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family == 'Debian'

- name: Copiando o icone do modelsim - Debian 11
  ansible.builtin.copy:
    src: modelsim.png
    dest: /opt/altera/intelFPGA/20.1/modelsim_ae/modelsim.png
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Ensure a locale en_US.UTF-8 exists
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present
  when: ansible_os_family == 'Debian'

- name: Define o /usr/share/applications/{{ altera_desktop }}
  ansible.builtin.copy:
    src: "{{ altera_desktop }}"
    dest: /usr/share/applications/
    owner: root
    group: root
    mode: '0644'
  loop:
    - quartus20.1.desktop
    - modelsim20.1.desktop
  loop_control:
    loop_var: altera_desktop
  when: ansible_os_family == 'Debian'

# Configuração das variáveis de licença
- name: Adicionar entrada MGLS_LICENSE_FILE export no /etc/security/pam_env.conf - Linux
  ansible.builtin.lineinfile:
    regexp: '^MGLS_LICENSE_FILE'
    path: /etc/security/pam_env.conf
    line: 'MGLS_LICENSE_FILE   DEFAULT=1800@license-server.sj.ifsc.edu.br'
  when: ansible_os_family == 'Debian'

- name: Adicionar entrada LM_LICENSE_FILE export no /etc/security/pam_env.conf - Linux
  ansible.builtin.lineinfile:
    regexp: '^LM_LICENSE_FILE'
    path: /etc/security/pam_env.conf
    line: 'LM_LICENSE_FILE     DEFAULT=1800@license-server.sj.ifsc.edu.br'
  when: ansible_os_family == 'Debian'

- name: Script do jtagd
  ansible.builtin.copy:
    content: |
      pkill -f jtagd -9; /opt/altera/intelFPGA/20.1/quartus/bin/jtagd --user-start;  /opt/altera/intelFPGA/20.1/quartus/bin/jtagconfig
    dest: /usr/local/bin/jtagd
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family == 'Debian'

- name: Copia o arquivo altera-usb-blaster.rules - Linux
  ansible.builtin.copy:
    content: |
      ATTR{idVendor}=="09fb", ATTR{idProduct}=="6001", MODE="666"
      ATTR{idVendor}=="09fb", ATTR{idProduct}=="6002", MODE="666"
      ATTR{idVendor}=="09fb", ATTR{idProduct}=="6003", MODE="666"
      ATTR{idVendor}=="09fb", ATTR{idProduct}=="6010", MODE="666"
      ATTR{idVendor}=="09fb", ATTR{idProduct}=="6810", MODE="666"
    dest: /etc/udev/rules.d/altera-usb-blaster.rules
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family == 'Debian'
