### https://www.kubuntuforums.net/showthread.php/30058-How-To-Choose-Custom-Location-and-Filename-with-CUPS-PDF
# Script que faz um salvar como para os documentos impressos pela impressora PDF do cups.

- name: Instala cups-pdf
  ansible.builtin.apt:
    pkg:
      - printer-driver-cups-pdf
  when: ansible_os_family == 'Debian'

- name: Script para renomear arquivos impressos
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      CURRENT_PDF="${1}"
      CURRENT_USER="${2}"
      DISPLAY=:0.0
      export DISPLAY
      XAUTHORITY=/home/${CURRENT_USER}/.Xauthority
      export XAUTHORITY
      PDFNAME=$(zenity --file-selection --save --confirm-overwrite)
      mv "$CURRENT_PDF" "$PDFNAME"
    dest: /usr/local/bin/cups-pdf-rename
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family == 'Debian'

- name: Configura /etc/cups/cups-pdf.conf
  ansible.builtin.replace:
    path: /etc/cups/cups-pdf.conf
    backup: true
    regexp: '#PostProcessing'
    replace: 'PostProcessing /usr/local/bin/cups-pdf-rename'
  when: ansible_os_family == 'Debian'
  notify: Restart_cups

- name: Permissão para o script ser executado
  ansible.builtin.lineinfile:
    path: /etc/apparmor.d/usr.sbin.cupsd
    regexp: '/var/spool/cups-pdf/'
    line: '  /usr/local/bin/cups-pdf-rename uxr,'
    backup: true
  when: ansible_os_family == 'Debian'
  notify: Restart_apparmor
