- name: Enable autologin to aluno
  ansible.builtin.replace:
    path: /etc/lightdm/lightdm.conf
    backup: true
    regexp: '#autologin-user='
    replace: 'autologin-user=aluno'
  when: ansible_os_family == 'Debian'
  tags: lightdm

- name: Ensure group "autologin" exists
  ansible.builtin.group:
    name: autologin
    system: true
  when: ansible_os_family == 'Debian'
  tags: lightdm

- name: Add aluno to autologin group
  ansible.builtin.user:
    name: aluno
    groups: autologin
    append: true
  when: ansible_os_family == 'Debian'
  tags: lightdm
