- name: Instalar os pacotes para o token SafeNet
  ansible.builtin.apt:
    pkg:
      - libc6
      - libgcc1
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libgtk2.0-0
      - libpango-1.0-0
      - libpcsclite1
      - libstdc++6
      - libx11-6
      - lsb-base
      - libnss3-tools
  when: ansible_os_family == 'Debian'

- name: Instala o Safenet Authenticator Client
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop:
    - http://ansiblefiles.sj.ifsc.edu.br/libssl1.1_1.1.1w-0+deb11u2_amd64.deb
    - http://ansiblefiles.sj.ifsc.edu.br/SafenetAuthenticationClient-BR-10.7.77-amd64.deb
  when: ansible_os_family == 'Debian'

- name: Script para habilitar módulo no navegador
  ansible.builtin.copy:
    content: |
      #!/bin/bash

      # Enconta onde está o arquivo db
      PERFIL=$(dirname $(find ~/.mozilla -name "cert9.db"))
      if [[ -z "$PERFIL" ]]; then
          echo "Nenhum perfil encontrado para este usuario."
          exit
      fi

      # Ativa modulo do Safesign
      modutil -add "SafeSign PKCS #11 Library" -libfile /usr/lib/libeTPkcs11.so -dbdir $PERFIL -force >/dev/null 2>&1
      echo "Cadeias e modulo SafeSign instalados no Mozilla Firefox do usuario $USER."
      modutil -add "SafeSign PKCS #11 Library" -libfile /usr/lib/libeTPkcs11.so -dbdir sql:.pki/nssdb/ -force >/dev/null 2>&1
      echo "Cadeias e modulo SafeSign instalados no Google Chrome do usuario $USER."

      echo "Pressione <ENTER> para sair"
      read input

    dest: /usr/local/bin/habilita_token_safenet.sh
    mode: '0755'
  when: ansible_os_family == 'Debian'

- name: Cria lançador do script para habilitar módulo no navegador
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Version=1.0
      Name= Habilita módulo Safenet nos navegadores
      Comment= Habilita módulo Safenet nos navegadores Mozilla Firefox e Google Chrome
      Exec=bash -c '/usr/local/bin/habilita_token_safenet.sh && exit'
      Icon=utilities-terminal
      Terminal=true
      Type=Application
      Categories=Application;
    dest: /usr/share/applications/habilita_token_safenet.desktop
    mode: '0755'
  when: ansible_os_family == 'Debian'
