---
#Linux

- name: Copy install file
  copy:
    src: SafenetAuthenticationClient-BR-10.0.37-0_amd64.deb
    dest: /tmp
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == 'buster'

- name: Install SafeNet
  apt:
    deb: /tmp/SafenetAuthenticationClient-BR-10.0.37-0_amd64.deb
  when: ansible_distribution_release == 'buster'
