######### Linux

- name: Copia arquivo de senha
  ansible.builtin.copy:
    src: grub-debian
    dest: /etc/grub.d/40_custom
    owner: root
    group: root
    mode: '0700'
  when: ansible_os_family == 'Debian'

- name: Aplica unrestricted no arquivo /etc/grub.d/10_linux - Linux
  ansible.builtin.replace:
    path: /etc/grub.d/10_linux
    regexp: '--class os"'
    replace: '--class os --unrestricted"'
    backup: true
  when: ansible_os_family == 'Debian'
  notify:
    - update grub

- name: Aplica unrestricted no arquivo /etc/grub.d/30_os-prober para o windows - Linux
  ansible.builtin.replace:
    path: /etc/grub.d/30_os-prober
    regexp: '--class os \\'
    replace: '--class os --unrestricted \\'
    backup: true
  when: ansible_os_family == 'Debian'
  notify:
    - update grub

- name: Modifica o arquivo /etc/default/grub - Debian
  ansible.builtin.copy:
    src: "{{ tipo }}"
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'
  notify:
    - update grub
