---
#Linux
- name: Instala wpasupplicant - Linux
  apt:
    state: latest
    pkg:
    - wpasupplicant
  when: ansible_os_family == 'Debian'

- name: Instala iwlwifi - Debian 11
  apt:
    state: latest
    pkg:
    - firmware-iwlwifi
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bullseye')

- name: Copiando arquivo interfaces - Linux
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: Copiando arquivo wpa_supplicant - Linux
  copy:
    src: wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0600
  when: ansible_os_family == 'Debian'
