- name: Adiciona chave para o 'Debian'
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/trusted.gpg.d/google.asc
    mode: '0644'
    owner: root
    group: root
  when: ansible_os_family == 'Debian'

- name: Adiciona repositório para o 'Debian'
  ansible.builtin.copy:
    content: |
      deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    dest: /etc/apt/sources.list.d/google-chrome.list
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Instala google-chrome do repositorio
  ansible.builtin.apt:
    name: google-chrome-stable
    update_cache: true
  when: ansible_os_family == 'Debian'
