### Comando em powershell para mostrar product_id
### get-wmiobject Win32_Product | Format-Table IdentifyingNumber, Name, LocalPackage -AutoSize
### Localizacao do productid 32 bits: HKLM:Software\Microsoft\Windows\CurrentVersion\Uninstall
### Localizacao do productid 64 bits: HKLM:Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall

- name: Cria pasta para instaladores
  ansible.windows.win_file:
    path: C:\instaladores
    state: directory
  when: ansible_os_family == 'Windows'

- name: Baixa AutoCAD_2024.exe
  ansible.windows.win_get_url:
    url: http://ansiblefiles.sj.ifsc.edu.br/AutoCAD_2024.exe
    dest: 'C:\instaladores\AutoCAD_2024.exe'
    force: false
    timeout: 300 # 5 minutos
  when: ansible_os_family == 'Windows'

- name: Executa o criação da instalação do AutoCAD 2024
  ansible.windows.win_package:
    path: C:/instaladores/AutoCAD_2024.exe
    arguments:
      - -q
    # product_id: '{28B89EEF-7101-0409-2102-CF3F3A09B77D}'
    state: present
  when: ansible_os_family == 'Windows'

- name: Executa o instalador do AutoCAD 2024
  ansible.windows.win_command: 'installer.exe -i deploy --offline_mode --ui_mode basic -q -o Collection.xml --installer_version 2.18.0.111'
  args:
    chdir: C:\Autodesk\{78B472F6-3A2B-4C77-AC8B-3ECE56221111}\image
  when: ansible_os_family == 'Windows'

##### LOCALMENTE O COMANDO FUNCIONA, MAS NÃO FUNCIONA VIA ANSIBLE E NEM VIA SCRIPT LOCAL #####
# - name: Comando para corrigir problema com a licença do AutoCAD 2024
#   ansible.windows.win_command:
#   args:
#     - "C:\Program Files (x86)\Common Files\Autodesk Shared\AdskLicensing\Current\helper\AdskLicensingInstHelper.exe"
#     - register
#     - --pk 001P1
#     - --pv 2024.0.0.F
#     - --cf "C:\Autodesk\AutoCAD_2024_English_Win_64bit_dlm\x64\acadprivate\AutoCADConfig.pit"
#     - -el US
#     - --lic_server_type SINGLE
#     - --lic_servers license-server.sj.ifsc.edu.br
#   when: ansible_os_family == 'Windows'

- name: Reinicia o computador
  ansible.windows.win_reboot:
    msg: "Reiniciando o computador para finalizar a instalação do AutoCAD 2024"
    pre_reboot_delay: 60
    reboot_timeout: 600
    post_reboot_delay: 60
  when: ansible_os_family == 'Windows'
  tags: limpa

- name: Apaga pasta C:/Autodesk
  ansible.windows.win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - C:\Autodesk
    - C:\Users\ctic\Desktop\AutoCAD_2024.lnk
  when: ansible_os_family == 'Windows'
  tags: limpa
