# - name: Create user account "aluno" with password "aluno"
#   win_user:
#     name: aluno
#     password: aluno
#     state: present
    
# - name: Set password to never expire for user "aluno"
#   win_shell: |
#     net user aluno /expires:never
#   args:
#     executable: cmd

# - name: Prevent user "aluno" from changing the password
#   win_shell: |
#     net user aluno /passwordchg:no
#   args:
#     executable: cmd

# - name: Add user "aluno" to local group "Usu치rios"
#   win_group_membership:
#     name: Usu치rios
#     members: aluno
#     state: present
#
- name: Manage local user aluno on a Windows remote host
  hosts: sje-ctic-866467.maquinas.sj.ifsc.edu.br
  gather_facts: no

  vars:
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Ensure user "aluno" exists and set password
      win_user:
        name: aluno
        password: aluno
        password_never_expires: yes
        user_cannot_change_password: yes
        state: present

    - name: Add user "aluno" to local group "Usu치rios"
      win_group_membership:
        name: Usu치rios
        members:
          - aluno
        state: present

...
