- name: Instalar pacotes necessarios para o packettracer 8 - Linux Debian 12
  ansible.builtin.apt:
    pkg:
      - libqt5websockets5
      - libqt5webkit5
      - libqt5webkit5-dev
      - dialog
      - libgl1-mesa-glx
      - libxcb-xinerama0-dev
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')

- name: Install cisco packet tracer 8.2.1
  ansible.builtin.apt:
    deb: http://ansiblefiles.sj.ifsc.edu.br/CiscoPacketTracer_821_Ubuntu_64bit.deb
  when: (ansible_os_family == 'Debian' and ansible_distribution_release == 'bookworm')
